README.md
Be nice with your users ... :)
=> Fixed example compilation issues

src/main/kotlin/org/jetbrains/exposed/sql/Transaction.kt
Allow deleting keys from UserDataHolder
=> Allow deleting keys from UserDataHolder

src/main/kotlin/org/jetbrains/exposed/sql/transactions/ThreadLocalTransactionManager.kt, src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ThreadLocalManagerTest.kt
I have myself only run the new tests. I do not have a working test setup for running the rest.
Additionally various calls to `Statement.close()` might not be properly handled either but I did not have time to create a test demonstrating this.
=> Properly handle exceptions on getConnection and Connection.commit(), .rollback() and .close()

src/main/kotlin/org/jetbrains/exposed/sql/vendors/H2.kt, src/test/kotlin/org/jetbrains/exposed/sql/tests/DatabaseTestsBase.kt, src/test/kotlin/org/jetbrains/exposed/sql/tests/h2/H2Tests.kt, src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt
=> H2 unwrapping connection to get mode properly

src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt
I needed that for some PostgreSQL functions. It is probably also useful for other DBMSes.
=> Add support for float values in DecimalColumnType

README.md
=> fix compilation in example

src/main/kotlin/org/jetbrains/exposed/sql/Database.kt
In a bigger project we use Exposed the `Connection` is provided to our code. It would be helpful if `Database` could be connected using `Connection` too.
=> Support passing lambda to get a new Connection to Database too

src/main/kotlin/org/jetbrains/exposed/dao/Entity.kt, src/main/kotlin/org/jetbrains/exposed/sql/Table.kt
Because I think code documentation is very important I have added some JavaDocs to the Entity classes and the column types in the Table.kt file.
=> Added JavaDocs to Entity classes and column types in Table.

spring-transaction/src/main/kotlin/org/jetbrains/exposed/spring/SpringTransactionManager.kt, spring-transaction/src/test/kotlin/org.jetbrains.exposed.spring/EntityUpdateTest.kt
spring-transaction does not execute update statement of DAO.
=> Fix entity update by spring-transaction

src/main/kotlin/org/jetbrains/exposed/sql/Constraints.kt, src/main/kotlin/org/jetbrains/exposed/sql/Queries.kt, src/main/kotlin/org/jetbrains/exposed/sql/SchemaUtils.kt, src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, src/main/kotlin/org/jetbrains/exposed/sql/vendors/H2.kt, src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt
Add custom name for constraints to cater for possible naming conventions for constraints.
=> Add custom name for constraints

src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt
The existing project only provided for Float's (with just 4 bytes of precision), added Double's
=> added double precision column type

exposed/src/main/kotlin/org/jetbrains/exposed/sql/transactions/TransactionApi.kt
This is my first draft that would close #523, the only issue I currently see is when you'd add the same TransactionManager for multiple databases and then removed it (it remove the first occurrence from the List, but not necessarily the *right* one); or register *another* TransactionManager for the same database, basically creating a "dead" manager inside the list, this issue should be easily fixable though.
Looking forward to your opinions on my PR.
=> Add method to close and unregister a database connection [DRAFT 1]

exposed/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt
Hi, I try to implement fix for #220 bug.
If it's not correct, do not mind to close this PR.
=> Escape collate (#220)

exposed/src/main/kotlin/org/jetbrains/exposed/sql/Database.kt
Fixes https://github.com/JetBrains/Exposed/issues/596
=> Fixed needQuotes check

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DMLTests.kt
=> Enable comparing(less/lessEq/greater/greaterEq) to nullable column

exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/java-time/JavaDateColumnType.kt
=> Do not use INSTANCE for column types

exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityCache.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityTests.kt
=> NoSuchElementException: List is empty on EntityClass.new(id) with EntityClass.get

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/UpdateBuilder.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DMLTests.kt
=> Change string length check to use codePointCount

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Column.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Constraints.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt
Performed the following changes:
- Added KDoc comments to most public declarations. There are still a few I didn't know how to describe.
- Rearranged some declarations to group them by functionality.
- Reformatted code to follow Kotlin Coding Conventions.
- Created backing property for property `indices` to avoid cast to `MutableList` in `Table` class.
- Refactored code to use `mutableListOf()` instead of `ArrayList()`.
- Replaced guard clause with kotlin function call.
- Improved computation of `columns` property in `Join` class, used `flatMap` instead of `fold` to reduce the number of list creations.
- Removed unused type parameter from `addColumn()` method.
- Added identity check to `equals` method in `Table` class.
- Improved table checker on `Index` creation, used `distinctBy` …
=> [KDoc & Format] Table & Columns

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Sequence.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt
This PR is to remove redundant code that creates sequence and to add [IF EXISTS] option in the "drop sequence" command.
=> removing redundant code related to create sequence and adding [IF EXISTS] option in the "drop sequence" command.

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Column.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Constraints.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SchemaUtils.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Mysql.kt, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcDatabaseMetadataImpl.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateTableTests.kt
=> Support custom foreign key naming

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Database.kt
Database driver didn't found -> Database driver not found
=> Fix grammar

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt
I know that I've request the change from object to open class, but I think it could be better as interface?
=> Change SqlExpressionBuilderClass to Interface

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Op.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/MiscTableTest.kt, exposed-jodatime/src/test/kotlin/org/jetbrains/exposed/JodaTimeMiscTableTest.kt, exposed-tests/src/main/kotlin/org/jetbrains/exposed/sql/tests/shared/MiscTable.kt
A couple of tests are not working for me on master but I think I got a pass on all relevant tests.
=> Added ByteColumnType.

docs/ChangeLog.md, gradle.properties
To make life easier for the next minor release.
=> 0.25.2 changelog and version

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Transaction.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ParameterizationTests.kt
=> Support passing query parameters

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Op.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Mysql.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt
Adds support for UNSIGNED byte, short, integer column type. #199
This pull request is a continuation of PR #908 .
=> unsigned byte, short, int type column

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Column.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateTableTests.kt
=> allow NOT NULL modifier for PK column in SQLite

exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcDatabaseMetadataImpl.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateMissingTablesAndColumnsTests.kt
Fix foreign key creation in PostgreSQL
=> Issue #934 (https://github.com/JetBrains/Exposed/issues/934)

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Database.kt, gradle.properties
This is a proposal on how to add the option to manually define driver and dialect.
See issue #1023
=> Enhancement issue #1023

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt
Just making nullable columns have support to default values
=> Add support to default values in Columns with nullable type

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Queries.kt
According to the following two documents, indices in SQLite whose names start with "sqlite_" are meant for internal use.
https://www.sqlite.org/optoverview.html#autoindex
https://www.sqlite.org/fileformat2.html#intschema
I think they probably shouldn't be reported as "not mapped".
=> Ignore internal SQLite indices on checkMissingIndices

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Op.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt
Supporting subquery as condition with '=' and '!=' operator:  `SELECT * FROM x WHERE id = (SELECT MAX(id) FROM x WHERE cond = y)`
=> Add EqSubQueryOp and NotEqSubQueryOp operators

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Op.kt
#1109. so far without documentation for methods.
=> Additional functionality for query dsl (#1109)

exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcDatabaseMetadataImpl.kt
Fixes #1168 
Driver name for v0.7.1 is "PostgreSQL JDBC - NG"
see: [PGDatabaseMetaData.getDriverName()](https://github.com/impossibl/pgjdbc-ng/blob/3d736776922da4b52907e46f1ddb78f5b71e1675/src/main/java/com/impossibl/postgres/jdbc/PGDatabaseMetaData.java#L230)
=> Support pgjdbc-ng 0.7.1

exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityHook.kt
Writing to the list of events is a common occurrence, which currently results in the creation of an entire array of existing events, an O(n^2) operation.  Using a concurrent queue should reduce the footprint of this operation.
Extracted backwards-compatible change from #1133.
=> Replace copying arraylists w/ concurrent queues

.github/workflows/gradle-validation.yml
https://youtrack.jetbrains.com/issue/KT-45551
See: https://github.com/gradle/wrapper-validation-action for more details.
=> Add Gradle Wrapper Validation

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcDatabaseMetadataImpl.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ConnectionTests.kt
=> Add autoIncrement to ColumnMetaData

exposed-jodatime/src/main/kotlin/org/jetbrains/exposed/sql/jodatime/DateColumnType.kt, exposed-jodatime/src/test/kotlin/org/jetbrains/exposed/JodaTimeMiscTableTest.kt
Using the test infrastructure for now as it does not work locally for me.
=> WIP: Restore old 0000-00-00 00:00:00 as null behavior for Mysql and MariaDb

exposed-java-time/src/test/kotlin/org/jetbrains/exposed/MiscTableTest.kt, exposed-jodatime/src/main/kotlin/org/jetbrains/exposed/sql/jodatime/DateColumnType.kt, exposed-jodatime/src/test/kotlin/org/jetbrains/exposed/JodaTimeMiscTableTest.kt
=> Added 0000-00-00 00:00:00 test for java-time module also.

exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcDatabaseMetadataImpl.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateMissingTablesAndColumnsTests.kt
The details of this pull request are explained in issue #1282
Fixes #1282
=> Normalized the targetColumnName for camelCase column names

buildSrc/src/main/kotlin/org/jetbrains/exposed/gradle/DockerTestContainers.kt, buildSrc/src/main/kotlin/org/jetbrains/exposed/gradle/Versions.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Expression.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/H2.kt, exposed-tests/src/main/kotlin/org/jetbrains/exposed/sql/tests/DatabaseTestsBase.kt, exposed-tests/src/main/kotlin/org/jetbrains/exposed/sql/tests/shared/Assert.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/h2/MultiDatabaseEntityTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/h2/MultiDatabaseTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ConnectionTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/functions/MathFunctionTests.kt
New TC config with new dialect: `h2_v2` is needed
=> Add H2 version 2.0.202 dialect

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Query.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/AdjustQueryTests.kt
This PR closes https://github.com/JetBrains/Exposed/issues/1296
=> Add `adjustHaving`, `andHaving`, `orHaving` extension methods for `Query`

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt
This PR fixes https://github.com/JetBrains/Exposed/issues/1415
=> Fix check constraints

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-crypt/build.gradle.kts, exposed-crypt/src/main/kotlin/org/jetbrains/exposed/crypt/Algorithms.kt, exposed-crypt/src/main/kotlin/org/jetbrains/exposed/crypt/EncryptedBinaryColumnType.kt, exposed-crypt/src/main/kotlin/org/jetbrains/exposed/crypt/EncryptedVarCharColumnType.kt, exposed-crypt/src/main/kotlin/org/jetbrains/exposed/crypt/Encryptor.kt, exposed-crypt/src/main/kotlin/org/jetbrains/exposed/crypt/Tables.kt, exposed-tests/build.gradle.kts, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/SelectTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/UpdateTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/functions/FunctionsTests.kt, settings.gradle.kts
issue: #419 
I've used spring-security-crypto for Encryption, but if it is necessary to replace it with javax.crypto or [bouncy castle](https://github.com/bcgit/bc-java), I'll do
=> Add encrypted column type

docs/ChangeLog.md
Fix a typo and link to the mentioned unit test.
=> Changelog improvements

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Op.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLServerDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/LikeTests.kt
Proof of concept for adding escaping to like expressions. If the whole `LikePattern` gets a bit strange I can reduce it to just have the new `LikeEscapeOp`
=> Escaping to like expressions.

exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ThreadLocalManagerTest.kt
=> fix read_only test

docs/README.md
I added significant changes to subheadings in the Readme.md file  such as  Community, Recommended mode of communication , pull requests.  I also added  icon badges to ensure easy readability.
I would also recommend that you add a funding Header header to the Readme file. Below are screen shots of the changes I made.
=> Readme.md Redoo

docs/README.md
Open Sauced (https://github.com/open-sauced/open-sauced) doesnt seem to be related to this project.
=> Open Sauced -> Exposed

exposed-spring-boot-starter/README.md
[Question came up in Slack](https://kotlinlang.slack.com/archives/C0CG7E0A1/p1671493542406279), and noticed its not immediately obvious how to configure things when using the Spring starter.
=> Document configuration when using Spring starter

docs/README.md, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/demo/dao/SamplesDao.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/demo/sql/SamplesSQL.kt
Mention reducing H2 1.x support.
Add kotlinlang slack invitation link.
Fix discrepancy between demo code blocks and generated sql blocks:
- Show more accurate logged output for given H2 jdbc connection.
- Remove test assertations.
- Fix whitespace.
=> fix: EXPOSED-31 Landing Readme links and demo code

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Op.kt, spring-transaction/src/test/kotlin/org/jetbrains/exposed/spring/EntityUpdateTest.kt, spring-transaction/src/test/kotlin/org/jetbrains/exposed/spring/ExposedTransactionManagerTest.kt
This PR removes `detekt` `ClassNaming` issues and reformats the affected files.
=> chore: remove detekt ClassNaming issues

docs/CONTRIBUTING.md
Added point regarding API check as it seems like it's not mentioned anywhere for contributors.
=> docs: add a point in CONTRIBUTING.md regarding API check

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Expression.kt
Method valueToString can be expensive, for example, if we bind arrays as a custom datatype.
Almost always registerArguments gets only one argument.
=> QueryBuilder.registerArguments - avoid potentially expensive valueToString call unless we need to sort values

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Function.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/WindowFunction.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/H2.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Mysql.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLiteDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/DMLTestData.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/functions/WindowFunctionsTests.kt
-Support of partition by and order by clauses
-Support of window frame clause (without EXCLUDE)
-Factories for common window functions
-Support for using aggregate functions as window functions
=> #623 Add support of window functions in Exposed DSL

.editorconfig, .idea/detekt.xml, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Constraints.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/functions/math/MathFunctions.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/transactions/ThreadLocalTransactionManager.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/Entity.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityClass.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/References.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/DefaultsTest.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/JavaTimeTests.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/MiscTableTest.kt, exposed-jodatime/src/test/kotlin/org/jetbrains/exposed/JodaTimeDefaultsTest.kt, exposed-jodatime/src/test/kotlin/org/jetbrains/exposed/JodaTimeMiscTableTest.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/DefaultsTest.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinTimeTests.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/MiscTableTest.kt, exposed-spring-boot-starter/src/test/kotlin/org/jetbrains/exposed/jdbc_template/AuthorTable.kt, exposed-spring-boot-starter/src/test/kotlin/org/jetbrains/exposed/jdbc_template/BookService.kt, exposed-spring-boot-starter/src/test/kotlin/org/jetbrains/exposed/jdbc_template/JdbcConfiguration.kt, exposed-spring-boot-starter/src/test/kotlin/org/jetbrains/exposed/jdbc_template/JdbcTemplateTests.kt
- Modify `max_line_length` value in `.editorconfig` to match that of `detekt.yml`
- Modify detekt IntelliJ plugin configuration in detekt.xml because the fields were not being applied correctly
- Remove more `detekt` issues before merging #1765
=> chore: Modify max_line_length value in .editorconfig to match that of detekt.yml

docs/BREAKING_CHANGES.md
Add breaking changes for version 0.43.0.
=> docs: Update BREAKING_CHANGES.md

documentation-website/Writerside/topics/Table-Definition.md, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt
Add KDoc for `databaseGenerated` feature
=> docs: Add KDoc for `databaseGenerated` feature

documentation-website/Writerside/topics/Asynchronous-Support.md, documentation-website/Writerside/topics/Data-Types.md, documentation-website/Writerside/topics/Deep-Dive-into-DSL.md, documentation-website/Writerside/topics/Frequently-Asked-Questions.md, documentation-website/Writerside/topics/Getting-Started.md, documentation-website/Writerside/topics/Working-with-Transaction.md
These are the additions I've made to the Wiki over the last couple months, following user feedback and questions, which haven't been brought over to `documentation-website` yet.
=> docs: Add missing Wiki documentation

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/functions/FunctionsTests.kt
=> Use concat when strings are added

documentation-website/Writerside/topics/Data-Types.md
The current docs (and old Wiki) detail `kotlinx.serialization` support for JSON columns before mentioning that the underlying `json()` accepts any generic serialization/deserialization combo.
This gives the wrong impression that it is not possible to use libraries like Jackson or GSON instead.
The docs now explain clearly that the choice of JSON serialization/deserialization library is left to the user and also includes a comparative example of column definition with Jackson.
=> docs: EXPOSED-313 JSON columns support libraries other than kotlinx.serialization

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Queries.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/ReturningTests.kt
Add `deleteReturning()` as a task of PR #2060
=> feat: EXPOSED-357 Support DELETE...RETURNING statement

documentation-website/Writerside/topics/Breaking-Changes.md
Add a section to Breaking_Changes regarding PR #2055
=> chore: Add spring-boot-starter dependency breaking change

.github/workflows/docs-workflow.yml
I also updated release guide to reflect documentation update process
=> Add workflow to build documentation website

exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/javatime/JavaDateColumnType.kt, exposed-kotlin-datetime/src/main/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinDateColumnType.kt
Check if database date value could be simplified.
=> chore: Simpler parsing DB date

samples/exposed-migration/README.md, samples/exposed-migration/build.gradle.kts, samples/exposed-migration/src/main/kotlin/Application.kt, samples/exposed-migration/src/main/kotlin/GenerateMigrationScript.kt
Added a Gradle task to the migration sample project to generate the migration script without applying the migration.
=> chore: Add `generateMigrationScript` task to migration sample project

.github/PULL_REQUEST_TEMPLATE.md
**Summary of the change**: Add template for the new pull request
- **Why**: To build changelogs and weekly summaries automatically
---
=> chore: Create PR template

exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/BooleanColumnTypeTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/NumericColumnTypesTests.kt
**Summary of the change**: Added tests for params
---
---
=> test: Add tests for params

documentation-website/Writerside/cfg/build-script.xml, documentation-website/Writerside/cfg/buildprofiles.xml, documentation-website/Writerside/writerside.cfg
Fix the build script configuration and add variables for topic titles and sitemap generation.
---
[WH-5582](https://youtrack.jetbrains.com/issue/WH-5582)
=> chore: docs: Adjust Writerside build config

documentation-website/Writerside/topics/Frequently-Asked-Questions.md
**Summary of the change**: Fix link to @tapac in FAQ.
---
=> docs: Fix link in FAQ

documentation-website/Writerside/cfg/buildprofiles.xml, documentation-website/Writerside/writerside.cfg
Update the URL of the header link to point to the new home page.
---
[EXPOSED-738](https://youtrack.jetbrains.com/issue/EXPOSED-738) Exposed documentation linking to the website
=> EXPOSED-738 Update landing page link

documentation-website/Writerside/snippets/exposed-transactions/README.md, documentation-website/Writerside/snippets/exposed-transactions/src/main/kotlin/org/example/App.kt, documentation-website/Writerside/snippets/exposed-transactions/src/main/kotlin/org/example/examples/SavepointExample.kt, documentation-website/Writerside/topics/Frequently-Asked-Questions.md, documentation-website/Writerside/topics/Transactions.md
Update the FAQ topic in the following ways:
- remove "Q:" and "A:" prefixes
- replace external GH issue links with internal ones referencing the docs
- remove StackOverflow link at the end
- add documentation for savepoint in "Working with Transactions"
Q&A added:
- What is Exposed?
- Is it possible to use a low-level JDBC connection directly with Exposed?
- Is it possible to generate SQL without a database connection?
- How can I convert a DSL query result to a DAO entity?
Q&A removed:
- What is the difference between Squash and Exposed?
- Where can I find snapshot builds of Exposed?
---
---
[EXPOSED-567](https://youtrack.jetbrains.com/issue/EXPOSED-567)
[EXPOSED-554](https://youtrack.jetbrains.com/issue/EXPOSED-554)
=> docs: EXPOSED-567 Update the FAQ topic

buildSrc/src/main/kotlin/org/jetbrains/exposed/gradle/Publishing.kt
Fix the "Could not read PGP secret key" issue on publishing packages
---
---
=> fix: Fix 'Could not read PGP secret key' issue

exposed-dao/build.gradle.kts, exposed-dao/src/main/kotlin/org/jetbrains/exposed/v1/dao/EntityHook.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/statements/R2dbcConnectionImpl.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/v1/tests/shared/entities/EntityHookTest.kt
Fix of the issues with `No transaction in context` if the application is used with ktor
---
=> fix: Fix `No transaction in context` for ktor

documentation-website/Writerside/cfg/buildprofiles.xml, documentation-website/Writerside/cfg/google-search.html
[EXPOSED-852](https://youtrack.jetbrains.com/issue/EXPOSED-852) Add Google Analytics to Exposed Docs
=> docs: build: EXPOSED-852 Add GA4 script

exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/transactions/TransactionManager.kt
Fix restoring context for r2dbc transactions created for multiple databases.
The key is the method `withTransactionContext(transaction)` that takes transaction, saves it in the context and thread locals, and cleans everything in the end of execution.
=> chore: Fix restoring context with R2DBC transaction

documentation-website/Writerside/topics/Statement-Interceptors.md
Update broken API links in Statement-Interceptors.md
[EXPOSED-883](https://youtrack.jetbrains.com/issue/EXPOSED-883)
=> docs: fix: EXPOSED-883 Broken API links in Statement-Interceptors.md
