JetBrains/Exposed

src/main/kotlin/org/jetbrains/exposed/dao/IntEntity.kt
This PR adds a `columnName` parameter to the `IntIdTable` class.
When creating SQL tables, I personally like to be specific about id column names to remove any ambiguity when reading data. `IntIdTable` provides the `id` column but forces the column name as `id`. To get around this I have to directly extend `IdTable` and redefine the same id column in `IntIdTable` just to name the column.
This PR solves that problem by simply adding a `columnName` String parameter to the `IntIdTable` class. `columnName` is optional and defaults to `"id"`, the current value to provide backwards compatibility.
=> Allow IntIdTable's id column to be renamed.

src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, src/main/kotlin/org/jetbrains/exposed/sql/Table.kt
This PR fix a wrong SQL syntax to create DECIMAL data type
When creating a decimal column type => precision and scale are wrong. In current implementation if you want to create a column of type DECIMAL(16,5) so you will do it by using the Exposed
```kotlin
val price = decimal("PRICE", 5, 16) // exposed  decimal(name, scale, precision)
```
but this will create a column PRICE(5,16) so insert of value 123456,5 fail.
I changed order of arguments in the DecimalColumnType and also in the Table.kt.
All tests are passed
=> DecimalColumnType - wrong handling with precision and scale

src/main/kotlin/org/jetbrains/exposed/sql/Function.kt
As per http://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html#function_sum "SUM() returns NULL if there were no matching rows."
=> Sum can now return null. This change was missed in the fixes for #41.

src/main/kotlin/org/jetbrains/exposed/sql/transactions/ThreadLocalTransactionManager.kt, src/main/kotlin/org/jetbrains/exposed/sql/transactions/TransactionApi.kt
- Something is wrong with the way the DAO interacts with H2 Clobs (I'm looking into this a bit but it seemed easier to use SQLite as a reference DB instead.  On H2 the connection is closed before the data has been read/cached).
- SQLite doesn't support `Connection.TRANSACTION_REPEATABLE_READ`.
- The `transaction {}` syntax is so sexy I can't let it go.
- You can now set the default transaction level used with `transaction {}` via the `TransactionManager` companion object:
`TransactionManager.defaultIsolationLevel = Connection.TRANSACTION_SERIALIZABLE`
=> Allowed user to set default isolation level

src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt
currenlty SERIAL is used which will yield a INT (= integer) and not a BIGINT (=long) as desired
=> map autoincremented LONG type correctly to PostgreSQL type "BIGSERIAL"

src/main/kotlin/org/jetbrains/exposed/sql/SQLLog.kt, src/main/kotlin/org/jetbrains/exposed/sql/Transaction.kt, src/test/kotlin/demo/SamplesDao.kt, src/test/kotlin/demo/SamplesSQL.kt
I had OutOfMemory issues when performing benchmarks using Exposed, due to expensive logging operations, even when logger is disabled.
=> Avoid expensive String expansion when logger is disabled

src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt
Some very early dates (at least 1970-01-02) get stored in SQLite as integers, therefore the `when` in `DateColumnType.valueFromDB` fails since it does not count Ints.
Ints need to be cast to a Long in order to play well with the DateTime constructor.
=> Also accept Ints when parsing a DATE from SQL

src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt
I wanted a way to specify a multi-column unique index in a Table that was more readable than
```
init {
index(true, columnA, columnB)
}
```
so I added a wrapper method for uniqueIndex that takes multiple columns
```
init {
uniqueIndex(columnA, columnB)
}
```
Also added a test that checks the SQL generated for multi-column indices. I only ran this test on h2 though.
=> Wrapper method for multi-column unique indices and multi-column index test

src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt
This happened when updating a date column with postgresql driver. The `value`-argument was already a `DateTime` and you were trying to convert it to `DateTime` via `String` but with different formats, leading to an exception. My pull request fixes this.
=> fix bug where DateTime should be converted to DateTime

src/main/kotlin/org/jetbrains/exposed/sql/Query.kt, src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DMLTests.kt
I removed the groupBy-aliasing within the count() function of `Query` because you cannot use aliases in a group-by clause in Oracle (and as far as i know also MSSQL) and it also doesn't make any sense to me. Is there any real use-case someone would need this?
I also fixed the duplicate aliasing (which also causes a `SqlException`)  when the column is already an `ExpressionAlias`. Now if the expression is an `ExpressionAlias` it won't automatiically create an alias for it anymore.
=> remove groupBy-aliasing in count query 

src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt
I run into this using passing an unsupported type, I think it may help and does not break anything. Why the exception message was not clear to me:
Unexpected value: 2018-01-10
java.lang.IllegalStateException: Unexpected value: 2018-01-10
at org.jetbrains.exposed.sql.DateColumnType.nonNullValueToString(ColumnType.kt:201)
=> Explain why the supplied value is not expected

src/main/kotlin/org/jetbrains/exposed/dao/Entity.kt
Hi, This is very trivial improvement.
I improve message of exception thrown when Entity id not found on calling entity.
Exception message changes as described below.
Before:
```
java.lang.IllegalStateException: Entity not found in database
at org.jetbrains.exposed.dao.EntityClass.get(Entity.kt:462)
at org.jetbrains.exposed.sql.tests.shared.EntityTests$testDefaults01$1.invoke(EntityTests.kt:116)
at 
.........
```
After:
```
java.lang.IllegalStateException: Entity id 999999999 not found in database
at org.jetbrains.exposed.dao.EntityClass.get(Entity.kt:462)
at org.jetbrains.exposed.sql.tests.shared.EntityTests$testDefaults01$1.invoke(EntityTests.kt:116)
at
.........
```
I think id information in log message is useful, specifically in this case (entity id not found case).
=> Improve log message (Contain id information).

src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLiteDialect.kt, src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DMLTests.kt
Added support for 'insertIgnore' and 'deleteIgnore' in SQLite based on the [official documentation](https://sqlite.org/lang_conflict.html)
=> Add support for 'insertIgnore' and 'deleteIgnore' in SQLite

spring-transaction/src/test/kotlin/org.jetbrains.exposed.spring/ExposedTransactionManagerTest.kt
`testConnectionWithoutAnnotation()` will succeed without `transaction {}`.
`testConnection2()` will succeed without `@transactional`.
=> Fix spring-transaction test

src/main/kotlin/org/jetbrains/exposed/sql/Column.kt, src/main/kotlin/org/jetbrains/exposed/sql/Constraints.kt, src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt
This is a first implementation of the support for check constraints, based on the Issue #268 
A test has been created to test this new functionality: `DDLTests.testCheckConstraint()`. It has been tested to work with PostgreSQL, SQLite and H2.
=> Add support for check constraints.

src/main/kotlin/org/jetbrains/exposed/sql/vendors/H2.kt, src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt
Resolves #290
This PR attempts to add support for ignore and replace
From what I've looked up, ignore involves simply adding `ON CONFLICT DO NOTHING`.
Replace is a bit different for postgres, as it goes through ignore and calls update on conflicts. It also needs to specify which keys to look out for conflicts, which is why I've made it default to the unique keys (snippet taken from the H2 code).
This was tested against [this code](https://github.com/AllanWang/McGill-Data/blob/91e47b96eca3f9f6734aac4e66b13976cd6fb3c7/database/src/test/kotlin/ca/allanwang/mcgill/db/DbTest.kt)
The dependency is passed through jitpack, so it's easy to tweak something and update the import
------------------
On top of this, I have one question:
The replace method for PG looks similar to ignore from H2. Isn't …
=> Postgres ignore + replace

src/main/kotlin/org/jetbrains/exposed/sql/Database.kt, src/main/kotlin/org/jetbrains/exposed/sql/Query.kt
At lest in PostgreSQL, the result set from a select() does not appear to be fetched lazily, and PostgreSQL seems to be caching the entire ResultSet.
```kotlin
MyTable.select { ... }.forEach { ... }
```
After this change,
```kotlin
MyTable.select { ... }.fetchSize(1000).forEach { ... }
```
In this test case case, it reduces memory usage by approximately 1.3gb.
=> Allow overriding the fetch size for a Query

src/main/kotlin/org/jetbrains/exposed/sql/Query.kt
The comment here threw me off. The function won't return null unless the expression type is nullable, in which case I would obviously expect to possibly deal with null. So the bit about `tryGet` seems to focus on the wrong thing.
Correct me if I'm wrong, but it seems like the only distinction between `get` and `tryGet` is that `get` throws an `IllegalStateException` if the result is uninitialized or the expression isn't in the record set, but `tryGet` just returns null in those cases. So choosing one of the two doesn't depend on your nullability expectation, rather it depends on what you want in those exceptional situations. In other words, use `tryGet` if you don't care to catch exceptions.
(I also changed some whitespace to match the rest of the file)
=> Clarify Query.get documentation

spring-transaction/src/main/kotlin/org/jetbrains/exposed/spring/SpringTransactionManager.kt, src/main/kotlin/org/jetbrains/exposed/sql/Database.kt, src/main/kotlin/org/jetbrains/exposed/sql/transactions/ThreadLocalTransactionManager.kt, src/main/kotlin/org/jetbrains/exposed/sql/transactions/TransactionApi.kt
The default repetitionAttempts value is 3 in transaction!
We need to set (change) it every time we use a transaction, and It's better to config that in expose settings globally... in Database.connect(..., manager = {...})
So, I wrote some code to do that.
Thanks
=> Set RepetitionAttempts in TransactionManager (to set globally)

src/main/kotlin/org/jetbrains/exposed/sql/Function.kt, src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLServerDialect.kt, src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLiteDialect.kt, src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DMLTests.kt
Adds ability to apply `groupConcat` on `Expression` instead of just `Column`. Also adds restriction so that it could only be applied on only `String` types in order to avoid run-time errors when executing queries.
Resolves #485.
=> Allow to apply groupConcat on expressions

src/main/kotlin/org/jetbrains/exposed/dao/Entity.kt, src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/EntityTests.kt
To address the n+1 problem in the DAO library I've added two extension functions which provide support for eagerly loading relations. The current syntax is : 
```kotlin
List<Entity>.with(Entity::relation1, Entity::relation2, SubEntity::relation) 
```
and
```kotlin
Entity.load(Entity::relation1, Entity::relation2, SubEntity::relation)
```
The extension functions will then aggregate relations, run WHERE IN commands and then save the results inside the transaction cache.
Currently the commit lacks support for BackReferences and OptBackReferences, with a view to add those shortly alongside some form of testing for the two functions. Would be great to get some feedback, it took a fair amount of poking around the repo to come up with the current approach.
=> Eager Loading support

exposed/src/main/kotlin/org/jetbrains/exposed/sql/Queries.kt, exposed/src/main/kotlin/org/jetbrains/exposed/sql/statements/InsertStatement.kt, exposed/src/test/kotlin/org/jetbrains/exposed/sql/tests/demo/sql/SamplesSQL.kt, exposed/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt, exposed/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DMLTests.kt
Related discussion on Slack:
Johannes Jensen   [Mar 14th at 10:51 AM]
Another thread: What is the use case for having `InsertStatement.get` return `T?` ? The only use in the project that ought to use this functionality at all is `fun <Key:Comparable<Key>, T: IdTable<Key>> T.insertIgnoreAndGetId`.
It seems to me that it ought to be changed to `T` and instead define a `InsertStatement.tryGet` for the much rarer use so can avoid having !! just to retrieve a generated key.
2 replies
Andrey Tarashevskiy   [2 hours ago]
Nullable columns could produce `null` on insert and that's not the 'null == value was absent from insert'
Johannes Jensen   [< 1 minute ago]
But since `T` isnt contrained to `Any` it would just be ie. `Int?` which would work. Or I am not understanding you correctly. I have …
=> Split InsertStatement.get into get, tryGet to simplify get use.

exposed/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Mysql.kt
This is an additional fix for #394 Foreign Key Constraints being recreated
=> Fix MySQL constraints when table names are in lower case

exposed/src/main/kotlin/org/jetbrains/exposed/sql/Constraints.kt, exposed/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Mysql.kt
Exposed uses `ALTER TABLE` statements to create constraints in case when there are cycles in table structure. In this case it explicitly sets constraint name to `fk_${fromCol.table.tableName}_${fromCol.name}_${targetColumn.name}`. However, if there are no cycles, constraints are defined in `CREATE TABLE` statements without name specification: thus, their names are generated by database engine that uses different naming convention (ie `Table_ibfk_1` in innodb).
This patch makes Exposed to explicitly specify constraint names in `CREATE TABLE` statements.
It also sets `identifierLengthLimit` for MySQL to 64 (as specified [here](https://dev.mysql.com/doc/refman/8.0/en/identifiers.html)) to fix test that fails otherwise.
=> Explicitly specify constraint name in create table statement

exposed/src/main/kotlin/org/jetbrains/exposed/sql/Function.kt, exposed/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DMLTests.kt
I ran into a use case, where I wanted to call some SQL functions exposed by PostGIS. 
But looking at the code I wondered why there is no support for generic functions, so I added that instead.
Existing functions like upper, lower etc could be redefined as function("UPPER") if you want to reduce the amount of code for some added complexity.
I think it is best if functions are defined in a type safe matter, but it is also nice for users to have a "rabbit hole" to be able to just call any function in the database.
=> Add generic custom sql function support

exposed/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt
AFAIK it doesn't make sense to pass a non-positive value to the `LIMIT` clause, so this PR prevents it from ever happening. Unfortunately I wasn't able to figure out how to write a test for this change : (
=> Build LIMIT only if size is strictly positive

exposed/src/main/kotlin/org/jetbrains/exposed/sql/Database.kt, exposed/src/main/kotlin/org/jetbrains/exposed/sql/transactions/ThreadLocalTransactionManager.kt, exposed/src/main/kotlin/org/jetbrains/exposed/sql/transactions/TransactionApi.kt, exposed/src/main/kotlin/org/jetbrains/exposed/sql/transactions/experimental/Suspended.kt, exposed/src/test/kotlin/org/jetbrains/exposed/sql/tests/h2/MultiDatabaseEntityTest.kt, exposed/src/test/kotlin/org/jetbrains/exposed/sql/tests/h2/MultiDatabaseTest.kt, exposed/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/EntityTests.kt, exposed/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/NestedTransactionsTest.kt, exposed/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ThreadLocalManagerTest.kt, spring-transaction/src/main/kotlin/org/jetbrains/exposed/spring/SpringTransactionManager.kt
Hi, I've implemented nested transaction support using JDBC savepoints.
now you can use pattern  
```kotlin
transaction { 
transaction {
transaction {
}
rollback()
}
}
```
Also made a little bit refactoring towards removing singletons.
=> Implemented nested transactions support

exposed/src/main/kotlin/org/jetbrains/exposed/sql/Op.kt, exposed/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DMLTests.kt
It is an API that can build the following SQL with DSL.
``` sql
SELECT COUNT(*)
FROM customer
WHERE customer.customer_id IN (
SELECT customer_id FROM payment WHERE amount > 100
)
```
``` kotlin
Customer.select { Customer.customerId inSubQuery Payment.slice(Payment.customerId).select { Payment.amount greater 100 } }
```
=> where in subquery

exposed/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt
I think a `Column<EntityID<T>>.notInList` method is also convenient as `Column<EntityID<T>>.inList` method is.
And it makes symmetry between `inList` and `notInList` method.
If this PR does not follow the project's direction, feel free to close this.
=> Make `notInList` function symmetrical with `inList` function

exposed/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Mysql.kt
CURRENT_TIMESTAMP does not work correctly in Mysql. This patch corrects the issue.
=> Handle CURRENT_TIMESTAMP in Mysql coorectly.

exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityClass.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ImmutableEntityTest.kt
Evict entities value from the current transaction cache on force update of immutable entities,
so that the next read of this entity using DAO API would return actual data from the DB
=> Fix bug with immutable entities and transaction cache

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt
New method Column<UUID>.autoGenerate() allows to automatically generate random UUID value to columns where explicit passing of a value is not mandatory (for id's for example)
Example of usage:
```
object TestTable : Table("test_table") {
val id = uuid("id").autoGenerate().primaryKey()
val val1 = text("val1")
}
```
=> Added uuid value autogeneration

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt
Hi,
In our project we use [own `ColumnType` implementation](https://github.com/TouK/kotlin-exposed-realworld/blob/d3f9f90fe0f4cbec4fc6b2ec0207a99b218a9dc9/src/main/kotlin/io/realworld/shared/infrastructure/WrapperColumn.kt#L43) to wrap [id columns types](https://github.com/TouK/kotlin-exposed-realworld/blob/d3f9f90fe0f4cbec4fc6b2ec0207a99b218a9dc9/src/main/kotlin/io/realworld/comment/infrastructure/SqlCommentRepositories.kt#L25). When we use `SchemaUtils` to create schema, `resolveAutIncType` function raises exception because our `ColumnType` is not `LongColumnType` or `IntegerColumnType`, so we reworked this method to find auto increment type basing on `sqlType`.
=> Support auto increment for own ColumnType implementation

exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/JavaDateFunctions.kt, exposed-jodatime/src/main/kotlin/org/jetbrains/exposed/sql/DateFunctions.kt
To select only the month on a datetime column we use Table.datetime-column.month(). 
This causes an error when using, for example, PostgreSQL database.
That's is because syntax of the month function is not the same for all database dialects. 
For example:
- For H2 database it will work because the syntax of month function is MONTH(<datetime-column>).
- For PostgreSQL it will cause an error because the syntax is EXTRACT(MONTH FROM <datetime-column>).
=> Fixing the month built-in function in case of all database dialects

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Queries.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DMLTests.kt
Follow up on https://github.com/JetBrains/Exposed/issues/641.
This functionality is inspired by Rails' [find_in_batches](https://apidock.com/rails/v5.2.3/ActiveRecord/Batches/find_in_batches) and is an alternative to using 'fetchSize' that does not rely on server-side cursors. It's also a much more efficient approach than using [limit+offset](https://www.eversql.com/faster-pagination-in-mysql-why-order-by-with-limit-and-offset-is-slow/).
The requirement for this to work is that the source table has an auto-increment column.
@Tapac I used a different naming style for the tests as I felt I needed more words, but if you prefer I can try to use the same format as the other tests.
=> Add batch select

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/UpdateBuilder.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/MiscTableTest.kt
We would like to have access to niceties from SqlExpressionBuilder here like `plus(t: T)`
```
update(c) { c + 1 }
```
=> Added UpdateBuilder.update expression builder version.

exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/References.kt
When I use [`with` clause of eager-loading feature](https://github.com/JetBrains/Exposed/wiki/DAO#eager-loading), a SQL selecting referenced tables with `IN` query is executed. But ids in `IN` query are not distinct, so make them distinct by this PR.
For example, in below code,
```kotlin
val region1 = Region.new {
name = "United States"
}
School.new {
name = "Eton"
region = region1
}
School.new {
name = "Harrow"
region = region1
}
commit()
School.all().with(School::region)
```
Below SQL is executed.
```sql
SQL: SELECT SCHOOL.ID, SCHOOL."NAME", SCHOOL.REGION_ID, SCHOOL.SECONDARY_REGION_ID FROM SCHOOL
SQL: SELECT REGION.ID, REGION."NAME" FROM REGION WHERE REGION.ID IN (1, 1)
```
But, duplicated ids exist (`IN (1, 1)`), so make them distinct by this PR fix.
After applying this PR fix, you …
=> Make ids on IN SQL condition distinct on eager loading

exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/demo/dao/SamplesDao.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/demo/sql/SamplesSQL.kt
Test samples also so they cannot drift into a bad state as they are currently.
Fails currently I assume due to #698 so wait until that is fixed.
=> Run samples as a part of test run.

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLiteDialect.kt, exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/java-time/JavaDateFunctions.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/JavaTimeTests.kt, exposed-jodatime/src/main/kotlin/org/jetbrains/exposed/sql/jodatime/DateFunctions.kt, exposed-jodatime/src/test/kotlin/org/jetbrains/exposed/JodaTimeTests.kt, exposed-tests/build.gradle.kts
This PR is similar to a previous PR that i did to add sql datetime functions.
But in his PR, i'm using the currentDialect.functionProvider to access the function. So that the convenient function is selected during runtime(via polymorphism) rather than using when statement.
=> better design and performance.
@Tapac are you agree? so that i close the previous PR
=> [Improved solution] Adding sql datetime functions year, day, hour, minute, second

exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/java-time/JavaDateColumnType.kt, exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/java-time/JavaDateFunctions.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/DefaultsTest.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/JavaTimeTests.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/MiscTableTest.kt
We use Instant in our Koltin code-base and it seems awkward to convert it
to LocalDateTime when java.sql.Timestamp supports Instant directly
=> Support for java.time.Instant for timestamp columns

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Exceptions.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateTableTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/ReplaceColumnTests.kt
This PR is to resolve the bug #709 .
In Fact, there are two scenarios where Exposed allow to create a table with multiple columns that have the same name (which fails later when executing the query in the database) : 
- First exemple : 
```Kotlin
object TableWithDuplicatedColumn : Table("myTable") {
val id1 = integer("id")
val id2 = integer("id")
}
```
- Second exemple : 
```Kotlin
object IDTable : IntIdTable("myTable") 
object TableDuplicatedColumnRefereToIntIdTable : IntIdTable("myTable") {
val reference = reference("id", IDTable)
}
```
So this PR is to introduce a new Exception that is thrown when user attempt to produce a table with duplicate column name (when creating the table or when replacing column of an existing table)
=> [BugFix] Prevent defining duplicated colum name in a table

ROADMAP.md
Oracle announced that they have stopped work on ADBA. https://mail.openjdk.java.net/pipermail/jdbc-spec-discuss/2019-September/000529.html
=> ADBA project terminated

exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/java-time/JavaDateColumnType.kt
Reason for change
===========================
Currently the `JavaLocalDateTimeColumnType` using a sqlite backend expects datetime strings to be in the following format: `yyyy-MM-d HH:mm:ss`. 
However, according to the manual[1] SQLite allows the following string formats for datetimes: 
* YYYY-MM-DD
* YYYY-MM-DD HH:MM
* YYYY-MM-DD HH:MM:SS
* **YYYY-MM-DD HH:MM:SS.SSS  <--- This format is currently broken**
Thus, some of the datetime strings written by other clients can't be parsed by exposed. I observed this limitation when reading datetimes written by python + SQLAlchemy. 
I implemented a fix by removing special treatment (only) for SQLite Datetimes. Now the normal datetime parsing machinery is used which auto-detects if there is a fraction part and of how many digits the fraction part …
=> Removed unnecessary special treatment for SQLite

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Column.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt
This PR is related to the issue #470 .
- This PR is to allow the user to define his proper primarykey constraint name. Here is an example :
```Kotlin
object table : Table("table") {
val id1 = integer("id1")
val id2 = integer("id2")
override val primaryKey = PrimaryKey(listOf(id1, id2), "CustomPk")
}
```
=> generated SQL:
`CREATE TABLE table (id1 INT,id2 INT, CONSTRAINT CustomPK PRIMARY KEY (id1,id2))`
- When the PK constraint name is defined and the primary key contains only one single column, then the constraint name must be defined in the generated SQL query.
@Tapac if the design and the code are ok i'm thinking also to add the functions : 
- table.primaryKey.rename("newPkname") => rename the constraint.
- table.primaryKey.drop() => drop the constraint.
=> Adding the feature of defining the primarykey constraint name

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Column.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateTableTests.kt
Creating a table that has an autoIncrement column and a custom primarykey (that contains single column) causes an error in SQLite dialect. Here is an example :
```Kotlin
object Test : Table("Test") {
val id = integer("id").autoIncrement()
// Rest of columns
override val primaryKey = PrimaryKey(id, name = "PKConstraintName")
}
```
SQL generated : 
```SQL
CREATE TABLE IF NOT EXISTS Test(id INTEGER PRIMARY KEY AUTOINCREMENT, CONSTRAINT PKConstraintName PRIMARY KEY (id))
```
Error :  `SQL error or missing database (table "Test" has more than one primary key)`
.
=> **So in this PR I did a little change to consider this case.**
=> [SQLite] fixing a bug in creating table with autoInc column and custom primarykey

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcDatabaseMetadataImpl.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ConnectionTests.kt
fixes #495
I referenced this java doc.
https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html#getColumns-java.lang.String-java.lang.String-java.lang.String-java.lang.String-
=> Add size property on ColumnMetadata class

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SchemaUtils.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/H2.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLServerDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLiteDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateDatabaseTest.kt
This PR is to add requested feature #757 .
Create database and drop database methods are implemented differently in each dialect :
- H2 : `CREATE/DROP SCHEMA IF NOT EXISTS dbname`
- SQLite : `ATTACH/DETACH  DATABASE dbname.db' AS dbname`
- Others : `CREATE/DROP DATABASE [IF NOT EXISTS] dbname`
=> Adding create and drop database methods

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt
Related to issue #777. This is to change the regular expression that ckecks the uuid as it is described [here](https://docs.microsoft.com/en-us/sql/t-sql/data-types/uniqueidentifier-transact-sql?view=sql-server-ver15)
=> changing the uuid check regexp

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Op.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/SelectTests.kt
We have `inSubQuery` feature but there is no its counterpart `notInSubQuery`. Now we can have it. 
Covered with tests.
=> notInSubQuery functionality

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Op.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/ArithmeticTests.kt
See issue #787 
Exposed did not follow the correct operator precedence rules for arithmetic operators.
=> Correct precedence for arithmetic operators

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Expression.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Function.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Op.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/MariaDBDialect.kt
- Added KDoc comments to most public declarations.
- Rearranged some declarations to group them by functionality.
- Reformatted code to follow Kotlin Coding Conventions.
- Created backing property for `args` property in `QueryBuilder` class.
- Refactored `args` property to use `mutableListOf()` instead of `ArrayList()` in `QueryBuilder` class.
- Refactored `toQueryBuilder` function in `CustomFunction` class, now uses `asList` instead of `toList`to avoid copying the original array.
- Refactored `cases` property in `CaseWhen` class to use `mutableListOf()` instead of `ArrayList()`.
- Refactored `and` and `or` functions from `Op.kt` to be more idiomatic.
- Updated function return types to match the class returned instead of a superclass.
- Added `infix` modifier to mathematical operators in …
=> [KDoc & Format] SQL Expressions, Operators and Functions

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt
Hi!
I am extending the some Dao functions and I need to create my custom expression builder, but I can't extend it because is a object and final.
=> SqlExpressionBuilder should be an open class

exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcDatabaseMetadataImpl.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ConnectionTests.kt
=> ExposedDatabaseMetadata#tableConstraints: fix it works correctly when column names need quoting

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt
In Column the equals is:
```
override fun equals(other: Any?): Boolean {
if (this === other) return true
if (other !is Column<*>) return false
if (!super.equals(other)) return false
if (table != other.table) return false
if (name != other.name) return false
if (columnType != other.columnType) return false
return true
`}`
```
It compares column type, but column types are only compared by reference because they don't implement equals and always return false inclusive when they are the same.
=> Implement equals in ColumnTypes.

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/H2.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/h2/H2Tests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/CoroutineTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateMissingTablesAndColumnsTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/InsertTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/JoinTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/ReplaceTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/ImmutableEntityTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/SelfReferenceTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/ViaTest.kt
This PR is to improve the primary key declaration.
- When using both deprecated and new declaration for primarykey, the new one is taken and the deprecated is silently ignored. (without logging the "confusion between mutiple declaration" error)
- When using the deprecated method, an error is logged telling to use the new declaration instead.
- Use of the new declaration in all tests.
- Some duplicated tests was removed.
=> primary key declaration fixes

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/Statement.kt
escape parameter placeholder '?' by double question mark '??'
PostgreSQL documentation - https://jdbc.postgresql.org/documentation/head/statement.html
* In JDBC, the question mark (?) is the placeholder for the positional parameters of a PreparedStatement. There are, however, a number of PostgreSQL operators that contain a question mark. To keep such question marks in a SQL statement from being interpreted as positional parameters, use two question marks (??) as escape sequence. You can also use this escape sequence in a Statement, but that is not required. Specifically only in a Statement a single (?) can be used as an operator.
should resolve https://github.com/JetBrains/Exposed/issues/890
=> FEAT / FIX: support parameter placeholder escaping

docs/README.md
There were a few minor styling issues in the first paragraph of the documentation. I rephrased a couple of sentences and joined the two first paragraphs so that the documentation gets shorter and cleaner for a reader.
Let me know what you think. You can check the updated README [in my fork](https://github.com/Shpota/Exposed/tree/update-documentation) of the repository.
It would also be great if a native speaker read the documentation.
=> Correct styling issues in the documentation

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Schema.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SchemaUtils.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/api/ExposedDatabaseMetadata.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Mysql.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLServerDialect.kt, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcDatabaseMetadataImpl.kt, exposed-tests/src/main/kotlin/org/jetbrains/exposed/sql/tests/DatabaseTestsBase.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/SchemaTests.kt
- **`Schema.exists()` method** : All existing schema names are stored in a cache variable. This cache is used by `Schema.exists()` method to check if the schema exists or not.
- **create/drop schema safely** : When attemps to create (or drop) schemas, the exists() method is used to determine which schemas to create/drop. => This way, if we create an existing schema and the dialect doesn't support "if not exists", Exposed will not create it. (same thing for drop schema).
- **Changing the oracle implementation** : a schema == user,  so to create schema you should use `create user` statement and there are many options added that you can specify.
- **`cascade` option in dropSchema(schema, cascade = false)** : used to drop schema and all of its objects and all objects that depend on those …
=> improvement of create/drop schema and adding some options

exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcDatabaseMetadataImpl.kt
I'm not sure if this is intentional or not, this fixes the issue I was having in https://github.com/JetBrains/Exposed/issues/849#issuecomment-625520283
Run this code
```kotlin
fun main() {
println("hello")
val db = Database.connect("jdbc:postgresql://localhost:5432/test", driver = "org.postgresql.Driver", user = "postgres", password = "postgres")
transaction(db) {
SchemaUtils.createMissingTablesAndColumns(
OriginalTable,
ExternalReference
)
}
println("done")
}
object OriginalTable : LongIdTable() {
val extReference = optReference("external", ExternalReference)
}
object ExternalReference : LongIdTable() {
val integer = integer("integer")
}
```
Now, try commenting out the `extReference` from the `OriginalTable` object
```kotlin
object OriginalTable : LongIdTable() {
val extReference = …
```
=> Ignore missing fields in Exposed's table instead of crashing when using createMissingTablesAndColumns

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Function.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Op.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Mysql.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt
Adds support for UNSIGNED column type. https://github.com/JetBrains/Exposed/issues/199
As far as I investigated, UNSIGNED syntax seems to be supported only on Oracle and MySQL.
https://dev.mysql.com/doc/refman/8.0/en/numeric-type-syntax.html
https://docs.oracle.com/cd/B28359_01/gateways.111/b31048/apa.htm#g635398
At the first step, I implemented it only for BIGINT type.
If this PR's direction is correct I proceed to implement for INT, SMALLINT, TINYINT, otherwise I plan to close this PR.
=> [WIP] UNSIGNED column support

docs/README.md
Currenty, `README.md` uses hardcoded image link to repository where it originates from. There are two issues:
1. It probably should refer to _this_ repository,
2. It probably should not depend on any network resource at all, since the image is co-located with the README.
So, I've changed it to a relative link.
Even though GitHub shows README on main page, it works fine. Intellij IDEA preview works too.
=> docs/README.md: fix hardcoded logo link

exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/Entity.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityClass.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityTests.kt
Created entity using new(id: ID?, ...) method has id._value.
Then `id._value == null` can't check for entity creation.
These entities are in transaction entity cache's inserts.
And I fixed #925 using it.
=> Modify checking for entity creation #925

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Function.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLiteDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/FunctionsTests.kt
I saw that it was explicitly done to use only String expressions in this [PR](https://github.com/JetBrains/Exposed/commit/b1c07da8abb60689ad11509713040d2e261f3745)
But `CONCAT` works with different types of expressions and it is not obligatory to use only `Expression<String>`.
=> Support various expressions in concat function

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/H2.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/h2/H2Tests.kt
Re-implement `Queries.replace()` for H2SQL using the native `MERGE INTO` syntax described [in the h2sql docs](http://www.h2database.com/html/commands.html#merge_into)
When no data is present, this returns an empty query (tested with `H2Tests.emptyReplace()`.
Since the syntax is identical to `INSERT INTO`, I have used `super.insert()` to generate a plain insert statement and then replaced the keyword `INSERT` with `MERGE`.  I am not using `H2FunctionProvider.insert` because it also attempts to provide partial replace functionality and could produce an invalid `MERGE INTO` statement.
I have added `SchemaUtils.drop(Testing) to the existing tests because it guarantees an empty state between tests.  Without this, new replace tests were failing due to existing data.
I have added explicit tests …
=> Implement native H2SQL replace

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Constraints.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/H2.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/MariaDBDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLiteDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateIndexTests.kt
May address https://github.com/JetBrains/Exposed/issues/895
=> Allow setting index_type (e.g., 'HASH' or 'BTREE')

exposed-java-time/build.gradle.kts, exposed-jodatime/build.gradle.kts, exposed-money/build.gradle.kts, exposed-tests/build.gradle.kts, exposed-tests/src/main/kotlin/org/jetbrains/exposed/sql/tests/DatabaseTestsBase.kt
The mxj library is flaky and doesn't work on various platforms due to being outdated.
This PR is related to #894 and #947.
=> Use testcontainers for MySQL instead of mysql-connector-mxj

exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/java-time/JavaDateColumnType.kt
The current fix for #991 missed the usage of `Timestamp.from()`. This change should fix that.
=> Quick fix addition for #991

exposed-core/build.gradle.kts, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLiteDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/DeleteTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/UpdateTests.kt
LIMIT in UPDATE and DELETE clause are supported in SQLite.
[optional_limit_and_order_by_clauses in delete clause](https://sqlite.org/lang_delete.html#optional_limit_and_order_by_clauses)
[optional_limit_and_order_by_clauses in update clause](https://sqlite.org/lang_update.html#optional_limit_and_order_by_clauses)
=> remove "SQLite doesn't support LIMIT in UPDATE/DELETE clause." exception

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Queries.kt
Resolves #847 
> Technically speaking. If you are able to provide meaningful insert statement for null value, handling the null case should be allowed. In same manner as here is no not-null constraint for plain insert.
If there are other similar types that could be relaxed, let me know and I can add those as well.
=> Relax type of batch insert body parameter to allow nullable values

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Database.kt
Read Committed is the default isolation level in PostgreSQL
https://www.postgresql.org/docs/11/transaction-iso.html
=> support default isolation level for postgresql

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/InsertStatement.kt
The comment is really confusing. In reality, the flag is supported for more than just MySQL. I tested the flag on Postgres and had the following query generated by the library:
`INSERT INTO test_insert_ignore (some_value) VALUES ($1) ON CONFLICT DO NOTHING RETURNING *`
The code behind it is: 
```
override fun insert(
ignore: Boolean,
table: Table,
columns: List<Column<*>>,
expr: String,
transaction: Transaction
): String {
val def = super.insert(false, table, columns, expr, transaction)
return if (ignore) "$def $onConflictIgnore" else def
}
```
According to my reasoning, the flag is also supported for H2 and SQLite.  Fix me if I'm wrong.
=> Remove confusing comment

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Transaction.kt
The previous code required a `ColumnType` when only a `IColumnType` was required.  This imposed additional requirements on authors when writing manual statements.  Relaxing the requirement to `IColumnType` makes it both easier to write manual statements and allows reuse of many of Exposed's existing parts, such as `QueryBuilder` which provides args as a list of `IColumnType`.
=> Relax typing for Transaction#exec

exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityCache.kt
This change will prevent inserts and deletes on a single table from evicting all cache entries on any referring entity.
=> Narrow scope of referring cache evictions

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt
Exposed allows: 
````Kotlin 
Users.slice().selectAll()
```` 
which outputs `SELECT  FROM USERS`
and then : Syntax error from databse
This PR is to try to prevent at compile time calling slice() without parameters by showing this error:
=> specify at least one column in Table.slice()

exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcDatabaseMetadataImpl.kt
The `org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl#existingIndices` method returns indices in which the same column may be contained several times.
As a result, not all indices are created correctly in `org.jetbrains.exposed.sql.QueriesKt#checkMissingIndices` because `org.jetbrains.exposed.sql.Index#onlyNameDiffer` checks the columns and extracts them from the table definition (` org.jetbrains.exposed .sql.Table`) only read unique columns per index.
=> Removal of duplicate columns for existing indices read from the database

exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityLifecycleInterceptor.kt
The set of source columns may be empty in some cases, such as `SELECT COUNT(*) ...`.  Instead we should flush any table that the query might touch.
=> Fix entity cache flushing when executing query

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/WhereConditionsTests.kt
Actually `like` and `notLike` methods accepts string arguments but not expressions.
In this PR we can do this:
````KOTLIN
val str = "Hich%"
User.select {
User.name like stringLiteral(str).upperCase()
}
````
works also with string expressions like `Column<String>`
=> like and notLike mothods works with string expression

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Mysql.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLServerDialect.kt
This commit introduces special sql types, instead of generic 'TEXT' column type, for MySQL and SQLServer dialects.
'longtext' is used for MySQL
'VARCHAR(MAX)' is used for SQLServer
Without this change Exposed fails to create text columns on MySQL and SQLServer due to missing column length.
=> Specific text column types for MySQL and SQLServer.

exposed-spring-boot-starter/README.md
This fixes a typo, version 0.21.2 does not exists
=> Update readme.md for release 0.29.1

exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityCache.kt
There are two reasons to do this:
1. The `EntityCache` is already within a `transactionScope`.
2. Even if 1) was not true, the purpose of the variable is to prevent the same cache from recursively flushing.  If there were multiple caches within the same transaction it would be fine if both flushed at the same time.
Extracted backwards-compatible change from #1133.
=> Replace transaction scope w/ local variable

exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/References.kt, exposed-tests/.gitignore
This change allows consumers to eager load any `Iterable`, as opposed to exclusively `List` or `SizedIterable`.  The eager loading code operates on a `List`, and `SizedIterable` is converted to a `List` before eager loading.  This process can be used for any `Iterable`.
=> Allow eager loading of any iterable

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLServerDialect.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/DefaultsTest.kt
Hi,
We use temporal tables to audit all the data changes.
When you do an insert, there are two special datetime2 columns (in a temporal table) declared as `GENERATED ALWAYS AS ROW START/END`. These columns are mandatory.
For some actions, like batch inserting, all columns need an explicit value. The columns mentioned above are automatically filled, and you cannot insert an explicit value into a `GENERATED ALWAYS` column.
You have a couple of options when inserting a new row in a temporal table like omitting the two columns or specify the DEFAULT keyword in the values list for both columns.
I've created a test that shows what we are trying to do and the suggested fix.
Other suggestions are welcome!
=> allow the SQL Server default keyword as default value for a column

exposed-bom/README.md
Both Maven and Gradle configuration parameters were incorrect.
According to https://repo1.maven.org/maven2/org/jetbrains/exposed/exposed-bom/maven-metadata.xml the first available version of exposed-bom is 0.32.1
=> Fix README.md of exposed-bom

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt
Using "org.postgresql:postgresql:42.2.16" converts `FLOAT` to `float8`, which uses double precision. It should be single precision, which is `real` using 4 bytes.
Reference: https://www.postgresql.org/docs/current/datatype-numeric.html
=> Use Postgres single precision data type

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Op.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/DMLTestData.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/InsertSelectTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/functions/FunctionsTests.kt
Inspired by `ModOp` and `AndOp`/`OrOp`, introduces support for bitwise operations in the query (`and` and `or`).
Additionally, there's a helper function `hasFlag` that checks if a bitflag is set on an expression by evaluating to `(expr & flag) = flag` or an equivalent in the current dialect.
=> Introduce operators for bitwise expressions and bitflag checks

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Queries.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/SelectBatchedTests.kt
Currently, `Sequence.asIterable` does not work, as `data.count == 0` is called, which terminates the sequence before inserting all values.
=> Add batchInsert with Sequence

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/UpdateBuilder.kt
Allow for setting a column using an update builder if it hasn't already been set.
This is a work-around for issue #1316.
=> UpdateBuilder: allow check if column is set

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Column.kt
the super.Expression.equals contains  
https://github.com/JetBrains/Exposed/blob/6fb5a3cf39eef4f1b240fe7e98857189f70f5970/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Expression.kt#L136
where `toString` resolves to 
https://github.com/JetBrains/Exposed/blob/6fb5a3cf39eef4f1b240fe7e98857189f70f5970/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Column.kt#L143
The problem here is that the same Column created from different places will inevitably have difference javaClass names. 
Such Column instantiations are required to build migration tools or when cache is dropped and columns and tables are read "from database". 
The column comparision should not be performed by technical informtion, but by busyness information only. That is, table name, column name and types should be …
=> remove call to super.equals

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Union.kt
Counting union results is currently broken on some databases (read oracledb) that don't support the as keyword when aliasing tables (or sub queries).  According to this [SO post](https://stackoverflow.com/questions/20479135/oracle-as-keyword-and-subqueries/20479233#20479233) the SQL 99 ANSI standard does not require the AS keyword when aliasing tables (or sub queries). So removing the as keyword on the union count query should fix this and be compatible with all RDBMS following the standard.
=> Fix counting unions

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Query.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/UpdateBuilder.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/InsertTests.kt
Fixes #1327 
Code sample:
````KOTLIN
tab1.insert { it[id] = tab2.slice(tab2.id).select { tab2.id eq "foo" } }
````
Just like `eqSubQuery`, we cannot do a type checking at compile time for this assignement  ( `it[id] = tab2.slice(tab2.id).select { tab1.id eq "foo" }`) as we don't have the return type of the query.
=> Supporting subqueries in insert and update statements

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Database.kt
When using the serverTimezone (e.g. Europe/Moscow) parameter when connecting to a database, the property returned wrong the database name
=> fix database name extension property

exposed-bom/build.gradle.kts
When adding the bom as a gradle platform, like this:
```
implementation(platform("org.jetbrains.exposed:exposed-bom:0.34.1"))
```
Gradle fails with the following error:
```
> No matching variant of org.jetbrains.exposed:exposed-core:0.34.1 was found. The consumer was configured to find an API of a component compatible with Java 11, packaged as a jar, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.gradle.category' with value 'platform', attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm', attribute 'javaModule' with value 'true' but:
- Variant 'apiElements' capability org.jetbrains.exposed:exposed-core:0.34.1 declares an API of a component compatible with Java 8, packaged as a jar, and its dependencies declared …
```
=> Fix bom for gradle projects

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Column.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Constraints.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SchemaUtils.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Mysql.kt, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcDatabaseMetadataImpl.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateMissingTablesAndColumnsTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateTableTests.kt, spring-transaction/src/test/kotlin/org.jetbrains.exposed.spring/SpringCoroutineTest.kt
This PR closes #511 (and its duplicate #1234).
From the DSL point of view, there was added a new method for the `Table` class (`foreignKey`), supposed to be called in `init`
block.
It has two overloads, allowing two ways for defining composite foreign keys:
1. listing pairs of the column to column references (set of referenced columns must form an explicit unique constraint)
2. listing columns set referencing primary key:
```
val TableC = object : Table("TableB") {
val idA1 = integer("id_a1")
val idA2 = integer("id_a2")
val idB1 = integer("id_b1")
val idB2 = integer("id_b2")
init {
foreignKey(idA1 to TableA.idA1, idA2 to TableA.idA2)
foreignKey(idB1, idB2, target = TableB.primaryKey) // foreignKey(idB1 to TableB.idB1, idB2 to TableB.idB2) is also possible
}
}
val TableA = object : …
```
=> Add composite foreign key

exposed-money/build.gradle.kts
This allows you to change H2 version at only 1 place
=> Use h2 version variable in exposed-money

exposed-kotlin-datetime/src/main/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinDateColumnType.kt
`Instant.fromEpochMilliseconds` expects epoch milliseconds as input but seconds are being passed here thus resulting in 
`2021-01-10` being stored as `1970-01-19` in the database
=> Fix conversion of LocalDate to database string

exposed-spring-boot-starter/src/main/kotlin/org/jetbrains/exposed/spring/autoconfigure/ExposedAutoConfiguration.kt, exposed-spring-boot-starter/src/test/kotlin/org/jetbrains/exposed/spring/autoconfigure/ExposedAutoConfigurationTest.kt, spring-transaction/src/main/kotlin/org/jetbrains/exposed/spring/SpringTransactionManager.kt, spring-transaction/src/test/kotlin/org.jetbrains.exposed.spring/SpringTransactionTestBase.kt
SpringTransactionManager does not allow to pass DatabaseConfig inside.
=> Allow to pass DatabaseConfig in SpringTransactionManager

exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/h2/H2Tests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateMissingTablesAndColumnsTests.kt
Currently, this test is always considered as skipped, as it actually contains several tests (for different DBs), and one of the internal assumptions about the accordance of DB enabled in a test run and DB required for test inevitably fails.
This PR splits it into dedicated tests for specific DBs (and adds some other improvements)
=> Fix `addAutoPrimaryKey` test

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Database.kt
Solution for #1406
After checking the latest changes, I see that `getDefaultIsolationLevel` is deprecated. We are using version `0.32.1` where `DatabaseConfig` was not implemented (:
=> use TRANSACTION_READ_COMMITTED transaction level for sqlserver dialect

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/ConditionsTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/SelectTests.kt
This PR fixes https://github.com/JetBrains/Exposed/issues/1437 by making `fun <T : Comparable<T>, E : EntityID<T>?> ExpressionWithColumnType<E>.eq(t: T`~?~`)` overload accept only non-nullable arguments. Passing `null` to receivers of this type will be resolved to more general overload `<T> ExpressionWithColumnType<T>.eq(t: T)` having the same logic for processing of this value.
Also, this PR fixes the same problem for `neq` method and unifies their API and implementation.
=> Fix method resolution ambiguity when passing null to eq/neq methods

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Op.kt
This PR simplifies and imposes more strict limitations on the `CompoundBooleanOp` type definition (`abstract` -> `sealed`).
Potentially this is a breaking change (now this class can't be extended by users, and if someone extended it earlier, compilation will fail for him), but I don't think anyone sane will be affected.
=> Refactor `CompoundBooleanOp` class

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ResultRow.kt
This PR not only fixes https://github.com/JetBrains/Exposed/issues/1435 (which is a rather specific use-case) but also improves performance of the `ResultRow.create` method if some fields of `ResultSet` are `NULL`.
=> Fix `ResultRow` creation

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/UpdateBuilder.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt
As @m-burst mentioned in https://github.com/JetBrains/Exposed/pull/1417 conversation, the same problem could arise in another place. This PR fixes it in the same manner as https://github.com/JetBrains/Exposed/pull/1417.
Also, it applies the same fix in `UpdateBuilder` class for checks that the value which is set to non-nullable column is not null. Although these checks are done in methods, which are intended to be called inside a transaction (so it's shouldn't lead to `IllegalStateException` in runtime), this fix still makes sense from the performance point of view (type check should be faster than `equals` method call)
=> Fix check constraint-2

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Column.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityClass.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/IntEntity.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/LongEntity.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/UUIDEntity.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityTests.kt
This PR replaces reflection with regular code in two places:
1.  Cloning a `Column` to replace its type with auto-increment.
2. `EntityClass.createInstance`
On my computer it brings down the time to run this code for the 1st time from ~750ms to ~300ms:
```
Database.connect("jdbc:h2:mem:test", driver = "org.h2.Driver")
transaction{
addLogger(StdOutSqlLogger)
City.new { name = "St. Petersburg" }
println("Cities: ${City.all().toList()}")
}
```
Fixes #1453
=> Improve initialization performance

exposed-java-time/build.gradle.kts, exposed-kotlin-datetime/build.gradle.kts, exposed-spring-boot-starter/build.gradle.kts, exposed-tests/build.gradle.kts, spring-transaction/build.gradle.kts
You can't compile Exposed with Java 17 because it fails with the following error.
```
Unrecognized VM option 'MaxPermSize=256m'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Process 'Gradle Test Executor 122' finished with non-zero exit value 1
org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 122' finished with non-zero exit value 1
at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:414)
at org.gradle.process.internal.worker.DefaultWorkerProcess.onProcessStop(DefaultWorkerProcess.java:141)
at org.gradle.process.internal.worker.DefaultWorkerProcess.access$000(DefaultWorkerProcess.java:42)
at …
```
=> Disable `-XX:MaxPermSize` flag if the JDK version is Java 8 or higher

exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcConnectionImpl.kt
Currently, in Postgres + Spring Transaction setup, 
`SHOW TRANSACTION ISOLATION LEVEL` is executed every time a transaction is started, as shown in the image.
So, I changed the initialization of `transactionIsolation` to be lazy.
=> Reduce `SHOW TRANSACTION ISOLATION LEVEL` in Postgres

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Transaction.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/StatementInterceptor.kt
Adding transaction to lifecycle hooks to support #1530.
Note:
- This is a breaking change to the `StatementInterceptor` interface
=> Add Transaction to lifecycle hooks for #1530

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Op.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/functions/FunctionsTests.kt
This PR adds two functions(`andIfNotNull`, `orIfNotNull`) that allow to combine null condition with and/or in where clause.
A query statement is often composed with required and optional parameters. For optional parameters, we can add them to where clause with following syntax(from wiki):
```kotlin
val query = StarWarsFilms.selectAll()
directorName?.let {
query.andWhere { StarWarsFilms.director eq it }
}
sequelId?.let {
query.andWhere { StarWarsFilms.sequelId eq it }
}
```
With this PR the syntax can be simplified:
```kotlin
val query = StarWarsFilms.select {
Op.TRUE andIfNotNull // No required parameters in this sample, a non-null condition is needed as beginning
directorName?.let { StarWarsFilms.director eq it } andIfNotNull
sequelId?.let { StarWarsFilms.sequelId eq it }
}
```
=> Support combining nullable parameters in WHERE clause

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/transactions/experimental/Suspended.kt
Our team has wanted to specify additional Coroutine context elements when using newSuspendedTransaction, but are unable to do so as the newSuspendedTransaction requires a CoroutineDispatcher type rather than a CoroutineContext type.
This seems relatively harmless but am curious what the rationale is w/ regards to forcing a CoroutineDispatcher type.
i.e.
```
We want to do something like this:
newSuspendedTransaction(Dispatchers.IO + openTelemetryContext)
```
=> Allow for specifying a CoroutineContext when creating a newSuspendedTransaction.

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Mysql.kt
Fix raise `java.sql.SQLException` when use expression in mysql replace statement.
``` kotlin
import org.jetbrains.exposed.sql.*
import org.jetbrains.exposed.sql.transactions.transaction
import org.junit.jupiter.api.Test
object Users : Table() {
val id = integer("id").autoIncrement()
val name = varchar("name", length = 50).uniqueIndex()
val cityId = integer("city_id").references(Cities.id).nullable()
override val primaryKey = PrimaryKey(id)
}
object Cities : Table() {
val id = integer("id").autoIncrement()
val name = varchar("name", 50).uniqueIndex()
override val primaryKey = PrimaryKey(id)
}
fun main() {
Database.connect(url = "jdbc:mysql://localhost:3306/exposed_test", driver = "com.mysql.cj.jdbc.Driver", user = "<USERNAME>", password = "<PASSWORD>")
transaction { …
```
=> Fix argument value error when use expression in mysql replace statement

exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityClass.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/h2/EntityReferenceCacheTest.kt
Currently, trying to find `User` with id of `City`. Should update cache of `City`
=> EntityClass#wramUpReferences should cache reference of referrer

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt
Fixes https://github.com/JetBrains/Exposed/issues/1496 by creating the primary key constraint name without including schema name
=> Fix creation of composite primary key in schema

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Exceptions.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Transaction.kt
* Use monotonic time.
* Remove empty RuntimeException() for warn message.
=> Polish long query logging.

exposed-java-time/src/test/kotlin/org/jetbrains/exposed/JavaTimeTests.kt, exposed-jodatime/src/test/kotlin/org/jetbrains/exposed/JodaTimeTests.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinTimeTests.kt
Hi - here's my attempt at improving the datetime/timestamp comparison in tests.  
I'm using the precision that Exposed has enabled for each dialect, but a lot of them can go to a higher precision.  See my issue for comments.
There are 2 lines commented out for Mysql.  The comparison seems odd, but this is existing behaviour and the tests aren't comparing the nanoseconds at all for a lot of cases.
I'm also unable to run the suite successfully on my machine (https://github.com/JetBrains/Exposed/issues/1368).
I'm attempting to fix these tests so we can merge the PR https://github.com/JetBrains/Exposed/pull/1223.
Another idea might be to have a variable tied to all dialect, which could be overridden.
=> #1370 redo datetime/timestamp comparison in tests

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/BooleanColumnTypeTests.kt
Fix how bool values are sent to Oracle DB. Previously `BooleanColumnType`
didn't do any conversion so real boolean value did reach JDBC and it has
been converted to numeric value of 0 or 1.
This behavior is not correct as bool columns in Exposed are CHAR(1) in Oracle.
We need to pass bool as a string instead of a number otherwise Oracle will not use
indexes when such column is used in WHERE clause.
Example:
create table foo (boolColumn char(1));
create index foo_idx on foo (boolColumn);
With numeric value:
select 1 from foo where boolColumn = 1;    // results in full table scan (ignores foo_idx)
--------------------------------------------------------------------------
| Id  | Operation         | Name | Rows  | Bytes | Cost (%CPU)| Time     | …
=> Fix bool column behavior in Oracle queries

exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/javatime/JavaDateColumnType.kt
Adding missing conversion of `LocalDateTime` to `Instant`.
=> JavaInstantColumnType: Adding ability to convert LocalDateTime to Instant

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Database.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Transaction.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/api/ConnectionApi.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/transactions/ThreadLocalTransactionManager.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/transactions/TransactionApi.kt, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcConnectionImpl.kt, exposed-tests/src/main/kotlin/org/jetbrains/exposed/sql/tests/DatabaseTestsBase.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/h2/MultiDatabaseEntityTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ThreadLocalManagerTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityTests.kt, spring-transaction/src/main/kotlin/org/jetbrains/exposed/spring/SpringTransactionManager.kt
Some of the database vendors allows to minimize resource impact by specifying that the transaction will not add any changes to the data. 
This MR attempts to add that parameter,
=> Add read-only transaction parameters

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Database.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Queries.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/Entity.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/InnerTableLink.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/demo/sql/SamplesSQL.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateMissingTablesAndColumnsTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/DeleteTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/InsertTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityTests.kt
This feature allows to omit table name from the where clause of delete queries.
Instead of:
https://github.com/JetBrains/Exposed/blob/bd5709f8e21983ffbe4b39f66b2412a73bb9c603/exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/DeleteTests.kt#L35
This now could be simplified to 
```kotlin
users.deleteWhere { name like "%thing" }
```
=> Table aware deleteWhere 

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Queries.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/InsertTests.kt
insertIgnoreAndGetId conceals the fact of failed insert by returning the provided values instead of `null`. The existing nullable result contract is not honored for PG / MySQL
=> insertIgnoreAndGet must explicitly mark failed insert on conflicts

exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/javatime/JavaDateColumnType.kt, exposed-money/src/test/kotlin/org/jetbrains/exposed/sql/money/MoneyDefaultsTest.kt, exposed-spring-boot-starter/src/test/kotlin/org/jetbrains/exposed/spring/autoconfigure/ExposedAutoConfigurationTest.kt
Hi i am Heli who using Exposed
First, changed some codes to not use the platform type. platform type requires unnecessary boilerplate(!!, let trick, ...) And open source is a guide to writing code.
so i think bad code examples should be deleted.
Second, change 'when' expression style
thanks. 🙇
--
There is no change that users can feel.
=> fix some codes to not use platform type and expression style

buildSrc/src/main/kotlin/org/jetbrains/exposed/gradle/Versions.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Database.kt, exposed-tests/build.gradle.kts, exposed-tests/src/main/kotlin/org/jetbrains/exposed/sql/tests/DatabaseTestsBase.kt
Fix pg embedded test segfaults 
```
/➜  src  file /PG-578c3302bce806451b07e3a73d8438d1/bin/postgres -v
/PG-578c3302bce806451b07e3a73d8438d1/bin/postgres: Mach-O universal binary with 2 architectures: [i386:Mach-O executable i386
- Mach-O executable i386] [x86_64]
/PG-578c3302bce806451b07e3a73d8438d1/bin/postgres (for architecture i386):	Mach-O executable i386
/PG-578c3302bce806451b07e3a73d8438d1/bin/postgres (for architecture x86_64):	Mach-O 64-bit executable x86_64
➜  src   /PG-578c3302bce806451b07e3a73d8438d1/bin/postgres -v
[1]    81714 segmentation fault   -v
```
=> migrate pg tests to testcontainer module

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/transactions/experimental/Suspended.kt
Some parts of the API is using `CoroutineContext` and other is using `CoroutineDispatcher`. I fixed it by changing all to `CoroutineContext`, which is the parent class of `CoroutineDispatcher`.
=> Fix suspendedTransaction coroutine context type

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Database.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Mysql.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLServerDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt
Distinct the particular text types. 
Current implementation uses `longtext` everywhere. It does make sense as most of the DB Engines keeps the reference and not the actual value. However that limits some scenarios relying on the exact "unlimited" text type length to discover externally indexable columns. 
In addition, in some scenarios appealing to the largest text possible introduced unwanted flexibility. 
Understandably, not every DB Engine make sense from this. To my best beliefs,  the ones who does are mysql (and compatible engines), Oracle, MSSql.
=> add particular text lenght subtypes

exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/References.kt
`with` call should not change the receiver type, this is not what it is called for :)
=> preserve colection type

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/IterableEx.kt
It would be nice to allow developer to know whether lazily loaded is already loaded. 
My use case is a simple mapping from DAO entity to dto. Currently I need to pass extra param, which tells the mapping function to skip certain attributes - to avoid extra loading or exception.
With this function I can easily check that:
```kotlin
val messages by DiscussionMessageEntity referrersOn DiscussionMessageTable.discussionId
...
val messageDtos = if ((messages as LazySizedCollection).isLoaded()) {
messages.map { it.toDto() }
} else {
listOf()
}
```
=> Expose info whether lazy collection is loaded

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Constraints.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Database.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateTableTests.kt
=> Allow defining tables with quoted names

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/DefaultsTest.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/DefaultsTest.kt
See issue #1612 
Due to `fun <T : Any> Column<T>.clientDefault` requiring `T : Any`, this function is not usable with nullable columns. As discussed in the above issue, this PR removes this requirement and doesn't seem to break anything.
Running the `:exposed-tests:test` I get 2319 passed, 333 ignored, no failed. I assume that those 333 are supposed to be ignored as nothing except the function signature has been changed.
=> make clientDefault extend <T> instead of <T : Any>

exposed-tests/src/main/kotlin/org/jetbrains/exposed/sql/tests/DatabaseTestsBase.kt
As described in testcontainers/testcontainers-java#318 Kotlin since `1.5.30` is [improved](https://kotlinlang.org/docs/whatsnew1530.html#improvements-to-type-inference-for-recursive-generic-types) type inference for recursive generic types and since `1.6` this improvement is [enabled by default](https://kotlinlang.org/docs/whatsnew16.html#improved-type-inference-for-recursive-generic-types).
=> Remove unnecessary proxy class

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt
Fixes  #1628 
In Oracle, the `VARCHAR` type is reserved and has the potential to change in the future. `VARCHAR2` should be used instead since it won't change. I also added the `CHAR` specification so that the column length always corresponds to characters instead of bytes or characters depending on the `NLS_LENGTH_SEMANTICS` database setting.
=> Use VARCHAR2 column for VarCharColumnType when on Oracle

exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/Entity.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityBatchUpdate.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/ForeignIdEntityTest.kt
Making sure that when we update an entity with an id which is a foreign key to another table, the assertion in `EntityBatchUpdate.addBatch()` allows this.
Closes #880
=> Fix an error when updating an entity with a foreign key id (issue 880)

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt
Only show the length of the value instead of the value itself when exceeding the column length.
Based on solution 1 as mentioned in JetBrains/Exposed#1666
Closes JetBrains/Exposed#1666
=> Show length instead of value for exceeded column length

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt
Previously, `PostgreSQLDialect.modifyColumn` was not able to drop default values.
=> Fix: PostgreSQLDialect.modifyColumn is not able to drop default values

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt
Long.toInt will get a negative number if the value is greater than Int.MAX_VALUE
=> Fix UInt value out of bounds

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Column.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateTableTests.kt
Adjust equals() method in EntityIDColumnType.
IdTable creates a column of EntityIDColumnType to replace the original when .entityId() is invoked. PrimaryKey() accepts arguments that can either be the former or the original column of non-EntityIDColumnType. This results in a failure to adequately compare column types when resolving a column's description of its primary key constraint.
Both isOneColumnPK() and isLastColumnInPK() are also adjusted so that equals() is invoked by the EntityIDColumnType (if present). This covers the potential case when an IdTable may be created with a single primary key column that has a user-defined name.
An extra test is added to cover testing of ddl involving a single primary key column in a Table. Existing related tests only cover Tables created with …
=> EXPOSED-21 Primary key constraint not created

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ResultRow.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityTests.kt
In the `setInternal` function in `ResultRow`, the expression `c` could not be found in the `fieldIndex` map because the column comparison fails because of a type mismatch between EntityIDColumnType and VarCharColumnType.
Paired with @bog-walk 🙌🏼
=> fix: EXPOSED-27 Id is not in record set

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/H2.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/UpdateTests.kt
`update()` with join in  `H2FunctionProvider` allows a WHERE clause to be appended to the query, even though the H2 [MERGE INTO](https://www.h2database.com/html/commands.html#merge_into) command supports WHERE minimally. So if a compatibility mode does not support WHERE in merge, the driver throws an unclear `JdbcSQLSyntaxErrorException`.
[Documentation](https://www.h2database.com/html/features.html#compatibility_modes) and tests show that the only H2 mode to support WHERE clause is Oracle mode.
This catches all unsupported cases and throws an `UnsupportedByDialectException` with a more informative message.
=> fix: EXPOSED-28 Update with join fails on H2 in MySql mode

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/UpdateBuilder.kt, exposed-money/src/test/kotlin/org/jetbrains/exposed/sql/money/MoneyTests.kt
Remove the upper bound generic constraint for the function `set(column: CompositeColumn<S>, value: S)`
https://kotlinlang.org/docs/generics.html#upper-bounds:~:text=The%20default%20upper%20bound%20(if%20there%20was%20none%20specified)%20is%20Any%3F
=> fix: EXPOSED-29 Cannot set nullable composite column in InsertStatement

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/H2.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt
Fix indexing behavior on text column in H2 v2.x
H2 version 1.x does not support indexing on `text` columns, with attempts to create a primary key throwing a `JdbcSQLFeatureNotSupportedException`, while `.uniqueIndex()` and `index()` log a warn & ignore the attempt.
H2 2.x supports indexing on `text` columns, except when in Oracle mode, because `text` maps to `clob`. Attempting to create a primary key in Oracle mode still throws an exception, but index can now be actually created by `.uniqueIndex()` and `index()` in all other modes.
=> fix: EXPOSED-23 H2 unsupported indexing behavior

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Function.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/H2.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/MariaDBDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Mysql.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLServerDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLiteDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/functions/FunctionsTests.kt
Added CHARINDEX function support per #1059. Only supported for sql server for now, will add other dialects in the next PR.
=> Add CHARINDEX function for sqlserver

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Function.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLServerDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLiteDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/functions/FunctionsTests.kt
Rationale for:
- Function Name: Opted to use `CharLength` instead of `Length` to follow the ANSI SQL standards, even though all dialects support a function with a variation on the name 'length'. Also, `LENGTH()` specifically returns the length of the string measured in bytes in MySQL and MariaDB, whereas all versions of `CHAR_LENGTH()` return the expected single-character count.
- Expression Type: The function only accepts string expressions, so an explicit cast is required if a number needs to be provided to the function. Of the supported databases, only MySQL, MariaDB, and Sqlite support a numerical value argument for implicit casting by the database.
Partial fix for [#1059](https://github.com/JetBrains/Exposed/issues/1059)
=> feat: EXPOSED-32 Support string function CHAR_LENGTH

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Op.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/ConditionsTests.kt
The normal 3-valued logic of SQL syntax means the result of `null == null` is UNKNOWN, which returns `null` instead of `true`.
Supporting null-safe comparison, using IS [NOT] DISTINCT FROM and its variants, allows 2 null values to be treated as equivalent. This limits the return value of the equality comparison to only 2 values: `true` or `false`.
=> feat: EXPOSED-37 Support null-safe equality comparison

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/DefaultsTest.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/DefaultsTest.kt
=> Remove unnecessary parentheses for functions

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SchemaUtils.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateDatabaseTest.kt
Simply added a more informative message in the exception thrown when `autoCommit` needs to be `true`
=> chore: Add to exception descriptive message indicating required autoCommit status for create/drop database

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLiteDialect.kt, exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/javatime/JavaDateColumnType.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/JavaTimeTests.kt, exposed-jodatime/src/main/kotlin/org/jetbrains/exposed/sql/jodatime/DateColumnType.kt, exposed-jodatime/src/main/kotlin/org/jetbrains/exposed/sql/jodatime/DateFunctions.kt, exposed-jodatime/src/test/kotlin/org/jetbrains/exposed/JodaTimeTests.kt, exposed-kotlin-datetime/src/main/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinDateColumnType.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinTimeTests.kt
`LocalDate` value was being passed to database as `java.sql.Date`, stored as a 13-digit integer because the object represents **milliseconds** since 1970-01-01. Date datatype in SQLite passed to date functions as an integer must be of a specific format, 10 digits, to represent the number of **seconds** since 1970.
Conversion to a recognizable format could be achieved by changing the dialect's date functions, like `year()` e.g.:
```STRFTIME('%Y', date_column / 1000, 'unixepoch')```
But this would break cases where the same date functions are used for `LocalDateTime` values.
Date value is instead passed to database as a string, since [multiple formats](https://www.sqlite.org/lang_datefunc.html#time_values) are recognized for comparison.
To match this changed format, `LocalDate` column …
=> fix: EXPOSED-36 LocalDate comparison in SQLite

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Queries.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/UpsertStatement.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Mysql.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLServerDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLiteDialect.kt, exposed-tests/src/main/kotlin/org/jetbrains/exposed/sql/tests/DatabaseTestsBase.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/UpsertTests.kt
Add functionality for INSERT or UPDATE command.
MySQL, PostgreSQL, and SQLite use their own specific implementations, while the other dialects use the standard MERGE USING statement with aliases and a derived table.
Accepts **optional user-defined key columns** to determine the conflict condition. If none are provided, the primary key is used. If there is no primary key, the first unique index is used. If there are no unique indices, each dialect handles differently, but any documentation should probably strongly advise that keys are defined to avoid unexpected results.
Accepts an **optional WHERE clause**, as well as **user-defined update assignments** if update behaviour differs from insert behaviour. **Column expressions, defaults, and subqueries** are also enabled if the individual …
=> feat: EXPOSED-45 Support single statement UPSERT

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Queries.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/BatchReplaceStatement.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/InsertStatement.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/ReplaceStatement.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/H2.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Mysql.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLiteDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/h2/H2Tests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/ReplaceTests.kt
KDocs stated that `replace()` inserts a new row or updates the existing row if a unique constraint conflict is found, which is equivalent to an upsert command. They have been edited to state that REPLACE performs an "insert or delete then insert" command, as per the dialects that actually support it ([MySQL](https://dev.mysql.com/doc/refman/8.0/en/replace.html), [SQLite](https://www.sqlite.org/lang_conflict.html)).
Classes `ReplaceStatement` and `BatchReplaceStatement` refactored since supported vendors use syntax very similar to INSERT statement. Duplicate code from `InsertStatement`'s `prepareSql()` extracted to a protected helper function so that it can also be used in the 2 replace classes.
Test suites refactored to better test for expected "insert or delete then insert" behavior. 1 …
=> fix: EXPOSED-49 Replace statement defined as upsert statement

docs/ChangeLog.md
PR https://github.com/JetBrains/Exposed/pull/1561 inadvertently introduced some breaking changes.
See https://github.com/JetBrains/Exposed/issues/1610 for more context regarding breakage.
=> Note breaking change in 0.40.1

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Function.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLServerDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLiteDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/functions/StatisticsFunctionTests.kt
The aggregate functions for statistics were failing on:
- [SQLite] with `no such function` exception from DB. Now they fail early with an `UnsupportedByDialectException`.
- [SQL Server] because of unrecognized syntax. Now they use the correct function name.
Add a new test class for statistics aggregate functions.
=> fix: EXPOSED-48 Incorrect statistics aggregate functions

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Queries.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/BatchUpsertStatement.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityLifecycleInterceptor.kt, exposed-tests/src/main/kotlin/org/jetbrains/exposed/sql/tests/DatabaseTestsBase.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/UpsertTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityTests.kt
Add support and tests for batch UPSERT query.
Extract an existing table object to use across multiple tests in `UpsertTests` suite.
Extract commonly-grouped collection of MySQL-specific `TestDB` to a companion object property, so they can be easily accessed across test files.
Edit `EntityLifecycleInterceptor` and add test for entity cache invalidation when DSL `(batch)upsert` used alongside DAO, as per issue [#914](https://github.com/JetBrains/Exposed/issues/914).
=> feat: EXPOSED-52 Support batch UPSERT

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/InsertStatement.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/InsertTests.kt
When executing a batch insert, the number of inserted rows is the sum of the batch rows instead of the count.
Making this distinction allows extensions of batch insert like
```kotlin
class MyBatchInsertStatement(
table: Table,
) : BatchInsertStatement(table) {
override fun prepareSQL(transaction: Transaction) = buildString {
append(super.prepareSQL(transaction))
append(" ON CONFLICT (id) DO NOTHING")
}
}
```
where the return value of `execute` is still accurate.
=> Sum batch results for inserts

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Constraints.kt, exposed-tests/src/main/kotlin/org/jetbrains/exposed/sql/tests/DatabaseTestsBase.kt, exposed-tests/src/main/kotlin/org/jetbrains/exposed/sql/tests/shared/ForeignKeyTables.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateTableTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/sqlite/ForeignKeyConstraintTests.kt
The `SET_DEFAULT` reference option is not supported in:
-  [MySQL 5.1.49](https://github.com/JetBrains/Exposed/blob/f0308188e0911f8f623b6b55f4998e59a5459963/buildSrc/src/main/kotlin/org/jetbrains/exposed/gradle/Versions.kt#L15) according to this [manual](http://download.nust.na/pub6/mysql/doc/refman/5.1/en/innodb-foreign-key-constraints.html) since it is not mentioned as one of the possible reference options
- in [MariaDB](https://mariadb.com/kb/en/foreign-keys/#:~:text=The%20SET%20DEFAULT%20action%20is%20not%20supported.) ([Stack Overflow](https://stackoverflow.com/a/30585123/11310485))
The way I handled this is the same way the `ON UPDATE` clause was handled for Oracle.
In SQLite, [foreign key constraints are disabled by default](https://www.sqlite.org/releaselog/3_6_19.html#:~:text=Fore …
=> feat: EXPOSED-47 Add support for SET DEFAULT reference option

exposed-core/api/exposed-core.api
apiDump was not performed prior to merging PR#1621, causing failed build checks on main.
=> build: Perform apiDump to fix failed merge build

detekt.yml, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/BatchUpsertStatement.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/UpsertStatement.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt
Replace spread operators with named arguments in code that was producing warnings on build.
Note that, while this removes warnings, analyzed bytecode still shows that a copy of the array is being made.
See issue https://youtrack.jetbrains.com/issue/KT-17043
=> fix: EXPOSED-64 Fix Detekt SpreadOperator warnings

buildSrc/src/main/kotlin/org/jetbrains/exposed/gradle/Versions.kt, exposed-core/api/exposed-core.api, exposed-core/build.gradle.kts, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Function.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/H2.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Mysql.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLServerDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLiteDialect.kt, exposed-tests/build.gradle.kts, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/JsonBColumnTypeTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/JsonColumnTypeTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/JsonTestsData.kt, settings.gradle.kts
Add 2 new column types: `JsonColumnType` & `JsonBColumnType` that can be used 3 ways:
```
json("column_name", Json, Type.serializer()) // or custom serializer
json<Type>("column_name", Json)
json("column_name", customEncoder(), customDecoder())
```
Dialects store JSON differently, usually in text or binary format, but may not reflect this in the name of the data type. Some may not even support the JSON data type, but use it as an alias for another type (e.g. [MariaDB](https://mariadb.com/kb/en/json-data-type/) maps JSON to LONGTEXT and [H2](https://www.h2database.com/html/datatypes.html#json_type) maps to `byte[]`). To allow for this variability, the user's choice between `json()` and `jsonb()` can be flexible depending on dialect, e.g.:
- [PostgreSQL] `json()` -> JSON, `jsonb()` -> JSONB …
=> feat: EXPOSED-60 Support json/json(b) column types

build.gradle.kts, buildScripts/gradle/publishing.gradle.kts
Part of the steps for [EXPOSED-41](https://youtrack.jetbrains.com/issue/EXPOSED-41)
=> chore: Set up Maven publishing

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/H2.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/JsonBColumnTypeTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/JsonColumnTypeTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/JsonTestsData.kt
**H2:**
H2 started supporting JSON data type (maps to `byte[]`) in [version 1.4.200](https://github.com/h2database/h2database/releases/tag/version-1.4.200) and Exposed tests use version 1.4.199. Since v1.4.2 was the final version before 2.0 release and [v1 is being phased out](https://youtrack.jetbrains.com/issue/EXPOSED-30/Phase-Out-Support-for-H2-Version-1.x), H2 v1 is excluded from tests (the test blocks were fixed to properly do this).
Extended support does not cover existing functions as H2 only supports [two json-constructing functions](https://www.h2database.com/html/functions.html#json_object).
**Oracle:**
Oracle started supporting JSON data type in native binary format [as of 21c](https://docs.oracle.com/en/database/oracle/oracle-database/21/adjsn/json-in-oracle-database.html#GUID …
=> feat: EXPOSED-69 Extend json support to H2, Oracle (text) and DAO

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Function.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Op.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Mysql.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLServerDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLiteDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/JsonBColumnTypeTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/JsonColumnTypeTests.kt
**Add** dialect overrides and unit tests for:
- `jsonContains()` -> Checks if the invoking JSON column expression contains the specific expression argument provided.
- `jsonExists()` -> Checks if any data exists at the specified path within the invoking JSON column expression. **Note:** SQLServer does have a relevant function but it is only available as of latest 2022 v16.x, while Exposed tests and supports 2017 v14.x.
**Fix** issues with `jsonExtract()`:
- [Postgres] Supports 2 variants, for either JSON or JSONB type, so a way to distinguish between the invoking column types needed to be added. This also allows casting since the 2 new functions only accept JSONB values.
- Some dialects were hard-coded with the prefix `'$.'`, but the root context item alone `'$'` is actually a valid JSON …
=> feat: EXPOSED-68 Add more json/json(b) column functions

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Database.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Op.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SchemaUtils.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/StatementInterceptor.kt, exposed-dao/api/exposed-dao.api, exposed-java-time/api/exposed-java-time.api, exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/javatime/JavaDateFunctions.kt, exposed-jodatime/api/exposed-jodatime.api, exposed-jodatime/src/main/kotlin/org/jetbrains/exposed/sql/jodatime/DateFunctions.kt, exposed-kotlin-datetime/api/exposed-kotlin-datetime.api, exposed-kotlin-datetime/src/main/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinDateFunctions.kt
Raise levels of API `@Deprecated` annotations as per [gradual phase-out guidelines](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-deprecated/#kotlin.Deprecated).
**Note**: All elements had most recent level change on last release (0.41.1 - November 2022), except `createFKey()`, which was last changed on 12/2021.
**Raise from WARNING to ERROR**:
- Op.kt classes: `LikeOp` and `NotLikeOp`
**Raise from ERROR to HIDDEN** (to preserve binary compatibility with previously compiled code):
- `CurrentDateTime` object's `invoke()` (in all 3 date-time modules)
- `StatementInterceptor` interface's `afterCommit()` and `afterRollback()`
- `SchemaUtils` object `createFKey()`
- SQLExpressionBuilder.kt `Sequence.nextVal()` and `SqlExpressionBuilderClass`
**Currently HIDDEN, now removed**:
- …
=> deprecate: EXPOSED-84 Raise deprecation levels of API elements

.idea/detekt.xml
This change makes the warnings that appear in the IDE based on rules set in the `detekt.yml` config file. The steps to do it were Settings -> Tools -> detekt -> + Add configuration file -> Choose detekt.yml. This automatically adds a component called "DetektPluginSettings" in `detekt.xml`, which I modified further.
Thanks @bog-walk for catching this.
=> chore: add detekt IntelliJ plugin configuration to detekt.xml

exposed-tests/src/main/kotlin/org/jetbrains/exposed/sql/tests/DatabaseTestsBase.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateMissingTablesAndColumnsTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/InsertTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/JsonBColumnTypeTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/JsonColumnTypeTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/JsonTestsData.kt
Add unit tests for JSON and JSONB functions using stored values that contain either a top-level JSON array (`'[1, 2, 3]'`) or an array nested in a JSON object (`'{"a":1,"b":[1, 2, 3]}'`).
Extract common conditional check for older versions of MySQL (and MariaDB) to `DatabaseTestsBase` class.
=> test: Add json/jsonb array tests

exposed-java-time/build.gradle.kts, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/JavaTimeTests.kt, exposed-jodatime/build.gradle.kts, exposed-jodatime/src/test/kotlin/org/jetbrains/exposed/JodaTimeTests.kt, exposed-kotlin-datetime/build.gradle.kts, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinTimeTests.kt
Add unit tests using JSON values that contain datetime strings, to check how extraction of values and value comparison is handled.
**Note:**
`java.time` and `org.joda.time` types do not have implicitly supported serializers from `kotlinx.serialization` library, unlike `kotlinx.datetime` types. This means a [custom serializer](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#serializing-3rd-party-classes) needs to be used, either specified on a property (as seen in the tests) or on an entire file. This also means that current implementation of `jsonExtract()` will not allow extraction as a JSON value (with `toScalar = false`) because the function uses the implicit type serializer `serializer<T>()` for datetime types.
=> test: Add jsonb datetime tests

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/EnumerationTests.kt
Currently, a column can be created with a reference to either `EnumerationColumnType` or `EnumerationNameColumnType`, but trying to do so using a column created via `customEnumeration()` throws a `NullPointerException`.
The NPE is thrown by `clone()` when attempting [to first access the column type's primary constructor](https://github.com/JetBrains/Exposed/blob/main/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt#L1135). Because `customEnumeration()` specifies a database-specific type, its `IColumnType` is being registered as the custom SQL type argument through an anonymous object. The anonymous object does not provide a `KClass` with a valid `primaryConstructor`.
Extracting this object to a new class `CustomEnumerationColumnType` provides a valid `KClass` instance to …
=> fix: EXPOSED-50 customEnumeration reference column error

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Constraints.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/H2.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/MariaDBDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Mysql.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLServerDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateIndexTests.kt
Add support for functional indices.
**Problem 1 - Getting Table Info:**
Data class `Index` currently gets `Table` information from user-provided `columns`. If an index is defined using only functions, the `table` property cannot be derived, since `Function` class does not store such info. In this case, table info needs to be directly provided, so this is done automatically if a user defines `functions`.
**Problem 2 - Naming the Index:**
Current behavior is to append column names to table name. `Function` class does not store a name, so it will be derived from the function string (works for Exposed functions of the form NAME(expr)). If a custom function doesn't have this format, the entire string is used instead.
- _Alternative_: Force users to provide a `customIndexName` if functions are …
=> feat: EXPOSED-89 Support functions in Create Index

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Constraints.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Mysql.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLServerDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLiteDialect.kt, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcDatabaseMetadataImpl.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateIndexTests.kt
**Affected DB : SQLite, MySQL**
`existingIndices()` in `JdbcDatabaseMetadataImpl` requires a COLUMN_NAME value from every table index retrieved through `DatabaseMetadata`. There is no metadata option for functions in the event that a function-based index is created instead.
The 4 databases that support function-based indices return different COLUMN_NAME values:
- [PostgreSQL] returns the function definition, e.g. `"lower((item)::text)"`
- [Oracle] returns the internal name of the virtual column, e.g. `"SYS_NC00006$"`
- [SQLite, MySQL] return null
The `!!` operator throwing the NPE has been replaced to ensure that indices defined by functions alone are still included instead of being ignored/throwing. This is important for `SchemaUtils` functions that validate index count, index name, or …
=> fix: EXPOSED-91 NPE in existingIndices() with function index

buildScripts/docker/docker-compose-sqlserver.yml
Switched to Azure SQL Edge because it's not possible to run earlier MS SQL Server version on hardware with ARM CPU. M1 and M2 chips from Apple use ARM architecture.
I tried to use 2.0.0, which is the [latest](https://mcr.microsoft.com/v2/azure-sql-edge/tags/list) at the time of writing this, but it didn't work for me and threw this error:
So I ended up using 1.0.7
How to test:
- Checkout branch locally
- Run any test for SQL Server
- It should pass with no issues
=> fix: SQLServerException: The port number -1 is not valid.

exposed-core/api/exposed-core.api
Fix failed build after merging #1672 without running `apiDump` Gradle task
=> build: run apiDump

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/DatabaseConfig.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Transaction.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/transactions/ThreadLocalTransactionManager.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/transactions/TransactionApi.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/transactions/TransactionScope.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/transactions/experimental/Suspended.kt, exposed-tests/src/main/kotlin/org/jetbrains/exposed/sql/tests/DatabaseTestsBase.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/h2/MultiDatabaseEntityTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/h2/MultiDatabaseTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/CoroutineTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/NestedTransactionsTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ThreadLocalManagerTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityTests.kt
Refactor suspend transaction functions, `newSuspendedTransaction` and `suspendedTransactionAsync`, to implement a similar retry policy as regular `transaction` by introducing mutable properties to `Transaction` class:
- repetitionAttempts
- minRepetitionDelay
- maxRepetitionDelay
```kt
newSuspendedTransaction {
repetitionAttempts = 10
// statements
}
```
Rename `Transaction.suspendedTransaction()` to `Transaction.withSuspendTransaction()`.
To be consistent across both regular and suspend transactions, these repetition parameters have been removed from `transaction` in favor of using the same `Transaction` class properties. 
```kt
transaction {
repetitionAttempts = 10
// statements
}
```
**Note** that current behavior had an empty transaction block (with no set repetition arguments) using …
=> fix: EXPOSED-80 Set repetition policy for suspended transactions

exposed-core/api/exposed-core.api, exposed-core/build.gradle.kts, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Function.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Op.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-java-time/build.gradle.kts, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/JavaTimeTests.kt, exposed-jodatime/src/test/kotlin/org/jetbrains/exposed/JodaTimeTests.kt, exposed-json/api/exposed-json.api, exposed-json/build.gradle.kts, exposed-json/src/main/kotlin/org/jetbrains/exposed/sql/json/JsonBColumnType.kt, exposed-json/src/main/kotlin/org/jetbrains/exposed/sql/json/JsonColumnType.kt, exposed-json/src/main/kotlin/org/jetbrains/exposed/sql/json/JsonConditions.kt, exposed-json/src/main/kotlin/org/jetbrains/exposed/sql/json/JsonFunctions.kt, exposed-json/src/test/kotlin/org/jetbrains/exposed/sql/json/JsonBColumnTests.kt, exposed-json/src/test/kotlin/org/jetbrains/exposed/sql/json/JsonColumnTests.kt, exposed-json/src/test/kotlin/org/jetbrains/exposed/sql/json/JsonTestsData.kt, exposed-kotlin-datetime/build.gradle.kts, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinTimeTests.kt, exposed-tests/build.gradle.kts, settings.gradle.kts
Create new module `exposed-json`.
Migrate over all JSON/JSONB column type classes, function classes, extension functions, & test suites from `exposed-core`.
Make `postgresql` driver `compileOnly` (and update `valueFromDB()` in column type classes to check for PostgresqlDialect) in new module.
Remove all `kotlinx-serialization` and `postgresql` driver dependencies from `exposed-core` and `exposed-tests` modules.
Add `testDependency` on new module to all 3 datetime modules.
**Code & Visibility Modifier Changes:**
- Replace internal `H2DataProvider` used in `JsonBColumnType` with public `originalDataProvider`.
- Replace column type check in `PostgreSQLFunctionProvider` that used `!is JsonBColumnType<*>` with a string check: `sqlType() != "JSONB"`.
- Replace internal `currentTestDb` with …
=> refactor: EXPOSED-88 Remove kotlinx-serialization dep from exposed-core

.github/workflows/detekt.yml, buildSrc/src/main/kotlin/org/jetbrains/exposed/gradle/DBTestingPlugin.kt, buildSrc/src/main/kotlin/org/jetbrains/exposed/gradle/tasks/DBTest.kt
The `detekt` GitHub Action will fail if there is a deleted file among the changed files because it attempts to check its content and fails at doing so. Also, there is no need to check the content of a file that was simply renamed. So I excluded deleted and renamed files from the `detekt` check.
The second commit is to test that the fix works because it includes a deleted file. I tested it on renamed files locally.
=> fix: Exclude deleted and renamed files from detekt GitHub Action

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/UnsignedColumnTypeTests.kt
MySQL and MariaDB are the only Exposed databases that actually support unsigned types natively, using the UNSIGNED type prefix. In spite of this, any value sent/received to/from the database is truncated to fit within the smaller Kotlin type SIGNED range (so it usually overflows).
For example:
```kt
// SMALLINT UNSIGNED ranges from 0 to 65535
object Tester : Table("tester") {
val unsignedShort = ushort("u_short")
}
transaction {
Tester.insert {
it[unsignedShort] = 65000u
}
// generates SQL:
// INSERT INTO tester (u_short) VALUES (-536)
// and fails with:
// com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Out of range value for column 'u_short' at row 1
}
```
Fix the logic in the 4 unsigned column type classes to ensure that both dialects' values are not truncated when …
=> fix: EXPOSED-97 Unsigned column types truncate MySQL values

spring-transaction/src/main/kotlin/org/jetbrains/exposed/spring/SpringTransactionManager.kt, spring-transaction/src/test/kotlin/org/jetbrains/exposed/spring/SpringMultiContainerTransactionTest.kt, spring-transaction/src/test/kotlin/org/jetbrains/exposed/spring/SpringTransactionEntityTest.kt
Our team has a monolithic architecture with multiple teams working on different domains in one codebase.
Each domain is isolated using Spring's container technology and consists of several child containers under a parent container, each connecting to the database using a different Datasource.
In this case, there are times when we want transactions to cross between the different domains for convenience. Using the traditional SpringTransactionManager, if a child transaction is executed, the parent transaction may encounter a "No transaction in context" error.
This error is caused by the current transaction manager in the TransactionManager interface not being updated properly across configuration boundaries.
Our team tried to solve this problem using the Stack.
We created logic that pushes …
=> feat: Add spring mutli container support

README.md
The README.md has a link to YouTrack, and if you aren't logged in, it just shows:
I've used YouTrack before and was still pretty confused by this.
"You might have more luck if you log in" is pretty subtle and easy to miss.
The README.md should likely have a note added.
=> fix: EXPOSED-98: Add instructions to log-in to see and log issues

exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/ColumnWithTransformTest.kt
Add test coverage for `ColumnWithTransform`.
=> test: Add test coverage for column transforms

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SchemaUtils.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/api/ExposedDatabaseMetadata.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Mysql.kt, exposed-jdbc/api/exposed-jdbc.api, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcDatabaseMetadataImpl.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/postgresql/PostgresqlTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateMissingTablesAndColumnsTests.kt
`SchemaUtils.createMissingTablesAndColumns()` invokes `addMissingColumnsStatements()` to generate the necessary ALTER statements when actualizing a new schema. The latter relies on detecting missing columns to create indices or primary keys (PK) on the new columns.
Attempting to move from a table without a PK, to a new table with a PK will not successfully create the PK if it is defined using only columns that already exist (i.e. no new columns detected to trigger adding a constraint):
```kt
// SUCCESS
object NoPKTable : Table("Foo") {
val bar = integer("bar")
}
object CompPKTable : Table("Foo") {
val bar = integer("bar")
val baz = varchar("baz", 32)
override val primaryKey = PrimaryKey(bar, baz)
}
transaction {
SchemaUtils.createMissingTablesAndColumns(NoPKTable) …
```
=> fix: EXPOSED-83 createMissingTablesAndColumns not detecting missing PK

exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/ConditionsTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/InsertTests.kt
The following tests in `exposed-tests` module fail when run using SQL Server:
**InsertTests/'batch insert number of inserted rows is accurate'()**
- SQL Server does not support insert or ignore (neither does Oracle, on which it also fails), so it has been excluded from the test.
- The test suite is adjusted to use a common list of databases that don't support insert or ignore.
- The failing test is also refactored to better cover MySQL-related databases, which actually support insert or ignore.
**ConditionsTests/testNullSafeEqualityOps()**
- Fails with the error: `com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near the keyword 'DISTINCT'` because IS DISTINCT FROM operator is only supported as of [SQL Server 2022](https://learn.microsoft.com/en-us/sql/t-sql/queries/is-dis …
=> test: Fix failing exposed-tests in SQL Server

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Function.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/ConditionsTests.kt
The class `CaseWhen` has a function `Else()` with a return type `Expression<R>`, which creates and returns an instance of the `CaseWhenElse` class. According to [commit 008db328](https://github.com/JetBrains/Exposed/commit/008db328c88ad65943e6e7b281af600234317da2), the `CaseWhenElse` class used to also extend `Expression<R>:
A few years ago, in [commit ff3ed717](https://github.com/JetBrains/Exposed/commit/ff3ed717ad4c13e47f4ea12ecdd1a747c1003887), `CaseWhenElse` was changed to extend `ExpressionWithColumnType<R>` instead. In spite of this, the return type of `Else()` did not change:
This means that a case instantiated using the constructor of `CaseWhenElse` is not interchangeable with an identical case instantiated using the `Else` method of the `CaseWhen` class:
```kt
// for example, …
```
=> fix: EXPOSED-54 CaseWhen.Else returns narrow Expression<R>

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/H2.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Mysql.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLServerDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLiteDialect.kt, exposed-java-time/api/exposed-java-time.api, exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/javatime/JavaDateColumnType.kt, exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/javatime/JavaDateFunctions.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/DefaultsTest.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/JavaTimeTests.kt, exposed-jodatime/api/exposed-jodatime.api, exposed-jodatime/src/main/kotlin/org/jetbrains/exposed/sql/jodatime/DateColumnType.kt, exposed-jodatime/src/main/kotlin/org/jetbrains/exposed/sql/jodatime/DateFunctions.kt, exposed-jodatime/src/test/kotlin/org/jetbrains/exposed/JodaTimeDefaultsTest.kt, exposed-jodatime/src/test/kotlin/org/jetbrains/exposed/JodaTimeTests.kt, exposed-kotlin-datetime/api/exposed-kotlin-datetime.api, exposed-kotlin-datetime/src/main/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinDateColumnType.kt, exposed-kotlin-datetime/src/main/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinDateFunctions.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/DefaultsTest.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinTimeTests.kt
The data type **timestamp with time zone** is supported by the following databases:
- [H2](http://www.h2database.com/html/datatypes.html#timestamp_with_time_zone_type)
- [Oracle](https://www.oracletutorial.com/oracle-basics/oracle-timestamp-with-time-zone/)
- [SQLite](https://www.sqlite.org/lang_datefunc.html#:~:text=Formats%202%20through%2010%20may%20be%20optionally%20followed%20by%20a%20timezone%20indicator%20of%20the%20form%20%22%5B%2B%2D%5DHH%3AMM%22%20or%20just%20%22Z%22.)
- [SQL Server](https://www.sqlservertutorial.net/sql-server-basics/sql-server-datetimeoffset/)
- [PostgreSQL (converted to UTC when stored, without preserving time zone info)](https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-timestamp/#:~:text=It%E2%80%99s%20important%20to%20note%20that%20timestampt …
=> feat: EXPOSED-43 Add support for timestamp with time zone

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SchemaUtils.kt, exposed-jodatime/src/test/kotlin/org/jetbrains/exposed/JodaTimeDefaultsTest.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/DefaultsTest.kt
The following test fails in `exposed-javatime` and `exposed-kotlin-datetime` modules (**Note** it was missing from `exposed-jodatime` module and has now been included):
**DefaultTests/testConsistentSchemeWithFunctionAsDefaultExpression()**
The test fails because an existing and unchanged datetime column with a database default is marked as modified, triggering an unnecessary ALTER statement. This is because the metadata value returned in `addMissingColumnsStatements()` does not match the returned value of `dbDefaultToString()`:
- [SQL Server maps](https://learn.microsoft.com/en-us/sql/t-sql/functions/current-timestamp-transact-sql?view=sql-server-ver16) both CURRENT_TIMESTAMP and GETDATE() to the ANSI standard equivalent, getdate.
- MariaDB returns CURRENT_TIMESTAMP(6) correctly, but in …
=> fix: EXPOSED-99 SchemaUtils incorrectly compares datetime defaults

exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateTableTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/functions/FunctionsTests.kt
The following tests in `exposed-tests` module fail when run using Oracle:
**FunctionsTests/testLocate03()**
- Oracle substring search is also case sensitive. The list of case sensitive DB became longer so it was more concise to create a condition for non-case sensitive DB and swap the test cases.
**DDLTests/createTableWithForeignKeyToAnotherSchema()**
- SQL statement used in `exec()` is terminated with a semi-colon and also does not provide the required privileges to reference tables across different schema, so the GRANT statement was altered.
**CreateTableTests/createTableWithQuotes()**
- Throws error `ORA-01741: illegal zero-length identifier` because Oracle does not tolerate a quoted table identifier in a sequence name: `CREATE SEQUENCE ""Parent"_id_seq" START WITH...` Oracle has been …
=> test: Fix failing exposed-tests in Oracle

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/UnsignedColumnTypeTests.kt
**Current State** of `UShortColumnType` (excluding MySQL/MariaDB):
When attempting to insert a `UShort` value outside of the range `0..32767`, Exposed first truncates the value by calling `value.toShort()` before sending it to the DB:
```kt
object UShortTable : Table("ushort_table") {
val unsignedShort = ushort("ushort")
}
transaction {
UShortTable.insert { it[unsignedShort] = 49151u }  // compiles OK because it is a valid UShort
// but generates SQL:
// INSERT INTO ushort_table (uShort) VALUES (-16385)
}
```
The value is successfully stored as a negative number because most databases don't support unsigned types natively, which means Exposed is actually mapping UShort to 2-byte `SMALLINT`, which accepts the range `-32768..32767`. The value returned from the DB is the negative overflow …
=> fix: EXPOSED-82 Inaccurate UShort column type mapping

exposed-java-time/src/test/kotlin/org/jetbrains/exposed/JavaTimeTests.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinTimeTests.kt
The following tests in `exposed-java-time` and `exposed-kotlin-datetime` fail when run using MariaDB:
**KotlinTimeTests/'test string LocalDateTime with nanos'()
JavaTimeTests/'test string LocalDateTime with nanos'()**
- Fails with the message `Failed on microseconds` because Exposed's datetime assertion functions for the fractional part are using `roundToMicro()` to compare nanoseconds. In most other DB, including MySQL, the nanoseconds retrieved from the DB is round to match the internal precision using `RoundingMode.HALF_UP`.
- This doesn't work because MariaDB always rounds down. For example, if a `LocalDateTime` with 815_716_723 (nanoseconds) is sent to the DB, the value retrieved from the DB is 815_716_000, not 815_717_000 as the tests expect.
- These tests are also flaky because …
=> test: Fix failing datetime tests in MariaDB

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLServerDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/UnsignedColumnTypeTests.kt
Related to [PR #1799](https://github.com/JetBrains/Exposed/pull/1799)
**Current State** of `UByteColumnType` (excluding MySQL/MariaDB):
When attempting to insert a UByte value outside of the range `0..127`, Exposed first truncates the value by calling `value.toByte()` before sending it to the DB:
```kt
object UByteTable : Table("ubyte_table") {
val unsignedByte = ubyte("ubyte")
}
transaction {
UByteTable.insert { it[unsignedByte] = 191u }  // compiles OK because it is a UByte
// but generates SQL:
// INSERT INTO ubyte_table (ubyte) VALUES (-65)
}
```
The value is successfully stored as a negative number because most databases don't support unsigned types natively, which means Exposed is actually mapping UByte to 1-byte `TINYINT`, which accepts the range `-128..127`. The value returned …
=> fix: EXPOSED-107 Inaccurate UByte column type mapping

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateDatabaseTest.kt
The following test fails when run locally with Oracle:
**CreateDatabaseTest/'create database test'()**
The first failure `ORA-01501: CREATE DATABASE failed, ORA-01100: database already mounted` occurs because the create statement is executed while a database already exists. This occurs because the `dropDatabase()` statement executed in the try block fails as the [syntax is not correct](https://docs.oracle.com/en/database/oracle/oracle-database/18/sqlrf/DROP-DATABASE.html#GUID-4FFC1AF5-538D-4882-8979-7A9957492A23).
Once the syntax is fixed, the test still fails with error `ORA-65040: operation not allowed from within a pluggable database` because certain operations, including dropping the DB, need to be performed only at the root container level.
Attempting to fix this with `exec("ALTER …
=> fix: Inaccurate drop database statement in Oracle

exposed-java-time/src/test/kotlin/org/jetbrains/exposed/JavaTimeTests.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/MiscTableTest.kt, exposed-jodatime/src/test/kotlin/org/jetbrains/exposed/JodaTimeTests.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinTimeTests.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/MiscTableTest.kt
The following tests in `exposed-java-time` and `exposed-kotlin-datetime` fail when run using Oracle:
**MiscTableTest/testSelect01()**
**MiscTableTest/testSelect02()**
Fails with an internal equality comparison issue due to precision, which returns an empty collection when `single()` is called.
The `datetime()` column maps to `TIMESTAMP` without specifying a precision, so the DB defaults to a length of 6 digits, and the value is round up internally instead of being truncated.
For example, if the value "2023-07-31 13:00:21.871130789" is inserted, the value stored is `2023-07-31T13:00:21.871131`. This causes an issue in the WHERE clause when the literal comparison value `'2023-07-31 13:00:21.871'` is used.
Explicitly casting the datetime literal in the WHERE clause causes the appropriate …
=> test: Fix failing datetime comparison tests in Oracle

exposed-bom/README.md, exposed-spring-boot-starter/README.md, samples/exposed-ktor/gradle.properties
Bumped to Exposed 0.42.0 version in:
- spring-boot-starter README.md
- samples/exposed-ktor
- exposed-bom
Fixed failing sample build
=> chore: Bump Exposed version to 0.42.0 in spring-boot-starter, samples, and BOM

documentation-website/Writerside/hi.tree, documentation-website/Writerside/topics/Data-Types.md, documentation-website/Writerside/topics/Deep-Dive-into-DAO.md, documentation-website/Writerside/topics/Deep-Dive-into-DSL.md, documentation-website/Writerside/topics/Frequently-Asked-Questions.md, documentation-website/Writerside/topics/Functions.md, documentation-website/Writerside/topics/Modules-Documentation.md, documentation-website/Writerside/topics/Schemas.md, documentation-website/Writerside/topics/Table-Definition.md
Edit docs to be in sync with the updated Wiki pages after the release of version 0.42.0:
- Add new subsections in: Deep Dive into DAO, Deep Dive into DSL
- Edit FAQ and Modules pages
- Add Schemas section to tree with the subsections: Table Definition, Data Types, and Functions
- matches the new documentation structure and allows addition of new feature sections
=> docs: Update pages with new version documentation

README.md, documentation-website/Writerside/topics/Getting-Started.md, documentation-website/Writerside/topics/Modules-Documentation.md
- Added Maven coordinates to README.md
- Modified the same info in the documentation
=> chore: Add Maven coordinates in README.md

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Constraints.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/InsertTests.kt
Currently, all databases can have column check constraints included when a table is created, but MySQL is prevented from producing create/drop statements for its check constraints. This makes sense  for older MySQL versions that simply parsed and ignored any CHECK constraint in the CREATE TABLE statement.
As of [version 8.0.16](https://dev.mysql.com/doc/refman/8.0/en/create-table-check-constraints.html), MySQL fully supports check constraints, so this limitation is now removed.
The new unit test confirmed that SQLite also [does not allow](https://www.sqlite.org/lang_altertable.html) its constraints to be created/dropped outside of a CREATE TABLE statement, so it has been included to log a warning and prevent alters.
Additional:
- 2 tests with check constraints that don't actually test the …
=> fix: EXPOSED-111 Allow check constraint statements in MySQL8

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/H2.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/UpsertTests.kt
Using a UUID column as a key `id` constraint in H2's `MERGE INTO .. USING` statement fails with:
```
org.h2.jdbc.JdbcSQLDataException:
Data conversion error converting "U&'\\fffdK\\fffdS\\001bJr\\fffdG%\\fffdE\\00100\\fffd' (TESTER: ""ID"" UUID NOT NULL)";
```
This error occurs because the statement uses a derived column list to merge `ON (T.ID=S.ID)`, so the UUID as a `ByteArray` stored in T.ID needs to be converted internally to compare with the `String` in S.ID (from generated SQL). This error goes away if a regular integer `id` column is used or if the key constraint is swapped with another non-UUID type.
The error also goes away if an identical MERGE statement is placed in `exec()` directly, indicating that the issue lies with how Exposed sends UUID values to the H2 database. …
=> fix: EXPOSED-116 UUID conversion error with upsert in H2

exposed-java-time/api/exposed-java-time.api, exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/javatime/JavaDateFunctions.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/DefaultsTest.kt, exposed-kotlin-datetime/api/exposed-kotlin-datetime.api, exposed-kotlin-datetime/src/main/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinDateFunctions.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/DefaultsTest.kt
If a `timestamp()` or `datetime()` column is created with `CurrentTimestamp()` as the default expression, verifying the table using `addMissingColumnsStatements()` incorrectly generates an alter column statement.
This is because `CurrentTimestamp()` extends `Expression<T>`, so it is [not caught by](https://github.com/JetBrains/Exposed/blob/main/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt#L136) `processForDefaultValue()` and retains parentheses. This results in a comparison mismatch, e.g. in PostgreSQL, between `CURRENT_TIMESTAMP` (from metadata) and `(CURRENT_TIMESTAMP)` (from Exposed).
This issue was partially fixed by [PR #1642 ](https://github.com/JetBrains/Exposed/pull/1642), but `CurrentTimestamp()` was not covered because it does not extend `Function` …
=> fix: EXPOSED-112 SchemaUtils fails to compare default CURRENT_TIMESTAMP

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/UpdateStatement.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/UpdateTests.kt
The following test fails when run on Oracle:
**UpdateTests/testUpdateWithJoinAndWhere()**
Fails with an assertion error because the arguments passed to `PreparedStatement` are in the wrong positions:
```kt
// generated SQL
UPDATE
(SELECT TEST_TABLE_B.BAR c0 FROM TEST_TABLE_A INNER JOIN TEST_TABLE_B
ON TEST_TABLE_A.ID = TEST_TABLE_B.TABLE_A_ID
WHERE TEST_TABLE_A.FOO = 'baz') x
SET c0='foo'
// expected SQL
UPDATE
(SELECT TEST_TABLE_B.BAR c0 FROM TEST_TABLE_A INNER JOIN TEST_TABLE_B
ON TEST_TABLE_A.ID = TEST_TABLE_B.TABLE_A_ID
WHERE TEST_TABLE_A.FOO = 'foo') x
SET c0='baz'
```
This happens because Oracle is the only supported database to use a subquery directly in the UPDATE syntax to represent the join part and the WHERE clause together:
```kt
val subQuery = …
```
=> fix: EXPOSED-128 Update with Join and Where clause fails in Oracle

exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcDatabaseMetadataImpl.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateIndexTests.kt
The following test fails when run on Oracle:
**CreateIndexTests/'test possibility to create indexes when table exists in different schemas'()**
Fails with:
```
ORA-01430: column being added already exists in table
Statement: ALTER TABLE TEST_TABLE ADD ID NUMBER(12) NOT NULL
```
This happens because metadata incorrectly returns an empty map of existing table columns when `columns()` is invoked in `JdbcDatabaseMetadataImpl`:
```kt
override fun columns(vararg tables: Table): Map<Table, List<ColumnMetadata>> {
val rs = metadata.getColumns(databaseName, currentScheme, "%", "%")
val result = rs.extractColumns(tables) { // .. }
}
```
`metadata.getColumns()` relies on the property `currentScheme`, which is invariably set to `databaseName` in Oracle; that means, it is set to the default user …
=> fix: EXPOSED-135 Oracle does not use setSchema value as currentScheme

exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/javatime/JavaDateColumnType.kt, exposed-jodatime/src/main/kotlin/org/jetbrains/exposed/sql/jodatime/DateColumnType.kt, exposed-kotlin-datetime/src/main/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinDateColumnType.kt
The following test fails when run on Oracle in the 3 modules: `exposed-kotlin-datetime`, `exposed-java-time`, `exposed-jodatime`
**DefaultsTest/testTimestampWithTimeZoneDefaults()**
The following tests also fail when run on Oracle, but in `exposed-jodatime` only:
**JodaTimeBaseTest/testTimestampWithTimeZone()**
**JodaTimeMiscTableTest/testTimestampWithTimeZone()**
**Issue 1:**
Fails with: `ORA-01861: literal does not match format string`
Because Oracle is set to use the default formatter, instead of [the accepted pattern](https://docs.oracle.com/en/database/oracle/oracle-database/21/nlspg/datetime-data-types-and-time-zone-support.html#GUID-5BC5D2C1-6506-49BE-8177-F743A46FDC09):
```
Current -> TIMESTAMP '2023-08-09T11:26:32.7367231Z'
Accepted -> TIMESTAMP '2023-08-09 11:26:32.7367231 …
```
=> fix: EXPOSED-122 Fix timestampWithTimeZone tests in Oracle

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Constraints.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateTableTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/sqlite/ForeignKeyConstraintTests.kt
The following test fails when run on Oracle:
**sqlite/ForeignKeyConstraintTests/'test ON DELETE SET DEFAULT for databases that support it without SQLite'()**
Fails with:
```
java.sql.SQLException: ORA-03001: unimplemented feature.
Statement(s):
CREATE TABLE ITEM (ID NUMBER(12) PRIMARY KEY, "NAME" VARCHAR2(20 CHAR) NOT NULL, CATEGORYID NUMBER(12) DEFAULT 0 NOT NULL,
CONSTRAINT FK_ITEM_CATEGORYID__ID FOREIGN KEY (CATEGORYID) REFERENCES CATEGORY(ID) ON DELETE SET DEFAULT)
```
Oracle's ON DELETE clause only supports CASCADE or SET NULL reference options ([documentation](https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/constraint.html#GUID-1055EA97-BA6F-4764-A15F-1024FD5B6DFE__CJAIHHGC)).
A warning is now logged instead of appending to the query string and Oracle is excluded …
=> fix: EXPOSED-137 SET DEFAULT reference option should not be supported in Oracle

exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateMissingTablesAndColumnsTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityTests.kt
The following tests fail when run on Oracle:
**CreateMissingTablesAndColumnsTests/testCamelCaseForeignKeyCreation()**
Fails with:
```
ORA-02275: such a referential constraint already exists in the table.
Statement(s): ALTER TABLE RECEIPTS ADD CONSTRAINT FK_RECEIPTS_TRACENUMBER__TRACENUMBER FOREIGN KEY (TRACENUMBER) REFERENCES TMPORDERS(TRACENUMBER)
```
This happens because Oracle metadata (via `getImportedKeys()`) only returns foreign keys that reference primary keys of the referenced table ([documentation](https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html#getImportedKeys-java.lang.String-java.lang.String-java.lang.String-)), so an empty map is being retrieved, which triggers an unnecessary alter statement.
This test passes in other DB as their metadata seems to be …
=> test: Fix failing Oracle tests in exposed-tests

buildSrc/src/main/kotlin/org/jetbrains/exposed/gradle/DBTestingPlugin.kt
Update registered Gradle tasks in `DBTestingPlugin`:
- Add a new task that delegates to both PostgreSQL tasks: `postgresAll`
- Add a new task that covers most databases, at least the latest versions: `testPartial`
- Change Gradle verification task `test` so that it includes all supported databases.
Open to any naming or list element suggestions.
**Before:**
**After:**
=> chore: EXPOSED-104 Update gradle test tasks

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Column.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLServerDialect.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/DefaultsTest.kt, exposed-jodatime/src/test/kotlin/org/jetbrains/exposed/JodaTimeDefaultsTest.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/DefaultsTest.kt, exposed-tests/src/main/kotlin/org/jetbrains/exposed/sql/tests/TestUtils.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateMissingTablesAndColumnsTests.kt
When creating a column with a DEFAULT value in SQL Server, a DEFAULT constraint is created under the hood. To modify the default value of a column, the constraint has to be dropped first. To do that, the name of the constraint is needed. To be able to obtain its name easily, the way the DEFAULT constraint is created was modified to give it an explicit name with the format `DF_TableName_ColumnName`. So when adding a new DEFAULT value to a column or modifying an existing one, it's necessary to drop the existing DEFAULT constraint first (if it exists), and then add a new one.
Every alter statement will be a separate item in the list returned by the `modifyColumn` function. The statement to alter the default value of a column will combine both the DROP CONSTRAINT and ADD CONSTRAINT statements …
=> feat: EXPOSED-85 Add support for changing default value in SQL Server

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SchemaUtils.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Mysql.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-json/api/exposed-json.api, exposed-json/src/main/kotlin/org/jetbrains/exposed/sql/json/JsonBColumnType.kt, exposed-json/src/main/kotlin/org/jetbrains/exposed/sql/json/JsonColumnType.kt, exposed-json/src/test/kotlin/org/jetbrains/exposed/sql/json/JsonBColumnTests.kt, exposed-json/src/test/kotlin/org/jetbrains/exposed/sql/json/JsonColumnTests.kt
Assigning a default value to a JSON/JSONB column using `default()` results in syntax exceptions in all databases except H2 because the current `nonNullValueToString()` result is an unquoted JSON string literal.
**Step 1:**
Extend both JSON column types with a new marker interface, `IJsonColumnType`, to act as a bridge to the `exposed-core` module (like what is done for date/time columns with `IDateColumnType`).
**Step 2:**
Override `processForDefaultValue()` to appropriately wrap the defaults according to database specifics:
- MySQL only allows default values on JSON columns if they are wrapped like an expression and the version is 8.0+:
> The BLOB, TEXT, GEOMETRY, and JSON data types can be assigned a default value only if the value is written as an expression, even if the expression …
=> fix: EXPOSED-127 Default values for JSON columns are not quoted

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateTableTests.kt
When a table with an auto-increment column is created in Oracle, a sequence must be created first.
If the provided table name has escaped double quotes, this CREATE SEQUENCE statement throws a syntax error:
```kt
object Parent : LongIdTable("\"Parent\"") {}
// java.sql.SQLSyntaxErrorException: ORA-01741: illegal zero-length identifier
// Statement(s): CREATE SEQUENCE ""Parent"_id_seq" START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807
```
In the case of all the `IdTable` subclasses, this happens because `autoincrement()` on the id column is not being provided a custom name, so the `fallbackSeqName` string is being used. This string now removes double quotes from a table name.
**Note:**
Oracle (and H2 Oracle) are the only DB that rely on `fallbackSeqName` as they are the only supported …
=> fix: EXPOSED-145 Quoted table name breaks CREATE SEQUENCE in Oracle

exposed-json/api/exposed-json.api, exposed-json/src/main/kotlin/org/jetbrains/exposed/sql/json/JsonColumnType.kt, exposed-json/src/test/kotlin/org/jetbrains/exposed/sql/json/JsonBColumnTests.kt, exposed-json/src/test/kotlin/org/jetbrains/exposed/sql/json/JsonColumnTests.kt
When a JSON/JSONB column that takes a `List` or `ListSerializer` is created, it correctly deserializes/serializes the JSON array to and from the database. However, attempting to log any SQL statements with the collection as a String throws a `ClassCastException`.
If the column is created to take an `Array` or `ArraySerializer` instead, then no exception is thrown when the logger is used.
This happens because lists are processed by `ColumnType.valueToString()` as `ArrayList`, which extends the `Iterable` superclass and is handled separately:
```kt
fun valueToString(value: Any?): String = when (value) {
null -> {
check(nullable) { "NULL in non-nullable column" }
"NULL"
}
DefaultValueMarker -> "DEFAULT"
is Iterable<*> -> value.joinToString(",", transform = ::valueToString)
else -> …
```
=> fix: EXPOSED-130 Logger throws ClassCastException with JSON and ListSerializer

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/transactions/experimental/Suspended.kt, exposed-tests/build.gradle.kts, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/h2/ConnectionPoolTests.kt
If the `maximumPoolSize` of a `HikariDataSource` is exceeded, any active connections made through `newSuspendedTransaction()` are not released back into the pool after job completion. This leads to a connection timeout exception when attempting to get more connections.
`resetIfClosed()`, invoked in `suspendedTransactionAsyncInternal()`, calls `getConnection()` to check if a transaction is closed (may happen after a repetition attempt fails), so that it can be properly reset for another attempt. This blocks the connections being released.
The function was introduced in [PR #1774 ](https://github.com/JetBrains/Exposed/pull/1774) and should not be necessary for the first loop, as the transaction is created with an open connection.
Now `resetIfClosed()` is only called on subsequent repetition …
=> fix: EXPOSED-133 Suspend transactions blocking Hikari connection pool

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Column.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SchemaUtils.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcDatabaseMetadataImpl.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateMissingTablesAndColumnsTests.kt
If a table object is created with user-quoted table and/or column names, attempting to validate it using either `SchemaUtils.createMissingTablesAndColumns()` or `SchemaUtils.statementsRequiredToActualizeScheme()` incorrectly generates CREATE and ALTER statements.
This happens because metadata returned by the database does not generally include quotes.
So any comparison check with the cached identifiers (which do include quotes) in `Table.exists()` or `SchemaUtils` functions causes false negative results.
Table and column functions that process/unquote the respective names are introduced to ensure a more accurate equality check with metadata.
=> fix: EXPOSED-151 Quoted identifiers cause incorrect schema validation

detekt/detekt-config.yml, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ResultRow.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLServerDialect.kt, exposed-tests/build.gradle.kts, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/JoinTests.kt
This [warning](https://github.com/JetBrains/Exposed/issues/1683) was first eliminated [here](https://github.com/JetBrains/Exposed/pull/541/files). Then it was accidentally introduced again [here](https://github.com/JetBrains/Exposed/commit/77f11a99adf18e7b0db863b58c68d2d9ab8cd1ff) because of the change made to the `getOrNull` function.
- To fix this, I moved the logic in the `get` function to a new function, `getInternal`, that has a Boolean parameter `checkNullability` which it uses to decide to whether or not to check for the column's nullability and log a warning.
- A new test dependency was added ([io.github.hakky54:logcaptor](https://github.com/Hakky54/log-captor)) to assert that no logging took place.
=> fix: Remove false warning log

documentation-website/Writerside/topics/Deep-Dive-into-DAO.md, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityClass.kt
Add KDocs with test samples to `EntityClass` infix reference functions.
Edit docs to match [updated Wiki](https://github.com/JetBrains/Exposed/wiki/DAO#many-to-one-reference).
=> docs: EXPOSED-159 Add KDocs for EntityClass reference functions

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Function.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/DefaultsTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/ConditionsTests.kt
`toQueryBuilder` of `CaseWhenElse` doesn't write a space before `WHEN`
and the second and subsequent `WHEN` s are concatenated with the previous terms,
resulting in syntax error when the previous ones are, e.g.,  `END` of the nested `CASE` as concatenated `ENDWHEN`.
So fixed it back with the preceding space.
=> fix: EXPOSED-158 avoid SQL syntax error of CASE WHEN using nested CASE

README.md, docs/ChangeLog.md, documentation-website/Writerside/topics/Getting-Started.md, documentation-website/Writerside/topics/Modules-Documentation.md, exposed-bom/README.md, exposed-spring-boot-starter/README.md, gradle.properties, samples/exposed-ktor/gradle.properties
To be merged when the release is available on Maven.
=> chore: Bump Exposed version from 0.42.1 to 0.43.0, and add 0.43.0 changes to ChangeLog.md

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Constraints.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Mysql.kt, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcDatabaseMetadataImpl.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateMissingTablesAndColumnsTests.kt
=> Fix how changes are calculated for non-default schema table

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SchemaUtils.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateMissingTablesAndColumnsTests.kt
This PR fixes https://github.com/JetBrains/Exposed/issues/1643
=> fix: Fix tables creation depending on each other via foreignKey constraint

exposed-tests/src/test/resources/logback-test.xml
@joc-a I made an attempt to resolve the verbose logging. Which you also attempted to resolve in https://github.com/JetBrains/Exposed/pull/1849 I was not sure whether it is fully resolved. Can you maybe have a look at it? And what do you think of the changes? I just converted the XML configuration file with one that logback is able to understand. Logback is being used internally by logcaptor. Looking forward to your feedback
=> fix: Verbose logging in test module

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SchemaUtils.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLServerDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/SchemaTests.kt
When `SchemaUtils.dropSchema(schema, cascade = true)` is used with SQL Server it fails with the error:
```
Incorrect syntax near the keyword 'CASCADE'..
Statement(s): DROP SCHEMA TEST_SCHEMA CASCADE
```
[Documentation](https://learn.microsoft.com/en-us/sql/t-sql/statements/drop-schema-transact-sql?view=sql-server-2016) shows that CASCADE is not supported in this statement (from version 2016 upwards).
In fact, other uses of `dropSchema()` with cascade make sure to exclude SQL Server:
- [DatabaseTestsBase](https://github.com/JetBrains/Exposed/blob/main/exposed-tests/src/main/kotlin/org/jetbrains/exposed/sql/tests/DatabaseTestsBase.kt#L260)
- [CreateTableTests](https://github.com/JetBrains/Exposed/blob/main/exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateTableTe …
=> fix: EXPOSED-161 SQL Server syntax incorrectly allows CASCADE with dropSchema 

exposed-core/build.gradle.kts, exposed-crypt/build.gradle.kts, exposed-dao/build.gradle.kts, exposed-java-time/build.gradle.kts, exposed-jdbc/build.gradle.kts, exposed-jodatime/build.gradle.kts, exposed-json/build.gradle.kts, exposed-kotlin-datetime/build.gradle.kts, exposed-money/build.gradle.kts, exposed-spring-boot-starter/build.gradle.kts, exposed-tests/build.gradle.kts, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/functions/StatisticsFunctionTests.kt, spring-transaction/build.gradle.kts
Fix [EXPOSED-117](https://youtrack.jetbrains.com/issue/EXPOSED-117/Set-jvm-toolchain-target-to-8)
=> fix: EXPOSED-117 Set jvmToolchain to 8 for all modules

docs/ORACLE.md, docs/SQLServer.md
Change the naming according to new gradle tasks, docker images, and properties set up in the corresponding `compose` file
=> chore: Adjust test md files

buildSrc/src/main/kotlin/org/jetbrains/exposed/gradle/Versions.kt, exposed-jdbc/api/exposed-jdbc.api, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcConnectionImpl.kt, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcPreparedStatementImpl.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/functions/MathFunctionTests.kt
Support for getGeneratedKeys() was [dropped](https://github.com/xerial/sqlite-jdbc/releases/tag/3.43.0.0#:~:text=%F0%9F%9A%A8%20remove%20support%20for%20Statement%23getGeneratedKeys%3A%20getGeneratedKeys%20is%20not%20supported%20anymore%20(712a8a5)%2C%20closes%20%23329) in the sqlite jdbc version 3.43.0.0. This caused a SQLFeatureNotSupportedException when using this version with Exposed, so the [old implementation](https://github.com/xerial/sqlite-jdbc/commit/f18a5bfad6fd95bc47fa0a41849573addbc75e2b#:~:text=getGeneratedKeys%20%3D%20conn.prepareStatement(%22select%20last_insert_rowid()%3B%22)%3B) of getGeneratedKeys() was used to retain the previous behaviour.
=> fix: EXPOSED-162 SQLite generatedKeys exception

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Column.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/BaseBatchInsertStatement.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityTests.kt
This feature will enable marking a column as `databaseGenerated` to be able to omit setting it when inserting a new record without getting an error. The value for the column can be set with TRIGGER or DEFAULT, for example.
=> feat: EXPOSED-78 Support database-generated values for columns

buildSrc/src/main/kotlin/org/jetbrains/exposed/gradle/Versions.kt, exposed-spring-boot-starter/README.md, exposed-spring-boot-starter/build.gradle.kts, exposed-spring-boot-starter/src/main/kotlin/org/jetbrains/exposed/spring/autoconfigure/ExposedAutoConfiguration.kt, exposed-spring-boot-starter/src/main/resources/META-INF/spring.factories, exposed-spring-boot-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, exposed-spring-boot-starter/src/test/kotlin/org/jetbrains/exposed/spring/Application.kt, exposed-spring-boot-starter/src/test/kotlin/org/jetbrains/exposed/spring/autoconfigure/ExposedAutoConfigurationTest.kt, spring-transaction/build.gradle.kts
Some documentation for reference:
- Change in auto-configuration files ([Spring Boot 3 Migration Guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#auto-configuration-files))
- Change in test H2 version ([Spring Boot 3 Dependency](https://docs.spring.io/spring-boot/docs/3.0.x/reference/html/dependency-versions.html#appendix.dependency-versions))
- Recommended ways to exclude classes from auto-configuration ([Spring Boot Reference](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using.auto-configuration.disabling-specific))
- Testing auto-configuration using `ApplicationContextRunner` ([Spring Boot Reference](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.developing-auto-configuration.testing))
=> fix: EXPOSED-171 Switch from spring.factories to AutoConfiguration.imports (#1636)

exposed-spring-boot-starter/build.gradle.kts, spring-transaction/build.gradle.kts
Gradle plugin was recently upgraded to 8.3, so warnings of compile task target compatibility became errors.
Tasks `:spring-transaction:compileKotlin` and `:exposed-spring-boot-starter:compileKotlin` failed with the following:
> 'compileJava' task (current target is 17) and 'compileKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.
Consider using JVM toolchain:
Fixed by setting `compileKotlin` task to target jdk 17 in both modules.
=> build: Fix compileKotlin task target in Spring modules

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/UnsignedColumnTypeTests.kt
If multiple tables have the same unsigned column types with the same column names, creating these tables throws `JdbcSQLSyntaxErrorException` with a message like `Name already used by existing constraint`.
Affected databases: H2 (+ compatibility modes), SQL Server, Oracle.
To avoid these naming clashes, the name of the auto-generated check constraint for the unsigned column types now includes the table name in the prefix, with the original column type and name appended to it.
=> fix: EXPOSED-179 Unsigned column check constraint is not unique to table

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Column.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateMissingTablesAndColumnsTests.kt
Attempting to create the following table throws `com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near '.'`:
```kt
object ParentTable : IntIdTable("my_schema.parent_table") {
val column1 = varchar("column_1", 32).default("TEST")
}
// generated SQL
// CREATE TABLE my_schema.parent_table (
//       id INT IDENTITY(1,1) PRIMARY KEY,
//       column_1 VARCHAR(32) CONSTRAINT DF_my_schema.parent_table_column_1 DEFAULT 'TEST' NOT NULL
// ) 
```
When using SQL Server, a default column auto-generates a named-constraint for the default value using the full table name.
Using the table name without schema resolves this.
=> fix: EXPOSED-182 Schema name breaks Create Table with default column [SQLServer]

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Constraints.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Database.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/DatabaseDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/H2.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/MariaDBDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/MysqlDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLServerDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLiteDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateTableTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/sqlite/ForeignKeyConstraintTests.kt
The following exception is thrown because [SQLServer does not support RESTRICT reference option](https://www.sqlshack.com/commonly-used-sql-server-constraints-foreign-key-check-default): 
> com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near the keyword 'RESTRICT'.
----------------------------
The following exception is thrown because [Oracle does not have the RESTRICT reference option](https://docs.oracle.com/en/database/oracle/oracle-database/12.2/cncpt/data-integrity.html?source=%3Aex%3Apw%3A%3A%3Arc_emmk180529p00117%3Atp3q1m8_defddeob&source=%3Aex%3Apw%3A%3A%3Arc_emmk180529p00117%3Atp3q1m8_defddeob&source=%3Aex%3Apw%3A%3A%3Arc_emmk180529p00117%3Atp3q1m8_defddeob#GUID-FB419C3E-7C1E-4881-B77D-D09A57C741A6):
> java.sql.SQLSyntaxErrorException: ORA-00905: missing …
=> fix: Exception when using RESTRICT reference option

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/DatabaseConfig.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/api/IdentifierManagerApi.kt, exposed-money/src/test/kotlin/org/jetbrains/exposed/sql/money/MoneyTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ConnectionTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ThreadLocalManagerTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/LikeTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/SelectTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/BooleanColumnTypeTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/CharColumnType.kt
Currently, if [a reserved keyword](https://github.com/JetBrains/Exposed/blob/main/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Keywords.kt#L8) is used as a table or column name, Exposed first changes the case based on the proper database case, then quotes the name.
This means that a table object will create different-cased quoted identifiers in different databases, which is problematic when using migration scripts to enable use of a table object across databases:
```kt
object Tester : Table("Public") {
val col = integer("integer")
}
// PostgreSQL -> CREATE TABLE IF NOT EXISTS "public" ("integer" INT NOT NULL)
// H2         -> CREATE TABLE IF NOT EXISTS "PUBLIC" ("INTEGER" INT NOT NULL)
// MySQL      -> CREATE TABLE IF NOT EXISTS `Public` (`integer` INT NOT NULL)
```
This …
=> fix!: EXPOSED-150 Auto-quoted column names change case across databases

exposed-spring-boot-starter/README.md
Edit code blocks to show auto-configuration annotations.
Add links to spring boot sample project.
Add Gradle dsl dependency block.
=> docs: EXPOSED-132 Add annotations to spring-boot-starter README samples

exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcDatabaseMetadataImpl.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/sqlite/ForeignKeyConstraintTests.kt
Although the documentation of the driver mentions `UPDATE_RULE` [here](https://javadoc.io/static/com.oracle.database.jdbc/ojdbc8/12.2.0.1/oracle/jdbc/OracleDatabaseMetaData.html#getImportedKeys-java.lang.String-java.lang.String-java.lang.String-), it is missing from the `ALL_CONSTRAINTS` view [here](https://docs.oracle.com/en/database/oracle/oracle-database/12.2/refrn/ALL_CONSTRAINTS.html#GUID-9C96DA92-CFE0-4A3F-9061-C5ED17B43EFE). Only `DELETE_RULE` is mentioned.
This is part of the SQL that runs when `OracleDatabaseMetadata.getImportedKeys()` is invoked:
```
SELECT NULL AS pktable_cat,
p.owner as pktable_schem,
p.table_name as pktable_name,
pc.column_name as pkcolumn_name,
NULL as fktable_cat,
f.owner as fktable_schem,
f.table_name as fktable_name,
fc.column_name as fkcolumn_name, …
```
=> fix: EXPOSED-173 UPDATE_RULE read incorrectly for Oracle

spring-transaction/src/main/kotlin/org/jetbrains/exposed/spring/SpringTransactionManager.kt, spring-transaction/src/test/kotlin/org/jetbrains/exposed/spring/ConnectionSpy.kt, spring-transaction/src/test/kotlin/org/jetbrains/exposed/spring/ExposedTransactionManagerTest.kt, spring-transaction/src/test/kotlin/org/jetbrains/exposed/spring/SpringTransactionManagerTest.kt, spring-transaction/src/test/kotlin/org/jetbrains/exposed/spring/SpringTransactionTestBase.kt
Implemented the Propagation policy in SpringTransactionManager.
In addition to REQUIRED, we now support SUPPORTS, MANDATORY, REQUIRES_NEW, NOT_SUPPORTED, NEVER, and NESTED.
The changes are as follows
- NESTED is implemented to use the ThreadLocalTransactionManager's savepoint. So Spring's SavePointManager is not implemented.
- Implemented doSuspend and doResume methods for support, mandatory, etc. Saves the current transaction, changes the current TransactionManager to null, etc.
=> feat: EXPOSED-188 Support Propagation in SpringTransactionManager

exposed-jodatime/api/exposed-jodatime.api, exposed-jodatime/src/main/kotlin/org/jetbrains/exposed/sql/jodatime/DateColumnType.kt
Both column type classes in `exposed-jodatime` contain companion objects that check for `java.time` classes that were only introduced in JDK 1.8 (`LocalDateTime`, `OffsetDateTime`).
This was implemented because the module was expected to run on Java version 1.7 and to be compatible with legacy android versions.
Since the `jvmToolchain` has now been to set to 8, support for 1.7 is no longer needed and the classes can be referenced directly.
=> chore: EXPOSED-186 Replace JDK 1.7 support in exposed-jodatime classes

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Constraints.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/DatabaseDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcDatabaseMetadataImpl.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/sqlite/ForeignKeyConstraintTests.kt
Oracle returns CASCADE=0, SET_NULL=2, and NO_ACTION=1
`decode (f.delete_rule, 'CASCADE', 0, 'SET NULL', 2, 1) as delete_rule`
So when it returns 1, which in the current code corresponds to `DatabaseMetaData.importedKeyRestrict`, it is mapped to `RESTRICT`, which is not supported in Oracle. Instead of that, it will now be mapped to `NO_ACTION`.
The `resolveRefOptionFromJdbc` function was moved from `Constraints.kt` to `DatabaseDialect.kt`.
=> fix: EXPOSED-178 DELETE_RULE read incorrectly for Oracle

README.md, docs/BREAKING_CHANGES.md, docs/ChangeLog.md, documentation-website/Writerside/topics/Getting-Started.md, documentation-website/Writerside/topics/Modules-Documentation.md, exposed-bom/README.md, exposed-spring-boot-starter/README.md, gradle.properties, samples/exposed-ktor/gradle.properties, samples/exposed-spring/gradle.properties
Add 0.44.0 changes to ChangeLog.md
Add 0.44.0 breaking changes to BREAKING_CHANGES.md
=> chore: Bump Exposed version from 0.43.0 to 0.44.0

exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcPreparedStatementImpl.kt, exposed-tests/build.gradle.kts, exposed-tests/src/main/kotlin/org/jetbrains/exposed/sql/tests/DatabaseTestsBase.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/mysql/MysqlTests.kt
When rewriteBatchedStatements property is on mysql driver returns -2 as for each row returned by PreparedStatement.batchUpdate function. And when the whole array is summed up (https://github.com/JetBrains/Exposed/pull/1641) it results in negative value as nothing where inserted.
=> [MySQL] Fix bug when inserted ids are not returned if `rewriteBatchedStatements` property set to true

README.md
I just had an issue on my Java 8 Kotlin Project where it wouldn't find Exposed. After I switched from JBR 17 to Coretto 19 and some other steps I forgot by now (was trying random stuff to be honest) Gradle finally gave me an Error pointing at that issue in a build. Maven found it, but other parts of my project wouldn't work for some reason. 
This PR solely exists to save other people a couple of hours.
Error:
=> Version Notice for JVM

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Op.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SchemaUtils.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/StatementInterceptor.kt, exposed-dao/api/exposed-dao.api, exposed-java-time/api/exposed-java-time.api, exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/javatime/JavaDateFunctions.kt, exposed-jodatime/api/exposed-jodatime.api, exposed-jodatime/src/main/kotlin/org/jetbrains/exposed/sql/jodatime/DateFunctions.kt, exposed-kotlin-datetime/api/exposed-kotlin-datetime.api, exposed-kotlin-datetime/src/main/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinDateFunctions.kt
**Note:** All elements had most recent level change in release 0.42.0 (July 2023).
**Raise from ERROR to HIDDEN:**
- Op.kt classes: `LikeOp` and `NotLikeOp`
**Currently HIDDEN, now removed:**
- `CurrentDateTime` object's `invoke()` (in all 3 date-time modules)
- `StatementInterceptor` interface's `afterCommit()` and `afterRollback()`
- `SchemaUtils` object `createFKey()`
- SQLExpressionBuilder.kt: `Sequence.nextVal()` and `SqlExpressionBuilderClass`
=> deprecate: Raise deprecation levels of API elements

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/api/ExposedDatabaseMetadata.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/MysqlDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SchemaMetadata.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/VendorDialect.kt, exposed-jdbc/api/exposed-jdbc.api, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcDatabaseMetadataImpl.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/SchemaTests.kt
Raise deprecation level of `ExposedDatabaseMetadata.currentScheme` from WARNING to ERROR.
This property was initially deprecated after [this PR](https://github.com/JetBrains/Exposed/pull/815) introduced the possibility to change the schema in runtime.
The goal of this fix is to keep the property private in `JdbcDatabaseMetadataImpl`, which has 2 complications:
1. **`VendorDialect` functions use it to filter existing table names:**
- This is replaced by a new fun `tableNamesByCurrentSchema()`, which abstracts away the property from the core module. **Ideallly** this function should only return a `List<String>`, but it doesn't because of complication 2 (below).
2. **`VendorDialect.tableExists()` uses the property directly, as does 1 unit test:**
- So `tableNamesByCurrentSchema()` instead …
=> deprecate: Raise deprecation level of currentScheme property

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/api/IdentifierManagerApi.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/MysqlDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateTableTests.kt
When providing a table with a dot in its name, it's necessary to quote it so that the part before the dot is not treated as a schema name. If it is treated like a schema name, it fails to find that schema and throws an error. Adding quotes previously caused the name to be broken apart. The fix is to only break the name apart if is NOT already quoted.
**Old behaviour:**
Provided table name = "SomeNamespace.SomeTable"
Name in SQL statements = "SomeNamespace"."SomeTable"
**New behaviour:**
Provided table name = "SomeNamespace.SomeTable"
Name in SQL statements = "SomeNamespace.SomeTable"
Oracle is excluded from this fix because it throws this error:
> java.sql.SQLSyntaxErrorException: ORA-04043: object "SOMENAMESPACE.SOMETABLE" does not exist
A problem with casing for table names is suspected …
=> fix: Incorrect SQL statements when creating a table with a dot in its name

buildSrc/src/main/kotlin/org/jetbrains/exposed/gradle/Versions.kt, exposed-tests/src/main/kotlin/org/jetbrains/exposed/sql/tests/TestDB.kt
Every MySQL test shows the following log when run:
[Change notes](https://dev.mysql.com/doc/connector-j/8.1/en/connector-j-api-changes.html) confirm that the driver class name used in `exposed-tests` is deprecated.
The MySQL version used for testing is also bumped to 8.0.33.
**Note:** Could bump to latest 8.1.0, but it is fairly recent (2023-07-18, GA) and would require a [dependency change](https://dev.mysql.com/doc/relnotes/connector-j/8.1/en/news-8-1-0.html) (new `groupId` and `artifactId`) and refactoring of 1 unit test.
**Note:** I don't foresee complications, but please consider running MySQL tests locally to check that the new driver doesn't cause any issues.
=> test: Change MySQL connector Driver class name and version

exposed-spring-boot-starter/README.md
Add sub-section about how to configure other transaction managers alongside Exposed.
Add section about how to log SQL statements in Spring Boot app.
=> docs: EXPOSED-199 Update configuration section in spring-boot-starter README

exposed-java-time/api/exposed-java-time.api, exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/javatime/JavaDateColumnType.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/JavaTimeTests.kt, exposed-jodatime/src/main/kotlin/org/jetbrains/exposed/sql/jodatime/DateColumnType.kt, exposed-jodatime/src/test/kotlin/org/jetbrains/exposed/JodaTimeDefaultsTest.kt, exposed-kotlin-datetime/api/exposed-kotlin-datetime.api, exposed-kotlin-datetime/src/main/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinDateColumnType.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinTimeTests.kt
- For H2, the type of the value returned from the database for CurrentDateTime function is OffsetDateTime, which was not being handled correctly in `valueFromDB` function.
- For Oracle, the type of the value returned from the database for CurrentDateTime function is oracle.sql.TIMESTAMPTZ, which was not being handled correctly in `valueFromDB` function. The fix for this is to call `rs.getObject(index, java.sql.Timestamp::class.java)` in readObject, which then results in the type being java.sql.Timestamp which is already handled properly in `valueFromDB` function.
=> fix: Parsing failure when selecting CURRENT_TIMESTAMP using CurrentDateTime function

exposed-java-time/src/test/kotlin/org/jetbrains/exposed/DefaultsTest.kt, exposed-jodatime/src/test/kotlin/org/jetbrains/exposed/JodaTimeDefaultsTest.kt, exposed-jodatime/src/test/kotlin/org/jetbrains/exposed/JodaTimeTests.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/DefaultsTest.kt, exposed-tests/src/main/kotlin/org/jetbrains/exposed/sql/tests/TestUtils.kt
- Move `testCurrentDateTimeFunction` from `JodaTimeDefaultsTest` to `JodaTimeTests`
- Rewrite `testDefaultCurrentDateTime` in `JodaTimeDefaultsTest`
- Add `testDefaultCurrentDateTime` to Java and Kotlin tests
=> test: Refactor time tests

build.gradle.kts, exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Transaction.kt, exposed-dao/api/exposed-dao.api, exposed-jdbc/api/exposed-jdbc.api, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcConnectionImpl.kt, exposed-json/src/test/kotlin/org/jetbrains/exposed/sql/json/JsonColumnTests.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/DefaultsTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/EnumerationTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/AdjustQueryTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/DeleteTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/InsertTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/ReplaceTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/UpdateTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityBugsRegressionTest.kt
`kotlinOptions.languageVersion` was set to 1.6, preventing the use of Kotlin 1.9 features, namely switching to `Enum.entries`.
Removing this tasks block allowed the switch and the following **deprecations** also had to be dealt with:
- Direct use of `toChar()`
- `Assert.assertThat()`
- `Duration` constructor using extension functions
=> chore: Remove build file kotlinOptions languageVersion

exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityClass.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityTests.kt
Previously, the following line in `EntityClass.kt` was causing a crash:
`findById(id)?.storeReferenceInCache(refColumn, it)`
`findById` was being invoked on `this`, which is the child entity, using `id` (from looping over `distinctRefIds`) which is for the parent entity. This causes a crash as reported [here](https://youtrack.jetbrains.com/issue/EXPOSED-93).
The fix is to find the child entity by using `refColumn`, which is the column in the child table that references the `id` in the parent table.
I suspect this bug was never detected because our tests did not cover the case where the parent would have a String id, so the auto-generated Int id happened to be the same for the child entities and they were found using `findById(id)`.
=> fix: EXPOSED-93 Error when using `with`

exposed-tests/build.gradle.kts, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/QueryTimeoutTest.kt, spring-transaction/src/main/kotlin/org/jetbrains/exposed/spring/SpringTransactionManager.kt, spring-transaction/src/test/kotlin/org/jetbrains/exposed/spring/ExposedTransactionManagerTest.kt, spring-transaction/src/test/kotlin/org/jetbrains/exposed/spring/SpringTransactionManagerTest.kt
related issue #1671 
Simply changed the Spring Transaction's timeout to apply. Change the implementation to use the timeout implemented in the previous PR.
The test code for SpringTransactionManager is not database-specific, so I think we need to implement a module like `withDB` in the exposed-test module to test the actual behaviour. So I'm going to change the existing SpringTransactionManagerTest to be more extensible, at which point I'll add a real DB test for queryTimeout.
I wonder if the tests included in this PR are sufficient for this feature to be deployed.
=> feat: EXPOSED-225 Support transaction timeout in SpringTransactionManager

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/transactions/ThreadLocalTransactionManager.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/transactions/TransactionApi.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/transactions/TransactionScope.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/transactions/experimental/Suspended.kt
Covers files in the `transactions` package in the `exposed-core` module.
All public API elements now show a KDoc when hovered over by a mouse in IDE or when _Quick Documentation_ shortcut is used (`F1 | Ctrl+Q`).
=> docs: Add missing KDocs for exposed-core transactions API

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Query.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/AdjustQueryTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/ConditionsTests.kt
Currently providing an empty list to `slice()` results in a SELECT statement without any columns defined, which returns syntax exceptions in all databases except PostgreSQL and H2 (these return empty results).
Adding a check to `Query.prepareSQL()` allows an early fail now.
=> fix: EXPOSED-227 Slice() with empty list creates invalid SQL

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/FunctionProvider.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLiteDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/UpsertTests.kt
If all columns in an `upsert()` block are conflict/key columns, and `onUpdate` is not set, an empty update clause is generated, which throws an SQLException in all databases except MySQL and MariaDB.
It is important to allow key columns in the update clause for databases that do not support `insertIgnore()` and must use upsert to achieve this functionality.
Including these key columns is valid SQL in all databases except Oracle, which throws `ORA-38104: Columns referenced in the ON Clause cannot be updated`.
So filtering the update columns now only happens if the result will not be an empty list.
=> fix: EXPOSED-226 Upsert fails with only key columns in update

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Queries.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Query.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SetOperations.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/Entity.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityClass.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/InnerTableLink.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/SelectBatchedTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/SelectTests.kt
**Before:**
```kt
1. TestTable.slice(TestTable.columnA).select { TestTable.columnA eq 1 }
2. TestTable.slice(TestTable.columnA).select(Op.TRUE)
3. TestTable.slice(TestTable.columnA).selectAll()
4. TestTable.select { TestTable.columnA eq 1 }
5. TestTable.select(Op.TRUE)
6. TestTable.selectAll()
7. TestTable.slice(TestTable.columnA).selectBatched(50) { TestTable.columnA eq 1 }
8. TestTable.slice(TestTable.columnA).selectAllBatched(50)
9. TestTable.selectBatched(50) { TestTable.columnA eq 1 }
10.TestTable.selectAllBatched(50)
11. val originalQuery = TestTable.select { TestTable.columnA eq 1 }
12. originalQuery.adjustSlice { slice(TestTable.columnA) }
```
**After:**
```kt
1. TestTable.select(TestTable.columnA).where { TestTable.columnA eq 1 }
2. …
```
=> feat: EXPOSED-65 Design query DSL consistent with SQL language

exposed-java-time/src/test/kotlin/org/jetbrains/exposed/sqlserver/SQLServerDefaultsTest.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/sqlserver/SQLServerDefaultsTest.kt, exposed-tests/build.gradle.kts, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ConnectionExceptions.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/AdjustQueryTests.kt, gradle/libs.versions.toml, spring-transaction/build.gradle.kts
Hamcrest dependency is only used in 4 tests in the entire codebase and all its usages can be replaced with less verbose and more clear `kotlin.test` assertions.
=> test: Remove hamcrest dependency usage

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Query.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SetOperations.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityClass.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/AdjustQueryTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/SelectTests.kt
As I was putting together the migration guide, it occurred to me that we're placing the responsibility on users to perform an extra step that could be avoided if the declaration of the new `adjustSelect()` is changed.
Since the new `select()` returns a `Query` instead of a `FieldSet`, users would need to access the query's `set` property to resolve type mismatch errors when migrating:
```kt
// before
originalQuery.adjustSlice { slice(TestTable.columnA) }
// after
originalQuery.adjustSelect { select(TestTable.columnA).set }
```
This would no longer be necessary by changing the return type of the `body` parameter in this PR:
```kt
originalQuery.adjustSelect { select(TestTable.columnA) }
```
The old `adjustSlice()` was recommended to be used with a `slice()` in the lambda, so majority of …
=> refactor: EXPOSED-65 Change function declaration of adjustSelect

buildSrc/src/main/kotlin/org/jetbrains/exposed/gradle/TestDbDsl.kt
Currently, both `spring-transaction` and `exposed-spring-boot-starter` modules are set up to not be database-specific, but to only test how Exposed generally integrates with Spring.
This means that all unit tests use an embedded H2 database and that these test classes do not extend `DatabaseTestsBase()` .
In spite of this, all Spring tests are run by every Gradle test task, resulting in multiple H2 duplicate tests when task `test` or TC build is run.
Duplicates can be confirmed by:
- Log `Transaction.db.vendor` or `Transaction.db.dialect` in any test while running a non-H2 test task:
- Output will always be "H2" or "H2Dialect"
- Execute any H2-incompatible SQL in a test:
- e.g. `exec("SELECT version();")` should work when included in any test run with `testPostgres`, but instead this is …
=> test: Drop duplicate Spring tests using non-H2 Gradle tasks

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnDiff.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Database.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/DatabaseConfig.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Exceptions.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLLog.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Schema.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SchemaUtils.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Transaction.kt
Add KDocs to `exposed-core` files relating to Database and Schema.
All public API elements now show a KDoc when hovered over by a mouse in IDE or when _Quick Documentation_ shortcut is used (`F1 | Ctrl+Q`).
=> docs: Add missing KDocs for exposed-core database API

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Alias.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Column.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/CompositeColumn.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Constraints.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Sequence.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/WindowFunction.kt
Add KDocs to `exposed-core` files relating to Table and Column.
All public API elements now show a KDoc when hovered over by a mouse in IDE or when _Quick Documentation_ shortcut is used (`F1 | Ctrl+Q`).
**The only module with missing KDocs is now `exposed-dao`.**
=> docs: Add missing KDocs for exposed-core table API

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Database.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/transactions/ThreadLocalTransactionManager.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/h2/ConnectionPoolTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/postgresql/ConnectionPoolTests.kt, spring-transaction/src/test/kotlin/org/jetbrains/exposed/spring/SpringTransactionManagerTest.kt
The lazy property initializer of a new database connection attempts to reset parameters (like transaction isolation level and read only mode), regardless of whether connections are being reused from a connection pool instance.
This can be observed, for example, when schema settings are placed in `HikariConfig`, which opens a database transaction leading to thrown exceptions when Exposed later attempts to reset parameters:
> org.postgresql.util.PSQLException: Cannot change transaction read-only property in the middle of a transaction.
This PR builds on the changes introduced in PR #1943 by also retrieving and caching the `readOnly` mode set by the `DataSource`and avoiding redundant resets.
**Note:** To ensure that these resets are avoided and that the `DataSource` is the single source of …
=> fix: EXPOSED-242 [PostgreSQL] Cannot change connection setting in middle of a transaction

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/DatabaseConfig.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/api/IdentifierManagerApi.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ConnectionTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt
The opt-in flag `preserveKeywordCasing` was introduced 3 versions ago (PR #1841 ).
This PR sets the goal behavior (that keywords retain user-defined casing before being quoted) to `true` by default.
The flag temporarily remains in the event that users want to opt-out of the now default behavior by setting it to `false`.
Tests have been refactored to account for new behavior.
=> chore!: EXPOSED-239 Set preserveKeywordCasing flag to true by default

README.md, docs/MIGRATION_GUIDE.md, documentation-website/Writerside/topics/Migration-Guide.md
The 2 docs are duplicates for now, but, in the future, the library doc could just hold a link to the live writerside page, like what's done in Ktor.
Includes new DSL changes in README.
=> docs: Add MIGRATION_GUIDE

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/CharColumnType.kt
Unlike all other dialects, PostgreSQL column COLLATE clause requires that the option is quoted as part of the column definition.
=> fix: EXPOSED-244 [PostgreSQL] Collate option on column not recognized

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Op.kt
Current KDocs are misleading for the actual behavior of `Op.TRUE` and `Op.FALSE` as they make it seem like the objects simply translate to the SQL types for `true` and `false`.
This is technically correct for databases that support conventional boolean data types, so the objects can be used either as a stand-alone operator or as the left- or right-hand side of any comparison operator.
But for SQL Server and Oracle, which do not support syntax like `WHERE 1` or `WHERE TRUE`, the object's logic returns an operator that always evaluates to a boolean, like `1 = 1`. So attempting to use these objects as the left- or right-hand side of any comparison operator will cause a syntax error. `booleanLiteral()` or `booleanParam()` should be used in these situations.
=> docs: [SQL Server, Oracle] Edit KDocs for Op.TRUE/FALSE

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ops/AllAnyOps.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ops/InTableOp.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/SelectTests.kt
- Add some missing KDocs for new objects
- Make `UntypedAndUnsizedArrayColumnType` internal (to be replaced by a dedicated `ArrayColumnType` in the future)
- Edit tests to reflect new DSL
=> chore: Add Kdocs and update DSL for AllAnyFromBaseOp feature

exposed-spring-boot-starter/README.md, exposed-spring-boot-starter/src/main/kotlin/org/jetbrains/exposed/spring/autoconfigure/ExposedAutoConfiguration.kt
Users of `exposed-spring-boot-starter` might not expect the starter to set certain configuration attributes to their Spring defaults because it is necessary for the inclusion and configuration of Exposed's `SpringTransactionManager`.
This provides a warning regarding the default attribute settings included when `@ExposedAutoConfiguration` is automatically configured, as well as options for how to adjust the default proxy target settings, if required.
=> docs: Add details about @EnableTransactionManagement to spring-boot-starter docs

README.md, docs/BREAKING_CHANGES.md, docs/ChangeLog.md, documentation-website/Writerside/topics/Getting-Started.md, documentation-website/Writerside/topics/Modules-Documentation.md, exposed-bom/README.md, exposed-spring-boot-starter/README.md, gradle.properties, samples/exposed-ktor/gradle.properties, samples/exposed-spring/gradle.properties
Update BREAKING_CHANGES and CHANGELOG files.
Wiki will be updated with new DSL changes as well.
=> chore: Bump Exposed version from 0.45.0 to 0.46.0

exposed-json/src/main/kotlin/org/jetbrains/exposed/sql/json/JsonConditions.kt, exposed-json/src/test/kotlin/org/jetbrains/exposed/sql/json/JsonColumnTests.kt
If a json column is declared as storing a list/set/array of values and one of these iterables is used with the function `contains()`, a syntax error exception is thrown.
The function now properly wraps the serialized json list with quotes when the SQL is generated.
=> fix: EXPOSED-252 Json contains() throws with iterable as argument

documentation-website/Writerside/topics/Deep-Dive-into-DAO.md, exposed-dao/api/exposed-dao.api, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityCache.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityClass.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityTests.kt
Currently there are no functions in the DAO api that directly allow updates. This change adds functions that allow direct updates in the EntityClass API. Usage guidelines are explained in the documentation updates.
=> feat: Add findByIdAndUpdate functions to DAO API

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/InsertStatement.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/UpsertStatement.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/UpsertTests.kt
Currently when using `upsert()` with a `where` argument, only column expressions and literal values are being handled correctly in the `PreparedStatement` SQL.
Attempting to use a value that should be parameterized (by using `param()` functions or primitive types) results in an exception stating that the provided parameter count is incorrect. 
This occurs because the `where` arguments are not correctly added to the list of statement arguments in the super class `InsertStatement`.
An `arguments()` override that includes these `where` arguments has now been added to the `UpsertStatement` class.
=> fix: EXPOSED-257 Upsert incorrectly parameterizes non-literal WHERE arguments

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Transaction.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/TransactionExecTests.kt
If the ResultSet contains no result, the user wants to return `null`. However, since `executeQuery()` returns a non-nullable ResultSet, the user is forced to return a non-null object, even if there is no result.
By allowing `transform` to return null, this is fixed.
=> fix: Allow exec() transform block to return null if ResultSet is empty

exposed-json/src/main/kotlin/org/jetbrains/exposed/sql/json/JsonColumnType.kt, exposed-json/src/test/kotlin/org/jetbrains/exposed/sql/json/JsonBColumnTests.kt, exposed-json/src/test/kotlin/org/jetbrains/exposed/sql/json/JsonColumnTests.kt
When using **H2**, attempting to insert `null` into a nullable JSON column results in an NPE that states: 
> null cannot be cast to non-null type kotlin.String
When using **PostgreSQL-NG**, attempting to retrieve a null value stored in a JSON column results in a deserialization error because a non-null object is read with string value `'null'`.
Both these issues occur because the `JsonColumnType` override for `setParameter()` does not handle null values correctly.
In the case of PostgreSQL-NG, this meant that a null value was being stored as a string literal instead of SQL NULL.
If null values are passed, the dialect overrides now ensure that they are sent to the super implementation so they can be handled as SQL NULL.
=> fix: EXPOSED-261 [H2] JSON column throws when setting nullable parameters

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/h2/H2Tests.kt
In case of avg aggregate functions for h2 db - it returns Short type and fail convert it to BigDecimal.
e.g. 
code example:
```kotlin
(FilmCategories innerJoin Films).slice(FilmCategories.category, FilmCategories.film.count(), Films.length.avg()).selectAll()
.groupBy(FilmCategories.category).forEach { row ->
println(
"Category: ${row[FilmCategories.category]}\n" +
"\tNumber of films: ${row[FilmCategories.film.count()]}\n" +
"\tAverage duration of films: ${row[Films.length.avg()]}",
)
}
```
SQL: 
```sql
SELECT FILM_CATEGORY.CATEGORY_ID, COUNT(FILM_CATEGORY.FILM_ID), AVG(FILM."LENGTH") FROM FILM_CATEGORY INNER JOIN FILM ON FILM.FILM_ID = FILM_CATEGORY.FILM_ID GROUP BY FILM_CATEGORY.CATEGORY_ID
```
Current error:
```
Exception in thread "main" java.lang.IllegalStateException: Unexpected …
```
=> fix: Support Short type for BigDecimal conversion functions

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ops/InListOps.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/SelectTests.kt
If a `Pair`/`Triple` is used with `inList()`/`notInList()` and the right-side list contains multiple elements, the SQL generated is:
```sql
WHERE (col1, col2) IN ((?, ?), (?, ?), ...)
```
If the right-side list only contains a single element, the SQL generated is:
```sql
WHERE (col1, col2) = (?, ?)
```
The latter works correctly for all supported databases except Oracle, which throws:
> java.sql.SQLSyntaxErrorException: ORA-00920: invalid relational operator
This fix ensures that the `IN` and `NOT IN` operators are always used with Oracle regardless of the number of list elements.
Existing tests that excluded Oracle for this reason have been adjusted.
=> fix: EXPOSED-260 [Oracle] Pair.inList() fails if list contains single element

spring-transaction/src/test/kotlin/org/jetbrains/exposed/spring/ExposedTransactionManagerTest.kt, spring-transaction/src/test/kotlin/org/jetbrains/exposed/spring/SpringTransactionSingleConnectionTest.kt, spring-transaction/src/test/kotlin/org/jetbrains/exposed/spring/SpringTransactionTestBase.kt
Sorry for the late PR!
Added some tests to test the isolation level of SpringTransactionManager.
1. Write test code in `SpringTransactionSingleConnectionTest` to check if the issue that when there is only one connection, the connection cannot be obtained unless the default isolation level is set is fixed in the latest version.
2. Add test code to check if the isolation level is set well in the existing test
Discussion
1. I have confirmed that the problem encountered in this issue is resolved in the current version. I wonder if additional isolation tests are needed?
2. The `readOnly` test was tested with a spy test to make sure the value is set correctly. Unfortunately, H2 does not seem to support readOnly properly, so I was unable to test it.
3. May spring test also need to test real …
=> test: EXPOSED-233 Add additional SpringTransactionManager isolation test

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Transaction.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ParameterizationTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/SequencesTests.kt
The type for `exec()` parameterized arguments is declared as `args: Iterable<Pair<IColumnType, Any?>>`, so passing `null` as the second element correctly sets the statement parameter to SQL NULL.
But if a logger is enabled, this exception is thrown instead:
> java.lang.IllegalStateException: NULL in non-nullable column.
This is because all `IColumnType` default to being not nullable and fail the check in `ColumnType.valueToString()` when attempting to parse the null parameter value.
This exception can be avoided by always providing SQL NULL directly, via `Op.nullOp<T>()`.
But given the type hints, the accepted parameter values should match what would be accepted by any other DSL statement.
Even if the column in the Exposed table object is declared as being `nullable()`, the column type in …
=> fix: EXPOSED-263 Null arg parameter in exec() throws if logger enabled

docs/BREAKING_CHANGES.md, exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SchemaUtils.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/DatabaseMigrationTests.kt, gradle/libs.versions.toml
Two new functions have been added:
-`SchemaUtils.statementsRequiredForDatabaseMigration`
-`SchemaUtils.generateMigrationScript` (marked as experimental)
The conditions of usage of the generated migration script:
-It has the .sql extension.
-Its name is decided by the user.
-The directory in which it is created is decided by the user.
-It is editable after it's generated.
-The user bears full responsibility for how the migration script is used. It should NOT be executed as regular SQL statements because there is no guarantee that it can be rolled back if a failure happens at any point. It should only be executed using a database migration tool like Flyway, for example, which is used in the tests for this feature.
=> feat: EXPOSED-255 Generate database migration script that can be used with any migration tool

exposed-kotlin-datetime/src/main/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinDateColumnType.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinTimeTests.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/MiscTableTest.kt
Fix [EXPOSED-270](https://youtrack.jetbrains.com/issue/EXPOSED-270).
Exposed converts Duration to its nanoseconds value when writing to database, and uses the kotlin `Long.nanoseconds` function to convert Long to Duration when reading from database. If inserting the `Duration.INFINITE` value, the saving value in database is 9223372036854775807(`Long.MAX_VALUE`). However, the  kotlin `Long.nanoseconds` function checks `Long.MAX_VALUE` exceeding the nanosecond range and then converts it to millisecond unit, causing the ignoring of last few digits of the value. Therefore, the reading value does not equal to `Duration.INFINITE` anymore.
This bug can be fixed by first checking the equality of the value and `Duration.INFINITE.inWholeNanoseconds`, then return `Duration.INFINITE` directly if …
=> fix: EXPOSED-270 Crash when `Duration.INFINITE` is used for duration column type

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/DataTypeProvider.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/MysqlDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt
With both Oracle and MySQL, attempting to create a table with an unsigned integer or long column that should auto-increment throws an `Unsupported type` exception.
This occurs because `AutoIncColumnType`, which delegates to the underlying type, is currently set up to only detect signed integer and long column types.
It is not possible to reuse the existing `integerAutoincType()` or `longAutoincType()` if the delegate is an unsigned column because of the type syntax differences between standard and auto-incrementing columns in some databases. So new types have been added to `DataTypeProvider`.
=> fix: EXPOSED-272 [MySQL, Oracle] Unsupported type BIGINT UNSIGNED for auto-increment

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/DefaultsTest.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinTimeTests.kt
`between()` currently accepts arguments of types that do not match the type stored in the column on which it is called.
This means that the following is technically possible to compile:
```kt
object TestTable : Table() {
val number = integer("number")
}
TestTable
.selectAll()
.where { TestTable.number.between("hello", "there") }
```
In the event that this is being taken advantage of by users (for example with numeric or UUID types), rather than introducing an immediate breaking change, the upper bounds have been restricted to highlight the offending function and show a compiler warning.
> Type argument for a type parameter S can't be inferred because it has incompatible upper bounds: Int, String (multiple incompatible classes). This will become an error in Kotlin 2.0
A function overload …
=> fix: EXPOSED-266 Between() accepts arguments of different type than column type

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt
I came across this warning while scanning the datetime modules for PR #1983 .
A strange compiler warning is flagged for the following code in `exposed-jodatime` and `exposed-java-time` modules:
```kt
object TestTable : Table() {
val created = date("created")
val deleted = date("deleted")
}
TestTable
.selectAll()
.where { TestTable.created eq TestTable.deleted }
```
>  Type argument for a type parameter E can't be inferred because it has incompatible upper bounds: LocalDate, EntityID (multiple incompatible classes). This will become an error in Kotlin 2.0
The same warning doesn't appear in the `exposed-kotlin-datetime` module.
But a user has already reported that they are seeing the warning with regular (non-entity id) UUID columns, suggesting a pattern only involving objects that aren't …
=> fix: EXPOSED-280 Comparison operators show incorrect compiler warning with datetime columns

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Op.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SchemaUtils.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/functions/array/ArrayFunctions.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/api/PreparedStatementApi.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/FunctionProvider.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/H2.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-jdbc/api/exposed-jdbc.api, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcPreparedStatementImpl.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/ArrayColumnTypeTests.kt
Adds a new `ArrayColumnType` that accepts and returns elements of a List:
```kt
object TestTable : Table() {
val amounts: Column<List<Int>?> = array<Int>("amounts", IntegerColumnType()).nullable()
val items: Column<List<String?>> = array<String?>("amounts", TextColumnType()).default(emptyList())
val prices: Column<List<Double>> = array<Double>("prices", DoubleColumnType())
}
```
**Note:**
- The `ARRAY` data type is supported by H2 and PostgreSQL (and their variants). See below for other possible supporting DB.
- Even though it is an `array()` column, the expected input/output is `List`. Type casting with List and Java `ArrayList` is more simple when retrieving `java.sql.Array` from the DB. Avoiding class cast exceptions when converting back to a `kotlin.Array` is possible but would …
=> feat: EXPOSED-248 Support array column type

build.gradle.kts, buildSrc/src/main/kotlin/org/jetbrains/exposed/gradle/Detekt.kt, detekt/detekt-config.yml
How to test:
1. Add code that would cause a **detekt** error (e.g: an unused import)
2. Run `./gradlew detekt` from the terminal
3. It should fail and point you to the problematic code
=> chore: Configure detekt Gradle task to show its result in the terminal/IDE directly instead of generating an XML report

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ops/AllAnyOps.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/ArrayColumnTypeTests.kt
Support using `ANY` and `ALL` operators with new array column from PR #1986 , as well as any expression that returns a new array value, so the following is possible:
```kt
Table
.selectAll()
.where { Table.number eq anyFrom(Table.numbers) }
Table
.selectAll()
.where { Table.number less allFrom(Table.numbers.slice(1, 5)) }
```
**Next step:**
- Replace `UntypedAndUnsizedArrayColumnType` from PR #1886  with `ArrayColumnType` and refactor existing functions to use base column type reflection.
=> feat: EXPOSED-290 Support ANY and ALL operators using array column expressions

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Op.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/ConditionsTests.kt
Attempting to use either operator `isDistinctFrom()` or `isNotDistinctFrom()` with a left- or right-side value that is a complex expression results in either a syntax exception or incorrect results (depending on the db):
```kt
Table
.selectAll()
.where { Table.number1.isNotNull() isDistinctFrom Table.number2.isNull() }
// generates SQL:
// WHERE number_1 IS NOT NULL IS DISTINCT FROM number_2 IS NULL
// which is actually evaluated as:
// WHERE (number_1 IS NOT NULL IS DISTINCT FROM number_2) IS NULL
```
`isNull()` and `isNotNull()` are already marked as `ComplexExpression`.
This fix ensures that any such expressions are identified properly when appending to the query builder, by using `appendExpression()` instead of base `append()`.
```kt
// new SQL:
// WHERE (number_1 IS NOT NULL) IS …
```
=> fix: EXPOSED-287 Wrong parenthesis with advanced use of isDistinctFrom

exposed-core/src/main/kotlin/org/jetbrains/exposed/dao/id/EntityID.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/dao/id/IdTable.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/DaoEntityID.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/DaoEntityIDFactory.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/IntEntity.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/LongEntity.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/UUIDEntity.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityTests.kt
Add KDocs to `exposed-core` and `exposed-dao` files relating to EntityID and Entity subclasses.
=> docs: Add missing KDocs for EntityID and Entity subclasses API

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Column.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/BaseBatchInsertStatement.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/InsertStatement.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/InsertTests.kt
If a generated/computed column is marked as such using `databaseGenerated()`, but it is also `nullable()`, an exception is thrown even when the field is correctly excluded from an `insert()` block.
This occurs because a NULL value is still being auto-included for that column in the prepared insert statement.
**Additional:**
- Add `isDatabaseGenerated` property to places where `Column` is copied, so that, for example, switching the chain order leads to equivalent results: `.nullable().databaseGenerated()` vs `.databaseGenerated().nullable()`
=> fix: EXPOSED-292 Explicit nulls in insert with databaseGenerated()

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Op.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/api/PreparedStatementApi.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-jdbc/api/exposed-jdbc.api, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcPreparedStatementImpl.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt
The current implementation has a limit of 2GB and causes large memory allocations. This PR changes this to streaming for reading/writing the blob.
SQLite does not know the `setBlob()` function and has no `setBinaryStream()` function, therefor `setBytes()` is used.
This PR is not compatible to existing Postgres implementations (the column-type is changed from `bytes` to `old`).
=> EXPOSED-121, allowing option for "real" blobs in postgres

exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/javatime/JavaDateColumnType.kt, exposed-jodatime/src/main/kotlin/org/jetbrains/exposed/sql/jodatime/DateColumnType.kt, exposed-kotlin-datetime/src/main/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinDateColumnType.kt
For the fix that changes the formatter when fractional seconds are not supported in MySQL, I tested it locally with MySQL docker image mysql:5.5.62, but chose not to downgrade the version in the docker file because it would necessitate changes beyond the scope of this PR.
=> chore: Date/Time improvements - Part 1

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Annotations.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/DatabaseConfig.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Op.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SchemaUtils.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ops/AllAnyOps.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/DataTypeProvider.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/H2.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-json/src/main/kotlin/org/jetbrains/exposed/sql/json/JsonFunctions.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/SelectTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/ArrayColumnTypeTests.kt
1. Replace `UntypedAndUnsizedArrayColumnType` from PR #1886   with `ArrayColumnType` from PR #1986 
- Remove unused dialect data types
2. Introduce function `resolveColumnType()` that returns an appropriate column type based on type reflection
- Refactor existing array and json functions to use this so that users don't need to manually provide a base column type
- Provide a nullable override so that the base column type can be explicitly defined
**Note** This is a potentially breaking change in the (unlikely) event that users were providing an array of non-primitive or unsupported types to `anyFrom()` or `allFrom()`, for example: `anyFrom(arrayOf<BigInteger>())`. The recommendation will be to provide the best match or custom column type to the new parameter.
=> fix!: EXPOSED-288 Extend ANY and ALL operators to use ArrayColumnType

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/JavaTimeTests.kt, exposed-jodatime/src/test/kotlin/org/jetbrains/exposed/JodaTimeTests.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinTimeTests.kt
1. Add column type override so default datetime lists are not treated as text type.
2. Add unit tests in the 3 datetime modules.
=> fix: Add ArrayColumnType default override for datetime module types

exposed-crypt/build.gradle.kts, exposed-crypt/src/test/kotlin/org/jetbrains/exposed/crypt/EncryptedColumnTests.kt, exposed-tests/build.gradle.kts, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/SelectTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/UpdateTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/functions/FunctionsTests.kt, gradle/libs.versions.toml
- Bump `spring-security-crypto` dependency from 5.8.8 to 6.2.1.
- As for the other spring modules, upgrading to version 6.+ now requires JDK 17.
- Relocate related tests from `exposed-tests` to dedicated test directory in `exposed-crypt`.
- `exposed-tests` uses JDK 8, so its dependency on the `exposed-crypt` project fails.
=> build!: EXPOSED-234 Set exposed-crypt to jdk 17 & bump spring-security-crypto to 6.+

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Constraints.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt
Running tests with references and properties of the data class `ForeignKeyConstraint` have made it clear that I incorrectly swapped the referencing table ("child") with the referenced table ("parent") in  the class KDocs.
The KDocs now properly match the fields/behavior seen when the class members are accessed in tests.
The KDocs for functions that create foreign keys have also been cleaned up and samples added.
=> docs: Fix foreign key KDocs that swap parent and child references

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/H2.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateMissingTablesAndColumnsTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/sqlite/ForeignKeyConstraintTests.kt
Calling `SchemaUtils.createMissingTablesAndColumns()` on a table with a composite foreign key incorrectly produces 2 `ALTER` statements (to drop and add the same constraint) when testing on some H2 compatibility modes (Oracle and SQL Server).
This occurs because these H2 modes delegate to the respective dialects which have `NO_ACTION` stored as their default.
But a foreign key sent to the H2 database with `NO_ACTION` is returned by the driver metadata as the equivalent `RESTRICT`, leading to a false constraint equality check.
=> fix: EXPOSED-299 [H2 modes] SchemaUtils drops and adds identical composite foreign key

documentation-website/Writerside/topics/Deep-Dive-into-DSL.md, exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Queries.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/BatchUpsertStatement.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/UpsertStatement.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/FunctionProvider.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/MysqlDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLServerDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLiteDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/UpsertTests.kt
Currently, if the `onUpdate` parameter of `upsert()` is specified, this argument will be used in the update clause of the upsert statement. If the argument is left `null`, a duplicate of the column-value assignments from the insert `body` block will be used instead.
So if a user wants to only update a subset of columns, or not update columns with default values for examples, the only option is to provide an argument to `onUpdate` that duplicates the insert block:
```kt
object TestTable : Table("tester") {
val id = integer("id").uniqueIndex()
val created = datetime("created").defaultExpression(CurrentDateTime)
val updated = datetime("updated").defaultExpression(CurrentDateTime)
val name = varchar("name", 32)
val age = integer("age")
}
// for example, column "created" should never be …
```
=> feat: EXPOSED-258 Enhance upsert to allow exclusion of columns set on conflict

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/UpdateStatement.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/UpdateTests.kt
Attempting to use any `join` function in its full overload form, with an `additionalConstraint` argument, results in an exception if an `update()` is called after instead of a `select()`, for example:
> org.jetbrains.exposed.exceptions.ExposedSQLException: No value specified for parameter 2.
This occurs because the `additionalConstraint` conditions are being correctly appended to generated SQL, but their arguments are not being first registered with the prepared update statement.
The arguments in the update statement now correctly register any `additionalConstraint` and take into account their order if an update with a WHERE clause is called.
No unit tests existed for the full overload form with `update()`, so they have been added to existing tests.
=> fix: EXPOSED-301 Update with join throws if additionalConstraint provided

exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/Entity.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityClass.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityHook.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityLifecycleInterceptor.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/exceptions/EntityNotFoundException.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityHookTest.kt
Add KDocs to `exposed-dao` files relating to the Entity class only.
=> docs: Add missing KDocs for exposed-dao Entity API

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ops/InListOps.kt
This is the first part of several preparation steps for the refactor of `IColumnType` to make it and its subclasses type-safe.
=> refactor: Make calls to `registerArgument` function type-safe in InListOps.kt

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ops/AllAnyOps.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/SelectTests.kt
When calling the `registerArgument` function in the overriden `registerSubSearchArgument` function in `AllAnyFromArrayOp`, there is a type mismatch between `sqlType` and `argument`'s type because there is a compile-time guarantee that ArrayColumnType only receives a value of type `List` and not `Array`. This mismatch results in a compilation error when trying to guarantee type-safety with the refactor of IColumnType. Therefore, this is a necessary preparation step for the refactor of IColumnType to make it and its subclasses type-safe.
To avoid introducing a breaking change, the functions `anyFrom` and `allFrom` in SQLExpressionBuilder.kt retain the same signature, but convert the `Array` to a `List`. In addition, these two functions were overloaded with ones that accept `List` instead of …
=> refactor: Make call to `registerArgument` function type-safe in AllAnyFromArrayOp.kt

exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityBatchUpdate.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityClass.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/View.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/AliasesTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityBugsRegressionTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityTests.kt
Add KDocs in `exposed-dao` files relating to `EntityClass`.
=> docs: Add missing KDocs for exposed-dao EntityClass API

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/IterableEx.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/References.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityTests.kt
Using `all()` to get a collection of entities returns an instance of an anonymous `SizedIterable` object.
When eager loading references from this object, `with()` first iterates over the object then preloads relations for each retrieved entity, which correctly generates 2 SQL statements:
```kt
val x: SizedIterable<School> = School.all().with(School::region)
// SELECT SCHOOL.ID, SCHOOL."name", SCHOOL.REGION_ID, SCHOOL.SECONDARY_REGION_ID FROM SCHOOL
// SELECT REGION.ID, REGION."name" FROM REGION WHERE REGION.ID = 1
```
If this eager loading is followed by iteration (using `toList()` or `forEach()` e.g.), the first SQL statement is executed again because the anonymous object delegates to the source iterator, `AbstractQuery.iterator` and its results (from the first execution) are discarded …
=> fix: EXPOSED-217 Unnecessary query after calling with() and iteration

exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityClass.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/InnerTableLink.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/References.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityTests.kt
**Note: All public API elements in `exposed-dao` now have KDocs.**
Add KDocs in `exposed-dao` to files relating to References and `InnerTableLink` class.
Add more samples to reference functions (so both the referencing and referenced entities and table show together for better understanding).
=> docs: Add missing KDocs for exposed-dao Entity References API

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLiteDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/DeleteTests.kt
Attempting to use `deleteIgnoreWhere()` with SQLite results in:
> SQLiteException: [SQLITE_ERROR] SQL error or missing database (near "OR": syntax error)
SQLiteDialect is currently setup to generate this SQL even though DELETE IGNORE is [not supported](https://www.sqlite.org/lang_delete.html):
```
DELETE OR IGNORE FROM Cities WHERE Cities.cityId = 1
```
DELETE IGNORE is only supported by MySQL and MariaDB and no test exists for it, so it's been added to the base delete tests.
SQLite now fails early, like all other DB, with `UnsupportedByDialectException` if ignore is set to true.
=> fix: EXPOSED-307 [SQLite] Delete ignore not supported and throws

exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityCache.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityCacheTests.kt
Add KDocs in `exposed-dao/EntityCache.kt`.
=> docs: Add missing KDocs for exposed-dao EntityCache API

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ExplainQuery.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Queries.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Transaction.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/Statement.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/FunctionProvider.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/H2.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/MariaDBDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLServerDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLiteDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/ExplainTests.kt
`explain()` takes any valid SELECT, INSERT, UPDATE, DELETE etc statement in its lambda body.
It blocks the execution of this internal statement and uses it to prepare an EXPLAIN query, which returns a result set of query execution path details (very different depending on database).
It acts like a standard `Query` in that it will not be executed until it is iterated over in some way:
```kt
val result = explain {
Countries.select(Countries.id).where { Countries.code like "A%" }
}.toList()
println(result)
// PostgreSQL example
// QUERY PLAN=Seq Scan on countries  (cost=0.00..25.38 rows=6 width=4)
// QUERY PLAN=  Filter: ((country_code)::text ~~ 'A%'::text)
```
`explain()` blocks execution of the lambda statement by using 2 new Transaction properties.
1 of these properties makes sure that …
=> feat: EXPOSED-238 Support EXPLAIN statements

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SchemaUtils.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/DatabaseMigrationTests.kt
Previously, for indices that exist in the database but are not mapped in the code, only a warning was logged, but their DROP statements were not included in the statements returned by the `statementsRequiredForDatabaseMigration` function. This PR changes that.
A separate function was introduced to keep the behaviour in the older functions the same and limit this change to the `statementsRequiredForDatabaseMigration` function.
=> feat: Include DROP statements for unmapped indices in list of statements returned by `statementsRequiredForDatabaseMigration` function

README.md, documentation-website/Writerside/topics/Getting-Started.md, documentation-website/Writerside/topics/Modules-Documentation.md, exposed-bom/README.md, exposed-spring-boot-starter/README.md
Maven Central is available as a repository by default when using Maven, so it's not necessary to add it explicitly and I wouldn't recommend doing this. This advice might even mess up corporate users which can only access Maven Central via their company's artifact manager.
This PR also recommends using `exposed-bom` for dependency management.
=> Improve instructions for Maven users

exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityTests.kt
`idParam` has no test coverage in the codebase right now. If there are more types of tests I should add for it, please let me know.
=> test: Add test for idParam

exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcDatabaseMetadataImpl.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateMissingTablesAndColumnsTests.kt
we noticed a bug when using tables that have a schema where indexes were not being attached to the instance.
we were calling `metadata.getIndexInfo(catalog, tableSchema, storedIndexTable, false, false)` and getting no indexes returned. we were calling it with params like this:
```kotlin
metadata.getIndexInfo(catalog,"test", "test.test_table", false, false)
```
=> fix(jdbc): existingIndices() misses indexes from tables with a schema

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/DatabaseDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/UnionTests.kt
PostgreSQLDialect currently sets `supportsSubqueryUnions` property to `false` by default even though the use of subqueries (SELECT query including ORDER BY and/or LIMIT clause) has been supported alongside set operations since as early as [PostgreSQL version 12](https://www.postgresql.org/docs/12/queries-union.html).
The PostgreSQL GDG currently supports [only versions 12 through 16](https://www.postgresql.org/support/versioning/).
The 3 existing subquery union tests pass on all latest version [Docker images](https://hub.docker.com/_/postgres): 12.18-alpine, 13.14-alpine, 14.11-alpine, 15.6-alpine, 16.2 (latest).
=> fix: EXPOSED-259 supportsSubqueryUnions is too strict for PostgreSQL 12+

documentation-website/Writerside/topics/Working-with-Transaction.md, exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/DatabaseConfig.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Transaction.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/transactions/ThreadLocalTransactionManager.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/transactions/TransactionApi.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/transactions/experimental/Suspended.kt, exposed-tests/src/main/kotlin/org/jetbrains/exposed/sql/tests/DatabaseTestsBase.kt, exposed-tests/src/main/kotlin/org/jetbrains/exposed/sql/tests/TestDB.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/h2/MultiDatabaseEntityTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ConnectionExceptions.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ConnectionTimeoutTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/CoroutineTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/NestedTransactionsTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/RollbackTransactionTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ThreadLocalManagerTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/TransactionIsolationTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityTests.kt
The KDocs and the name for the property `Transaction.repetitionAttempts` makes it seem like setting the value to 1 means that any failed transaction would undergo 1 automatic retry or repeated attempt.
Instead, setting the value to 1 means that the transaction is only run once, without any repetition or retry, and any failure is thrown. [Example logic in source code](https://github.com/JetBrains/Exposed/blob/main/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/transactions/ThreadLocalTransactionManager.kt#L284)
The property, and its related delay and default variants, are being deprecated in favor of properties that are more aligned with their underlying purpose and the common naming conventions of other standard retry tools/plugins/frameworks:
- `repetitionAttempts` -> …
=> fix!: EXPOSED-317 repetitionAttempts property is misleading

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/MysqlDialect.kt
MySQL `upsert()` uses an alias for the insert row values when the database version is 8+.
But this is actually only possible starting with version 8.0.19.
Existing property `MysqlDialect.isMysql8` calls `isVersionCovers()`, which only fetches the database's major and minor version, so it is not sufficient for this comparison.
To get the patch version as well requires fetching metadata using the full `databaseProductVersion` property.
Tested locally with MySQL docker images 8.0.35, 8.0.19, 8.0.18, and 8.0.13.
=> fix: EXPOSED-340 Syntax error using upsert with MySQL8 below 8.0.19

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Sequence.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/api/ExposedDatabaseMetadata.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/DatabaseDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/H2.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLServerDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/VendorDialect.kt, exposed-jdbc/api/exposed-jdbc.api, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcDatabaseMetadataImpl.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/SequencesTests.kt
Added two functions:
- `sequences()` returns all the existing sequences that a user has the right to access in a database
- `exists()` for a `Sequence` that checks if a sequence exists by looking up all the existing sequences that a user has the right to access in a database, and checking if the identifier of the `Sequence` matches that of any of the existing sequences
=> feat: EXPOSED-296 Add ability to check if a Sequence exists in a database

documentation-website/Writerside/topics/Data-Types.md, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/EnumerationTests.kt
The example code for using `customEnumeration()` with H2 throws a cast exception.
If the type sent to the database is a string, it is not expected that the value returned by the database will be an integer.
Both transformation functions use or return a string now.
Confirmed that examples for MySQL and PostgreSQL do work.
=> docs: EXPOSED-319 H2 customEnumeration example throws

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Alias.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Column.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/AliasesTests.kt
The values set for `clientDefault`, `defaultExpression`, `databaseGenerated`, and `reference` were not being copied when cloning columns for a table alias, so I fixed it in one go for all of them.
=> fix: EXPOSED-349 "defaultValueFun" is lost from Column in Alias

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Database.kt
`Database.connect()` has an alternative, `Database.connectPool()` that takes a `ConnectionPoolDataSource` as an argument.
JDBC driver implementations of this class are not actual connection pools, but rather a means of obtaining the physical connections to be used in a connection pool.
**SQLite:**
* `SQLiteConnectionPoolDataSource` creates a new connection on each call to `getConnection()` instead of retrieving a pooled one. This [bug](https://github.com/xerial/sqlite-jdbc/issues/1011) is known with no plans to be fixed in light of dedicated alternatives.
**PostgreSQL:**
* `PGConnectionPoolDataSource` [source code](https://github.com/pgjdbc/pgjdbc/blob/master/pgjdbc/src/main/java/org/postgresql/ds/PGConnectionPoolDataSource.java) states that:
> The app server or middleware vendor should …
=> deprecate: EXPOSED-354 Database.connectPool() with ConnectionPoolDataSource

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Queries.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/ReturningStatement.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/FunctionProvider.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLiteDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/ReturningTests.kt
Add support for `RETURNING` clause with **insert** and **upsert** statements, in PostgreSQL and SQLite.
This PR sets the base for supporting the same clause with update and delete statements. So more tests will follow with those implementations.
**Usage:**
By default, the returned data is set to all columns from the invoking table.
```kt
val result1: List<ResultRow> = Items.insertReturning {
it[name] = "A"
it[price] = 99.0
}
Items.insertReturning(listOf(Items.id, Items.name)) {
it[name] = "B"
it[price] = 200.0
}.map {
it[Items.id].value to it[Items.name]
}
```
**Note:** The statement **auto-executes**, just like other insert/update/delete, and immediately iterates over (and closes) the ResultSet to populate a `List<ResultRow>` that is returned. I thought this was the best behavior to …
=> feat: EXPOSED-355 Support INSERT...RETURNING statement

exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityBatchUpdate.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityTests.kt
This error was introduced [here](https://github.com/JetBrains/Exposed/pull/1668/files#:~:text=if%20(entity.klass%20!%3D%20klass)%20error(%22Entity%20class%24%7Bentity.klass%7D%20differs%20from%20expected%20entity%20class%20%24klass%22)) and was not detected because there were no tests covering this usage.
=> fix: Error when updating different entities mapped to the same table

exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityClass.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityTests.kt
Bug fix in version 0.45.0 introduced a side effect. The query for loading child references would be executed twice if `keepLoadedReferencesOutOfTransaction = true`:
```kotlin
Parent.findById(1)?.load(Parent::children)
// OR Parent.all().with(Parent::children)
// SQL: SELECT parents.id, parents."name" FROM parents WHERE parents.id = 1
// SQL: SELECT childs.id, childs."name", childs.parent_id FROM childs WHERE childs.parent_id = 1
// SQL: SELECT childs.id, childs."name", childs.parent_id FROM childs WHERE childs.parent_id = 1
```
This happens because the new select query was being sent to the database without checking the cache first for loaded references.
Switched to a search method that goes through the cache first and made sure the test also covers that each query is only run once.
=> fix: EXPOSED-350 keepLoadedReferencesOutOfTransaction causes duplicate query when true

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/SelectTests.kt
Since 0.50.0, attempting to use a valid iterable of comparables with `inList()` invoked by an `EntityID` column leads to a type mismatch.
This happens because the following incorrect overload is being resolved:
```kt
infix fun <T> ExpressionWithColumnType<T>.inList(list: Iterable<T>): InListOrNotInListBaseOp<T> = SingleValueInListOp(this, list, isInList = true)
```
instead of the previous expected overload that wraps values as `EntityID`s:
```kt
infix fun <T : Comparable<T>> Column<EntityID<T>?>.inList(list: Iterable<T>): InListOrNotInListBaseOp<EntityID<T>?> {
val idTable = (columnType as EntityIDColumnType<T>).idColumn.table as IdTable<T>
return SingleValueInListOp(this, list.map { EntityIDFunctionProvider.createEntityID(it, idTable) }, isInList = true)
}
```
This reverts the change, …
=> fix: EXPOSED-366 inList with EntityID column causes type mismatch error

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/javatime/JavaDateColumnType.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/DateTimeLiteralTest.kt, exposed-jodatime/src/main/kotlin/org/jetbrains/exposed/sql/jodatime/DateColumnType.kt, exposed-jodatime/src/test/kotlin/org/jetbrains/exposed/JodaDateTimeLiteralTest.kt, exposed-kotlin-datetime/src/main/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinDateColumnType.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/DateTimeLiteralTest.kt
Here is the fix for usage date literals with Oracle DB. PR adds an explicit date format for date literals, because the default format is parametrized in DB, and can be different from the one we use.
=> fix: EXPOSED-353 dateLiteral does not work on OracleDB 12c or 19c

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/ArrayColumnTypeTests.kt
Fix for the column with type `bytea[]`(`array<ByteArray>()`). FIxed by passing `byte[][]` instead of `Object[]` to the driver.
=> EXPOSED-365 Unable to insert values into `Array` column

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/UpdateBuilder.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/InsertTests.kt
Fix https://youtrack.jetbrains.com/issue/EXPOSED-371/Unsafe-cast-of-columns-table-to-IdTable-when-using-EntityID-value
=> fix: EXPOSED-371 Fix incorrect table reference passed to EntityID instance when using value-based utility functions

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Column.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/Entity.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/LongIdTableEntityTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/UuidTableEntityTest.kt
Since version 0.50.0, using `Column.references()` invoked on a `UUIDColumnType` that targets an `EntityIDColumnType<UUID>` causes a `ClassCastException`.
This occurs because `PreparedStatementApi.fillParameters()` tries to get the `valueToDB()` from `EntityIDColumnType` rather than the underlying `UUIDColumnType`.
```
uuid("col_name").references(UUIDTable.id)
// throws when trying to access the DAO entity's delegated field
java.util.UUID cannot be cast to org.jetbrains.exposed.dao.id.EntityID
java.lang.ClassCastException: java.util.UUID cannot be cast to org.jetbrains.exposed.dao.id.EntityID
at org.jetbrains.exposed.sql.EntityIDColumnType.notNullValueToDB(ColumnType.kt:199)
at org.jetbrains.exposed.sql.IColumnType$DefaultImpls.valueToDB(ColumnType.kt:39)
at …
```
=> fix: EXPOSED-382 ClassCastException when uuid().references() is used with EntityID column

exposed-java-time/api/exposed-java-time.api, exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/javatime/JavaDateFunctions.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/DefaultsTest.kt, exposed-jodatime/src/test/kotlin/org/jetbrains/exposed/JodaTimeDefaultsTest.kt, exposed-kotlin-datetime/api/exposed-kotlin-datetime.api, exposed-kotlin-datetime/src/main/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinDateFunctions.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/DefaultsTest.kt
Version 0.50.0 introduced 2 changes to `CurrentTimestamp`:
- It is now an object instead of a class.
- It no longer returns type `T`, but instead returns an `Instant`.
So its previous use as a default expression with a timezone compatible column is no longer possible, as even changing to a singleton still requirs `OffsetDateTime` as the return type:
```kt
// compile error - invoke() not found
val t3: Column<OffsetDateTime> = timestampWithTimeZone("t3").defaultExpression(CurrentTimestamp())
// compile error - type mismatch
val t3: Column<OffsetDateTime> = timestampWithTimeZone("t3").defaultExpression(CurrentTimestamp)
```
---
This fix introduces a new object `CurrentTimestampWithTimeZone` for this specific use, to both modules `exposed-java-time` and `exposed-kotlin-datetime`.
Rather than …
=> fix: EXPOSED-384 CurrentTimestamp cannot be used with OffsetDateTimeColumnType

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/BatchUpsertStatement.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/InsertStatement.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/UpsertStatement.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/UpsertTests.kt
The problem of the wrong auto-generated uuid primary key returned from `batchUpsert()`. The fix is the same like with `upsert()` command in the recent [PR/2075](https://github.com/JetBrains/Exposed/pull/2075)
=> EXPOSED-376 batchUpsert does not return database values on conflict

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Alias.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/AliasesTests.kt
The fix of `Join.lastQueryAlias` function. It was returning the first query instead of the last one (and `null` when the first join was not a join of SubQuery). Simple test reproduced it.
=> EXPOSED-387 Exposed Join.lastQueryAlias not working correctly

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Alias.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ResultRow.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/ConditionsTests.kt
The fix was made [here](https://github.com/JetBrains/Exposed/pull/1631) initially but I had to add more changes, hence this PR.
=> fix: Crash in aliased OpBoolean

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/H2.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt
H2 supports VARBINARY columns without a specified length: https://www.h2database.com/html/datatypes.html#binary_varying_type
Currently, the H2 column types throw an error if the length is not specified.  We can use VARBINARY without a specified length instead.
While these columns are limited to 1,000,000,000 bytes, in practice I do not think users will run into this limitation. I added a note to the `binary` column docs anyways.
=> feat: Add support for variable-length binary columns in H2

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/ConditionsTests.kt
Elaboration on the issue here: [EXPOSED-395](https://youtrack.jetbrains.com/issue/EXPOSED-395)
- Passed `EntityID` instead of the raw value where necessary to fix the exception
- Added required overloaded functions for `EntityID`
- Modified overload priority for some functions
=> fix: EXPOSED-395 ClassCastException with EntityId column operations

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/DataTypeProvider.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLServerDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLiteDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/UnsignedColumnTypeTests.kt
When attempting to store `ULong.MAX_VALUE` in a `ulong` column, retrieving it results in -1 and not `ULong.MAX_VALUE` for all database dialects (except for MySQL and MariaDB). The reason is that we invoke `.toLong()` on the `ULong` value before we store it in the database (in `notNullValueToDB` in `ULongColumnType`) and that gets the -1 from [here](https://github.com/JetBrains/kotlin/blob/0938b46726b9c6938df309098316ce741815bb55/libraries/stdlib/unsigned/src/kotlin/ULong.kt#L27) because of the [implementation](https://github.com/JetBrains/kotlin/blob/0938b46726b9c6938df309098316ce741815bb55/libraries/stdlib/unsigned/src/kotlin/ULong.kt#L323) of `ULong.toLong()`.
Before this fix, the maximum value that could be stored with `ULongColumnType` for all database dialects (except for MySQL and …
=> fix!: EXPOSED-360 Storing ULong.MAX_VALUE in ulong column not working

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-json/src/main/kotlin/org/jetbrains/exposed/sql/json/JsonConditions.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/BooleanColumnTypeTests.kt
Allow having a custom column type that maps a database type to a different type in Kotlin code.
Elaboration on the issue here: [EXPOSED-391](https://youtrack.jetbrains.com/issue/EXPOSED-391)
=> fix: EXPOSED-391 Cannot map columns to different types anymore

documentation-website/Writerside/topics/Deep-Dive-into-DAO.md, exposed-dao/api/exposed-dao.api, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/InnerTableLink.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/References.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/OrderedReferenceTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/ViaTest.kt
PR add the possibility to add sorting for one-to-many references. Usage looks like:
```kotlin
class User(id: EntityID<Int>) : IntEntity(id) {
companion object : IntEntityClass<User>(Users)
...
val ratings by UserRating referrersOn UserRatings.user orderBy UserRatings.value
...
}
```
Open questions that I haven't yet resolved:
1) It's not possible to create several references with different orders. For example, something like this would not work:
```kotlin
class User(id: EntityID<Int>) : IntEntity(id) {
companion object : IntEntityClass<User>(Users)
...
val ratingsByValue by UserRating referrersOn UserRatings.user orderBy UserRatings.value
val ratingsById by UserRating referrersOn UserRatings.user orderBy UserRatings.id
...
}
```
The reason is the caching of referencing rules inside …
=> feat: EXPOSED-368 Ordering on References

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Function.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/functions/FunctionsTests.kt
The Coalesce function was returning a nullable type when it shouldn't.
=> fix: EXPOSED-389 Coalesce operator returning nullable value

buildScripts/docker/docker-compose-mariadb.yml, buildScripts/docker/docker-compose-mysql.yml, buildScripts/docker/docker-compose-mysql8.yml, buildScripts/docker/docker-compose-oracle.yml, buildScripts/docker/docker-compose-postgres.yml, buildScripts/docker/docker-compose-sqlserver.yml
TC builds (both `main` & team branches) started failing on task `sqlserverComposeUp` with the message: `java.lang.RuntimeException: Exit-code 18 when calling docker-compose` eventhough no changes have been made to the compose files.
Assuming a docker build configuration change on the TC agent, the version property has been bumped to the max in all compose files.
If there's no backwards compatibility issue, the next step would be to consider removing the property entirely ([docker reference](https://docs.docker.com/compose/compose-file/04-version-and-name/#version-top-level-element-optional)), as all docker-compose tasks show the warning message: `'version' is obsolete`.
=> chore: Fix TC Docker `version` is obsolete

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/DoubleColumnTypeTests.kt
we found an issue when casting values from the DB to a DoubleColumnType when the underlying column was a `real`
db had this:
when debugging through the value was represented as a `Float`, shown here:
the data is coming back as `Float` because the Postgres column is a `real` and not a `double precision`
=> fix(DoubleColumnType): correctly handle precision when casting Float to DoubleColumnType for a `real` column

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Query.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/FetchBatchedResultsTests.kt
In the `fetchBatchedResults` function, the wrong `greater` and `less` methods were being invoked because `autoIncColumn`'s type is erased (`Column<*>`) and unknown at compile time. The issue is fixed by checking if `autoIncColumn.columnType` is an instance of `EntityIDColumnType` and casting accordingly to enable selecting the correct `greater` and `less` methods.
=> fix: EXPOSED-400 ClassCastException when using `fetchBatchedResults`

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Alias.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-tests/src/main/kotlin/org/jetbrains/exposed/sql/tests/DatabaseTestsBase.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/JoinTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/LateralJoinTests.kt
Here is the support of LATERAL joins (such a join allows using inside the joining query previous joining parts [Postgres, 7.2.1.5. LATERAL Subqueries](https://www.postgresql.org/docs/current/queries-table-expressions.html#QUERIES-LATERAL))
With this MR it's possible to mark `JoinPart` as `lateral` and it will add the key word to join operator.
The downside of the solution is that any `JoinPart` can be marked as lateral, event if it makes sense only for joining queries. It could be possible to avoid it if we split non-query-join and query-join somewhere on `ColumnSet` level which has only one `ColumnSet::join()` method now. It does not look reasonable to me, but it's discussable.
Also minor change, `on` condition of `joinQuery()` is optional now because it's possible to join a query …
=> feat: EXPOSED-295 Support subqueries with preceding LATERAL

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Expression.kt, exposed-json/api/exposed-json.api, exposed-json/src/main/kotlin/org/jetbrains/exposed/sql/json/JsonColumnType.kt, exposed-json/src/test/kotlin/org/jetbrains/exposed/sql/json/JsonBColumnTests.kt, exposed-json/src/test/kotlin/org/jetbrains/exposed/sql/json/JsonColumnTests.kt, exposed-json/src/test/kotlin/org/jetbrains/exposed/sql/json/JsonTestsData.kt
The original issue is that `upsert()` creates incorrect value in the database for Json column and H2 database.
As I understood the root of the problem is that jdbc driver works differently for `insert` and `merge` prepared statements. In the case of `insert` the json string is saved in the db as it is, in the `merge` case it is stored with escaping characters...
Some more details on [YouTrack/EXPOSED-393](https://youtrack.jetbrains.com/issue/EXPOSED-393/H2-upsert-with-JSON-column-creates-invalid-data)
With this PR the new method in `IColumnType` is introduced: `fun parameterMarker(value: T?) = "?"`
It allows for the `JsonColumnType` to specify modifier for the parameter marker inside a prepared statement (so it looks like `? FORMAT JSON`).
It's done on the column type, because another …
=> fix: EXPOSED-393 H2 upsert with JSON column creates invalid data

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Queries.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/BatchUpsertStatement.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/UpsertStatement.kt, exposed-json/src/test/kotlin/org/jetbrains/exposed/sql/json/JsonBColumnTests.kt, exposed-json/src/test/kotlin/org/jetbrains/exposed/sql/json/JsonColumnTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/ExplainTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/ReturningTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/UpsertTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityTests.kt
- Add new `where` parameter to existing `batchUpsert()` and relevant overrides in `BatchUpsertStatement` class
- Update KDocs
- Remove duplicate KDocs from private functions
=> feat: EXPOSED-336 Support Where clause with batchUpsert

exposed-tests/src/main/kotlin/org/jetbrains/exposed/sql/tests/TestDB.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/SelectTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/ArrayColumnTypeTests.kt
MySQL8 was previously excluded from all tests for the following recently added functions:
- `anyFrom()` - only for Table variant, as MySQL does not support ARRAY
- `allFrom()` - only for Table variant, as MySQL does not support ARRAY
- `inTable`
- `notInTable`
These syntax are not supported by earlier version or MariaDB.
=> test: EXPOSED-249 Add MySQL8 to tests for AllAnyFromBaseOp feature

exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/References.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/LongIdTableEntityTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/UuidTableEntityTest.kt
This fix allows using `referrersOn` or `backReferencedOn` in the parent table when a column of type `T` in the child table references a column of type `EntityID<T>` in the parent table.
This use case was not working even before any refactor was done. The location from which the error is coming _is_ different now after the [type safety refactor](https://github.com/JetBrains/Exposed/commit/42ac41b14c632e745c58d234641e9a2862d3204a), but it's essentially the same problem: the type mismatch.
=> fix: EXPOSED-411 ClassCastException when `uuid().references()` is used with `referrersOn`

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Alias.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Column.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/DefaultsTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/ColumnDefinitionTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/InsertTests.kt
Column definition in `CREATE TABLE` DDL currently covers the following:
_column_name column_type column_default null_constraint key_constraint_
There are some very niched database-specific keywords or syntax that can be appended to a column definition, which are not available to the user unless introduced by feature requests. Some of these would just require hard-coding the additional feature in `Column` class for the specific database.
This proposal attempts to give user's the ability to customize column definitions that fit the following criteria:
1. It is very database-specific, but low priority.
2. It does not affect any further logic, like column insert/update values, prepared statement, etc.
3. It fits standard ordering rule shared by most databases, i.e. it follows _column_name …
=> feat: EXPOSED-416 Support adding special database-specific column definitions

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/BatchUpsertStatement.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/InsertStatement.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/UpsertStatement.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/InsertTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/UpsertTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/NonAutoIncEntities.kt
Inside `InsertStatement` there is a field `autoIncColumns` with the getter that should return the list of auto increment columns.  One of the checks it does is `column.columnType is EntityIDColumnType<*> -> !currentDialect.supportsOnlyIdentifiersInGeneratedKeys`, but looks like it's a wrong assumption since not every `EntityIDColumnType` must be autoincrementable (test with custom `String` primary key demonstrates it)
If I'm right, the main way to create `EntityIDColumnType` for the user is to use `entityId()` methods on column, but to make it autoincrement the method `cloneWithAutoInc()` (`autoIncrement()`) should be used, what will make column `AutoIncColumnType` what is also checked inside `InsertStatement`.
The only test that was affected by removing this check is …
=> fix: EXPOSED-405 SQLite bugs: Table with custom ID behaves weirdly in DAO and batchInsert

detekt/detekt-config.yml, exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/FunctionProvider.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/H2.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/MysqlDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLServerDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLiteDialect.kt, exposed-java-time/api/exposed-java-time.api, exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/javatime/JavaDateColumnType.kt, exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/javatime/JavaDateFunctions.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/JavaTimeTests.kt, exposed-jodatime/src/test/kotlin/org/jetbrains/exposed/JodaTimeDefaultsTest.kt, exposed-jodatime/src/test/kotlin/org/jetbrains/exposed/JodaTimeMiscTableTest.kt, exposed-jodatime/src/test/kotlin/org/jetbrains/exposed/JodaTimeTests.kt, exposed-kotlin-datetime/api/exposed-kotlin-datetime.api, exposed-kotlin-datetime/src/main/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinDateColumnType.kt, exposed-kotlin-datetime/src/main/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinDateFunctions.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinTimeTests.kt
- Added `time` extension functions for temporal expressions in Kotlin and Java.
- Modified `Time` function to make it work for all database dialects.
- Modified `JodaTimeMiscTableTest` and `JodaTimeDefaultsTest` to extend `DatabaseTestsBase` instead of `JodaTimeBaseTest` to match the way it is in the Kotlin and Java tests.
- H2 V1 is excluded from the tests because of a bug in the driver that messes up the fractional seconds.
I'm planning to add more tests to cover more types in later pull requests.
=> feat: Add time extension function for temporal expressions in Kotlin and Java

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/FetchBatchedResultsTests.kt
Added an additional check to see if the table is an alias and use the alias' delegate in that case.
I wanted to change the same logic in `UpdateBuilder`, but I couldn't think of a usage of the `set` functions where this change would be necessary. Please let me know if you think of a case where it is.
=> fix: EXPOSED-424 ClassCastException exception when using `fetchBatchedResults` with `alias`

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/CompositeColumn.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-money/api/exposed-money.api, exposed-money/src/main/kotlin/org/jetbrains/exposed/sql/money/CompositeMoneyColumn.kt, exposed-money/src/main/kotlin/org/jetbrains/exposed/sql/money/CompositeMoneyColumnType.kt, exposed-money/src/test/kotlin/org/jetbrains/exposed/sql/money/MoneyTests.kt
Defining a composite money column as nullable returns a different type:
```kt
// non-nullable column
val money: CompositeMoneyColumn<BigDecimal, CurrencyUnit, MonetaryAmount> = compositeMoney()
// actual nullable column
val nullableMoney: CompositeMoneyColumn<MonetaryAmount?> = compositeMoney().nullable()
// expected nullable column
val money: CompositeMoneyColumn<BigDecimal?, CurrencyUnit?, MonetaryAmount?> = compositeMoney().nullable()
```
The current setup works as long as the insert value is a composite `Money` value, as the individual columns will not be able to be resolved.
If the component values (`BigDecimal` and `CurrencyUnit`) are inserted individually into the component columns, it will only work for either a non-nullable column or a nullable column with a non-null value. This …
=> fix: EXPOSED-407 compositeMoney() nullability definition issues

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Queries.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/ReturningTests.kt
Adds a new parameter to `insertReturning()` so that `INSERT IGNORE` statements can be used with the `RETURNING` clause.
As mentioned as part of #2142
=> feat: EXPOSED-435 Allow insertReturning() to set isIgnore = true

exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/javatime/JavaDateColumnType.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/JavaTimeTests.kt, exposed-kotlin-datetime/src/main/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinDateColumnType.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinTimeTests.kt
=> fix: EXPOSED-363 LocalTime and literal(LocalTime) are not the same

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SchemaUtils.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/MysqlDialect.kt, exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/javatime/JavaDateFunctions.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/DefaultsTest.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/JavaTimeTests.kt, exposed-jodatime/src/main/kotlin/org/jetbrains/exposed/sql/jodatime/DateFunctions.kt, exposed-jodatime/src/test/kotlin/org/jetbrains/exposed/JodaTimeDefaultsTest.kt, exposed-kotlin-datetime/src/main/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinDateFunctions.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/DefaultsTest.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinTimeTests.kt
As of [MySQL 8.0.13](https://dev.mysql.com/doc/refman/8.0/en/data-type-defaults.html#:~:text=Expression%20Evaluation%E2%80%9D.-,Explicit%20Default%20Handling%20Prior%20to%20MySQL%208.0.13,-With%20one%20exception) and [MariaDB 10.2.1](https://mariadb.com/kb/en/create-table/#default-column-option), the default value specified in a DEFAULT clause can be a function or an expression.
=> fix: EXPOSED-432 CurrentDate default is generated as null in MariaDB

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/InsertStatement.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/functions/MathFunctionTests.kt
MySQL and MariaDB are the only supported databases that allow referencing another column in a default expression, but for this to work, the referenced column must be one that occurs earlier in the table definition. This was not working because Exposed was sorting the columns by column name for the insert statement. Not sorting fixes this issue.
=> fix: Allow column reference in default expressions for MySQL and MariaDB

documentation-website/Writerside/topics/Transactions.md
When PR #2042 was created, changes of the name `repetitionAttempts` to `maxAttempts` were placed in the .md file `Working-with-Transaction`. The documentation website actually uses content from `Transactions.md`, so the [deprecated info](https://jetbrains.github.io/Exposed/transactions.html#advanced-parameters-and-usage) is public.
Mention of this unused .md file (along with the other 2 unused files) has been made in [EXPOSED-73](https://youtrack.jetbrains.com/issue/EXPOSED-73/Create-Documentation) so that a decision can be made about their future.
=> docs: Change repetitionAttempts to maxAttempts in website docs

CHANGELOG.md, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/InsertStatement.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/InsertTests.kt
Here is a small fix before a bigger way of improving default values. 
We have a small regression for Postgres. Before it was possible to take default values generated on the DB side (columns with `defaultExpression()` or `databaseGenerated()` definitions) from insert statement. It was broken some weeks ago. Here is a corresponding test with the fix added.
Also updated the changelog a bit because it was mentioned in Slack that one of PRs added a breaking change (the one with the lateral joins feature)
=> fix: EXPOSED-430 Insert and BatchInsert do not return default values

documentation-website/Writerside/topics/Deep-Dive-into-DSL.md, exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-dao/api/exposed-dao.api, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/Entity.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityClass.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/ColumnTransformTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/ColumnWithTransformTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/ColumnWithTransformTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityFieldWithTransformTest.kt
Here is the PR that allows to transform columns from their original types to another. 
Transformations could be nested, and could be applied to nullable columns. Transformation of a non-nullable column produces a non-nullable column, and transformation of a nullable column produces a nullable one. Creating nullable columns requires not only types changing, but also set field `nullable` into true, so still the method `nullable()` must be used.
We already have `transform()` for columns on the DAO layer, so I took naming from there (`toColumn`, `toReal` methods):
```kotlin
.transform(
toColumn: (TReal) -> TColumn,
toReal: (TColumn) -> TReal
)
```
But probably it's not the perfect variant. I was initially thinking about `Target`/`Source` instead of `TReal`/`TColumn` respectively. If you …
=> feat: EXPOSED-388 Support for column type converters

documentation-website/Writerside/hi.tree, documentation-website/Writerside/topics/Deep-Dive-into-DAO.md, documentation-website/Writerside/topics/Frequently-Asked-Questions.md, documentation-website/Writerside/topics/Table-Definition.md
Adds details about new `CompositeIdTable` and how it relates to:
- Available `IdTable` types
- DAO CRUD operations
- DAO references
- Creating primary keys
- Creating foreign keys
Additional:
- Update incorrect FAQ about ARRAY column type
- Replace FAQ about custom `IdTable` with a direct example
- Restructure `hi.tree` to include existing, but unused, `Table-Definitions.md`
=> docs: EXPOSED-445 Add documentation for DSL & DAO composite primary keys

exposed-java-time/src/test/kotlin/org/jetbrains/exposed/DefaultsTest.kt, exposed-jodatime/src/main/kotlin/org/jetbrains/exposed/sql/jodatime/DateColumnType.kt, exposed-jodatime/src/test/kotlin/org/jetbrains/exposed/JodaTimeDefaultsTest.kt, exposed-kotlin-datetime/src/main/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinDateColumnType.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/DefaultsTest.kt
-  Joda-Time: Handled the case when the default value for a `timestampWithTimeZone` column has trailing zeros after the last dot ("2024-07-18T13:19:44.000"), which was the reason the test was failing. The zeros were being removed without removing the dot, which resulted in a parsing error. To fix this, I chose not to remove the zeros at all.
- Modifed `POSTGRESQL_OFFSET_DATE_TIME_AS_DEFAULT_FORMATTER` and `nonNullValueAsDefaultString` in KotlinDateColumnType.kt to match that of JavaDateColumnType.kt.
=> fix: EXPOSED-452 Flaky H2_Oracle test `testTimestampWithTimeZoneDefaults`

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SchemaUtils.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateMissingTablesAndColumnsTests.kt
`SchemaUtils.statementsRequiredToActualizeScheme()` was working incorrectly for MySql in the case a table has default float/double values. The reason is that MySQL returns a default float / double value without trailing zeros, when other databases return it with 1 trailing `0`. For example, the value `30f` returned from metadata for MySQL as `"30"` and for other databases as `"30.0"`.
---
---
[EXPOSED-457](https://youtrack.jetbrains.com/issue/EXPOSED-457) The column default value always compares unequal
=> EXPOSED-457 The column default value always compares unequal

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ops/InListOps.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/SelectTests.kt
Fixes compound operator logic in SQL Server branch of `MultipleInListOp`
- **Why**:
Current logic uses the following construct with `notInList()`:
`WHERE NOT(col_1 != ? AND ...) OR NOT(col_1 != ? AND ...) OR ...`
This was not being tested for properly and does not produce expected results.
Can be additionally observed by replacing any existing `notInList` test (pair/triple) with the list overload.
- **How**:
Logic has been switched to:
`WHERE NOT(col_1 == ? AND ...) AND NOT(col_1 == ? AND ...) AND ...`
---
---
PR #2157
=> chore: [SQL Server] Fix MultipleInListOp logic when isInList = false

documentation-website/Writerside/topics/Deep-Dive-into-DSL.md, exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/AbstractQuery.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Query.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/mysql/MysqlTests.kt
Allows implementation of custom Query classes that do not lose stored properties of the original query. This may be useful for users that need niched or very database-specific clauses, for example MySQL [query index hints](https://dev.mysql.com/doc/refman/8.0/en/index-hints.html).
- **Why**:
While it is possible to customize extension functions on the Query class, built-in class properties with private setters will not be copied to the new query instance when chaining/query building. The only properties copied would be those stored in base `AbstractQuery`. So these custom functions could not be used with original queries:
```kt
val originalQuery = TestTable.selectAll().where { TestTable.id eq 2 }.groupBy(TestTable.amount)
// when …
```
=> feat: EXPOSED-459 Open AbstractQuery.copyTo() to allow custom Query class extension

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-dao/api/exposed-dao.api, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/Entity.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityClass.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/References.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/CompositeIdTableEntityTest.kt
It is now possible to use eager loading with references involving `CompositeIdTable`.
- **Why**:
Initial implementation of `CompositeIdTable` was already very large, so the necessary logic to use `.load()` and `.with()` was not included. `preloadRelations()` also relied heavily on `inList`, which was not capable of accepting an unknown-sized list of columns on the left hand side: PR #2157 
- **How**:
- Add `inList` overloads for `List<CompositeID>` and for deconstructed `CompositeIdTable.id`
- Unit test commented out due to SQL Server bug:  PR #2176 
- Refactor `preloadRelations()` to handle `CompositeIdTable` references (both parent and child)
- Add variant to `warmupReferences()` that can work with multiple-column ids.
---
Please mark …
=> fix: EXPOSED-447 Eager loading does not work with composite PK entity

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/dao/id/CompositeID.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/dao/id/IdTable.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/CompositeIdTableEntityTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/ViaTest.kt
Adds validation of `IdTable.idColumns` on every access to ensure that a `CompositeIdTable` is not defined without any.
- **Why**:
When testing many-to-many relations with an extra column, the user might choose to use a `CompositeIdTable` as the intermediate table, with a composite primary key including a `reference()` column for each child table. In this case, since `entityId()` would not be called on either, `idColumns` would be empty. This would cause errors the first time the `id` column is accessed.
- **What**:
This PR proposes validating the id columns and throwing an exception with suggestions to use `Column.entityId()` or call `Table.addIdColumn()`.
- **How**:
- Make `idColumns` publicly read-only and change visibility modifier …
=> fix: Change IdTable idColumns to read-only and add validation on access

exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/CompositeIdTableEntityTest.kt
Previous merge to main wasn't rebased first and an import statement got lost, causing [the main build to fail](https://exposed.teamcity.com/buildConfiguration/Exposed_Build/6961?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true) with unresolved reference.
=> chore: Add missing import in exposed-tests

documentation-website/Writerside/topics/Home.topic
The items in the Learn more page of the documentation home page were linked to nothing.
The links were updated to link into the relevant documentation.
I believe that links leading to no where are not very user friendly, even if the documentation is not finished.
---
---
EXPOSED-473
=> Add links in Learn more section on documentation home page

.github/PULL_REQUEST_TEMPLATE.md, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/transactions/ThreadLocalTransactionManager.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/NestedTransactionsTest.kt
Nested transactions wrapped in a try-catch block that fail no longer commit their failed operations to the outer transaction block.
- **Why**:
Wrapping a nested transaction (`transaction` + `useNestedTransaction = true`) in a try-catch block would successfully catch and log any exception, but any operations performed within the failed transaction would still be committed. Whereas the expected behavior (that any failed operations would undergo rollback) would be achieved if `inTopLevelTransaction` is used instead of the nested transaction.
- **How**:
Branch for nested transaction logic now includes a catch block, similar to try-catch logic already in `inTopLevelTransaction`, rather than being ignored and caught by the outer transaction …
=> fix: EXPOSED-439 Outer transaction commits rows from failed inner transaction

.github/PULL_REQUEST_TEMPLATE.md, buildSrc/src/main/kotlin/org/jetbrains/exposed/gradle/Versions.kt, exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/javatime/JavaDateColumnType.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/DefaultsTest.kt, exposed-jodatime/src/main/kotlin/org/jetbrains/exposed/sql/jodatime/DateColumnType.kt, exposed-jodatime/src/test/kotlin/org/jetbrains/exposed/JodaTimeDefaultsTest.kt, exposed-kotlin-datetime/src/main/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinDateColumnType.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/DefaultsTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ThreadLocalManagerTest.kt, gradle/libs.versions.toml
When the value of a `timestampWithTimeZone` column is set from `CURRENT_TIMESTAMP`, the format of the value is different than when a different value is set as a default or a value is set during insertion, and the column type was not handling that case before for SQLite and Oracle.
- **What**:
Make `timestampWithTimeZone` column work when `CurrentTimestampWithTimeZone` expression is used as a default in SQLite and Oracle.
- **Why**:
Error was being thrown before.
- **How**:
Modify formatters to handle when `timestampWithTimeZone` column is set from `CURRENT_TIMESTAMP`.
---
---
=> fix: EXPOSED-464 `CurrentTimestampWithTimeZone` expression does not work as a default

docs/api/scripts/navigation-loader.js, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/GroupByTests.kt
fix some comments
---
- [ X] Documentation update
---
=> chore: fix some comments

exposed-core/src/main/kotlin/org/jetbrains/exposed/dao/id/IdTable.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Alias.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/AliasesTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/CompositeIdTableEntityTest.kt
**Summary of the change**: Using any aliased `IdTable` with `isNull()` or `eq()` no longer throws a class cast exception.
- **Why**:
The introduction of `CompositeIdTable` (PR #1987 ), and internal functions `mapIdComparison` and `mapIdOperator`, led to a regression. When any `IdTable` is aliased and used with the associated comparison operators, `eq` and `isNull` (and negative variants), the following is thrown: `org.jetbrains.exposed.sql.Alias cannot be cast to org.jetbrains.exposed.dao.id.IdTable`
- **What**:
The `Alias` class now has its own override for these internal functions, so that the aliased `idColumns` of the delegate are used.
- **How**:
- Both `mapIdComparison` and `mapIdOperator` have been moved a level down to `Table`, so that they can be …
=> fix: EXPOSED-472 Alias IdTable fails with isNull and eq ops

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnDiff.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SchemaUtils.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/ColumnMetadata.kt, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcDatabaseMetadataImpl.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ConnectionTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateMissingTablesAndColumnsTests.kt
Defining the same column of type `decimal()`, `binary()`, `varchar()`, or `char()` but with a different size (precision) or scale (for `decimal` only) now correctly triggers an ALTER statement when `SchemaUtils.createMissingTablesAndColumns` is used.
- **Why**:
Currently, if the existing database table has a column of type DECIMAL(?,?), VARCHAR(?), VARBINARY(?), or CHAR(?) and the Exposed table object defines the same column type but with a different size, the `SchemaUtils` functions will not generate any ALTER statements to fix the inconsistency.
- **What**:
`SchemaUtils.createMissingTablesAndColumns` now compares existing- and defined- column size (and scale, if applicable to type) when inspecting the `ColumnDiff`.
- **How**:
- …
=> fix: EXPOSED-467 Decimal type precision and scale not checked by SchemaUtils

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/BatchUpdateStatement.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/CompositeIdTableEntityTest.kt
We recently decided to adopt the new CompositeID-based Entities/Tables, and might have stumbled upon a bug.
Concisely put, it looks like it doesn't entirely work when CompositeID-entities are being batch-flushed (as at the end of a transaction). Here is an example stack trace when testing towards Postgres:
```
Can't infer the SQL type to use for an instance of org.jetbrains.exposed.dao.id.CompositeID. Use setObject() with an explicit Types value to specify the type to use.
org.postgresql.util.PSQLException: Can't infer the SQL type to use for an instance of org.jetbrains.exposed.dao.id.CompositeID. Use setObject() with an explicit Types value to specify the type to use.
at org.postgresql.jdbc.PgPreparedStatement.setObject(PgPreparedStatement.java:1076)
at …
```
=> fix: EXPOSED-481 Bug with batch-flushing of CompositeID entities

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SchemaUtils.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Sequence.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateTableTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/SequencesTests.kt
Add ability to pass custom sequence to auto-increment column.
- **What**:
Added `autoIncrement` overload function that accepts a sequence of type `org.jetbrains.exposed.sql.Sequence`.
- **Why**:
I noticed that it even though it was possible to create a custom sequence using `SchemaUtils.createSequence(mySequence)` and manually call `mySequence.nextIntVal()` or `mySequence.nextLongVal()` when inserting, it was not possible to simply pass it to an auto-increment column to use internally.
- **How**:
A secondary constructor was added to `AutoIncColumnType` to pass it the custom sequence. A sequence field was also added to `AutoIncColumnType` and this field is now used instead of `autoincSeq` in SchemaUtils.kt where it was used to …
=> feat: EXPOSED-487 Add ability to pass custom sequence to auto-increment column

documentation-website/Writerside/topics/Deep-Dive-into-DSL.md, exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Queries.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/ReplaceStatement.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/SequencesTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/ReplaceTests.kt
Adds an overload for `replace()` that accepts a query as an argument, in the same way that `insert()` can accept a query instead of column-value assignments.
- **Why**:
It is already possible to generate SQL like INSERT INTO ... SELECT using `insert()` with a query parameter and REPLACE INTO ... VALUES is already supported by `replace()`. But it is not possible to generate REPLACE INTO ... SELECT without customizing the statement classes.
- **What**:
It is now possible to generate this statement out of the box.
- **How**:
- Adds a new class `ReplaceSelectStatement` that extends `InsertSelectStatement`.
- Adds a new function `Table.replace(query)`.
---
--- …
=> feat: EXPOSED-486 Support REPLACE INTO ... SELECT clause

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/CompositeIdTableEntityTest.kt
`eq()` and `neq()` extensions on `EntityID` columns no longer incorrectly assume that their passed parameter value must be a `CompositeID` if the table is a `CompositeIdTable`. The parameter value could also be a single component column value.
- **Why**:
Attempting to select or delete from a `CompositeIdTable`, when using a condition involving an `EntityID` column on the left side and a non-entity id value (and non-`CompositeID`) on the right side, results in a cast exception.
`mapIdComparison()` is being invoked simply because of the table type, which ignores the possibility that a condition could involve only a single composite key column.
- **What**: 
`mapIdComparison` is now only called if the invoking column is actually the `id` …
=> fix: EXPOSED-492 Eq/Neq op with partial CompositeID unwrapped value fails

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/UpdateStatement.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/H2.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/UpdateTests.kt
Fixes bug when generating UPDATE-FROM-JOIN statement that uses a subquery (with its own WHERE clause) in the JOIN part.
- **Why**:
Previous refactor of `UpdateStatement.arguments()`, to properly order registered arguments in an update-from-join statement, took place in PR #2007 . The fix did not factor in the possibility that the join target could be a subquery. If this query itself holds any clause with arguments, the latter will not be registered when preparing the statement, leading to the same `No value specified for parameter x` errors as previously.
- **How**:
- Any detected subquery arguments are registered just before the rest of the join part additional arguments.
- Tests for single and multiple joins, and joins with …
=> fix: EXPOSED-493 Update with join query throws if WHERE clause present

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Database.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/transactions/ThreadLocalTransactionManager.kt, exposed-tests/src/main/kotlin/org/jetbrains/exposed/sql/tests/DatabaseTestsBase.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/NestedTransactionsTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/RollbackTransactionTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/UpsertTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/ForeignIdEntityTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/ImmutableEntityTest.kt
**Summary of the change**: Raise the deprecation levels of property setters that were deprecated after `DatabaseConfig` was implemented. The deprecation level has remained untouched because they were being used for testing purposes.
- **What**:
The following elements have been deprecated since around [0.35.1](https://github.com/JetBrains/Exposed/commit/32323e35bab9c1bdd95eb7d78eda2f221e91678f) ->
**Raise from WARNING to ERROR:**
- `Database.useNestedTransactions`
- `Database.defaultFetchSize`
- `ThreadLocalTransactionManager.defaultIsolationLevel`
- **Why**: [Test refactoring]
For the last remaining property used in tests, the only current alternative to setting the deprecated property would be to either store a configured `Database.connect()` instance in a …
=> deprecate: Raise deprecation levels of API property setters

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-json/src/test/kotlin/org/jetbrains/exposed/sql/json/JsonColumnTests.kt
Adds an override for `setParameter()` to `ColumnWithTransform` class.
- **Why**:
Any column type that relies on logic in `setParameter()` to succeed when preparing a statement will fail if `transform()` is used to convert it to `ColumnWithTransform`. This happens because the delegate's implementation is being ignored by the wrapping class.
This behavior can be seen if a custom column type is created that relies on some conversion in `setParameter()`; for example, needing to use `PGobject` when setting the parameter type with PostgreSQL.
Or, as shown in the test, using `json().transform()`.
The same operations that succeed with a standard `json()` will fail with `json().transform()`, throwing something like:
``` …
```
=> fix: EXPOSED-501 Column.transform() ignores custom setParameter() logic

documentation-website/Writerside/topics/Data-Types.md
Adds a new section to 'Data Types' page with examples of how to implement different custom types.
- **Why**:
- The 6 data types used as examples are very niched database-specific types or extensions, supported by only 1 database.
Their implementation and maintenance as out-of-the-box Exposed types is very low priority given their scope of support.
- Documentation currently does not detail how a user can customize their own column types.
- **What**:
- Adds a dedicated section under 'Data Types' for each custom type class (`ltree`, `YEAR`, `int4range | daterange`, `SET`, `hstore`, `citext`) and how to use them.
- Ports the associated GH issues to a dedicated YT issue (see below) so they won't be forgotten (in the event supporting these …
=> docs: EXPOSED-499 Add examples of custom data types

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/H2.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateMissingTablesAndColumnsTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/DatabaseMigrationTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/InsertTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/ViaTest.kt
- **What**:
When obtaining all sequences from a database, Oracle and H2 Oracle now quote a sequence name if it has a dot .
- **Why**:
When attempting to drop all available sequences in Oracle and H2 Oracle, DROP SEQUENCE fails when there is a dot in the sequence name because the name obtained from the database is not quoted. The error thrown for Oracle states that the sequence is not found in the database. The error thrown for H2 Oracle states that the schema is not found in the database.
- **How**:
In the overridden `sequences()` function in `OracleDialect` and `H2Dialect`, there is now a check to see if the sequence name has a dot, and if it does and it's not already quoted, quotes are added. This way, when the sequence's `identifier` is used to drop it in the …
=> fix: EXPOSED-513 DROP SEQUENCE fails when there is a dot in the sequence name

documentation-website/Writerside/topics/Breaking-Changes.md, documentation-website/Writerside/topics/DSL-CRUD-operations.topic, exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Queries.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/DeleteStatement.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/FunctionProvider.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/H2.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/MysqlDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLServerDialect.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityLifecycleInterceptor.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/DeleteTests.kt
Adds `Join.delete()` to Queries.kt.
- **Why**:
It is already possible to perform an UPDATE of a table from a join relation using `Join.update()`.
But it is not possible to perform the DELETE equivalent.
- **What**:
```kt
val join = Users innerJoin UserData
// update all records in UserData table
join.update {
it[UserData.comment] = Users.name
it[UserData.value] = 123
}
// delete first 3 records in UserData table that have specified value
join.delete(UserData, limit = 3) { UserData.value eq 123 }
```
- **How**:
- `DeleteStatement` property `table: Table` is replaced with the common super class `targetsSet: ColumnSet`, so that it can accept either a `Table` or a `Join`. This follows the same pattern for …
=> feat!: EXPOSED-514 Support DELETE from tables in join

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Alias.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ResultRow.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/UpdateBuilder.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/ForeignIdEntityTest.kt
Internal `isEntityIdentifier()` now takes a `Column` as its receiver instead of `ColumnType`.
- **Why**:
`isEntityIdentifier()` is used to determine whether a compound operator should be used on a table's `idColumns` and its logic was dependent on an equality comparison between the receiver column type and the table's `id`.
But when `Table.reference()` is called it creates a new column using the parent's `id` column as the `idColumn`, so the table used in the comparison is equivalent. Column equality also [no longer relies on column type](https://github.com/JetBrains/Exposed/pull/2151/files#diff-8455a7e11eea94f34ecde2b3dd5eb0dc60bc7725bc190707dc792ad1d23051c2), and is solely based on table name and column name.
So if the parent's `id` …
=> fix: EXPOSED-496 reference() idColumn equality check with referree's id is insufficient

documentation-website/Writerside/topics/Deep-Dive-into-DAO.md, documentation-website/Writerside/topics/Table-Definition.topic
Adds examples of `CompositeIdTable` definition using a key `reference()` column via `addIdColumn()`.
- **Why**:
User presented with a thrown exception because they tried to create a new `CompositeID` using a `CompositeIdTable` definition that called `entityId()` unnecessarily on a reference column:
```kt
object Members : CompositeIdTable("members") {
// this results in unnecessary Column<EntityID<EntityID<Long>>>
val user = reference("user", Users).entityId() // Users is IdTable<Long> with id = long("id").entityId()
val guild = reference("guild", Guilds).entityId() // Guilds is IdTable<Long> with id = long("id").entityId()
val experience = integer("experience").default(0)
override val primaryKey = PrimaryKey(user, guild)
}
```
The …
=> docs: EXPOSED-515 How to identify composite key columns that use reference()

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SchemaUtils.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/DatabaseDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/H2.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLServerDialect.kt, exposed-migration/src/main/kotlin/MigrationUtils.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/DatabaseMigrationTests.kt
The function `MigrationUtils.statementsRequiredForDatabaseMigration` now includes the proper statements to change the type of a column when it detects that the auto-increment status has changed for PostgreSQL and SQL Server, and statements to create/drop the necessary sequences.
- **Why**:
**PostgreSQL**: The generated ALTER COLUMN statement was setting SERIAL as the target column type and that was throwing an error because it is not recognised as a type.
**SQL Server**: The generated ALTER COLUMN statement was setting IDENTITY as the target column type and that was throwing an error because it is not possible to add it to an existing column later on and must be defined that way from the start.
- **How**:
Two functions, …
=> feat: EXPOSED-498 Handle auto-increment status change on a column

documentation-website/Writerside/topics/Breaking-Changes.md, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/NumericColumnTypesTests.kt
- **What**:
fix: EXPOSED-536 Short column allows out-of-range values
- **Why**:
For SQLite and Oracle, inserting an out-of-range value using raw SQL with `exec` would work even though it shouldn't.
- **How**:
Short stores values between -32768 and 32767. For Oracle, Short data type was changed from SMALLINT to NUMBER(5) because SMALLINT is stored as NUMBER(38) in the database and takes up unnecessary storage. Another reason for this change is that this is a precursor to the column type change detection feature for migration, where it will be useful to have the column type be more specific than NUMBER(38).
A check constraint was added (that applies only to SQLite, Oracle and H2_Oracle) to ensure that no out-of-range values are stored.
--- …
=> fix!: EXPOSED-536 Short column allows out-of-range values

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/Statement.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/StatementTest.kt
https://github.com/JetBrains/Exposed/pull/891
Using double ? was broken. I fixed it
=> [fix] escape parameter placeholder '?' by double question mark '??'

buildScripts/docker/docker-compose-mariadb.yml, buildScripts/docker/docker-compose-mysql5.yml, buildScripts/docker/docker-compose-mysql8.yml, buildScripts/docker/docker-compose-oracle.yml, buildScripts/docker/docker-compose-postgres.yml, buildScripts/docker/docker-compose-sqlserver.yml
- **What**:
The `version` bit has been removed from all docker yml files.
- **Why**:
Because of this warning:
> the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
---
---
=> chore: Remove docker yml files warning -> the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion

documentation-website/Writerside/topics/Breaking-Changes.md, exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLServerDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/NumericColumnTypesTests.kt
- **What**:
fix!: EXPOSED-545 Byte column allows out-of-range values
- **Why**:
For SQLite, SQL Server, Oracle, PostgreSQL, and H2 PostgreSQL, inserting an out-of-range value using raw SQL with exec would work even though it shouldn't.
- **How**:
Byte stores values between -128 and 127. For Oracle, Byte data type was changed from SMALLINT to NUMBER(3) because SMALLINT is stored as NUMBER(38) in the database and takes up unnecessary storage. Another reason for this change is that this is a precursor to the column type change detection feature for migration, where it will be useful to have the column type be more specific than NUMBER(38).
A check constraint was added (that applies only to SQL Server, SQLite, Oracle, PostgreSQL, and H2 PostgreSQL) to ensure that no out-of-range values are …
=> fix!: EXPOSED-545 Byte column allows out-of-range values

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Op.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/CompositeIdTableEntityTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityTests.kt
`idParam()` now registers each value stored in a composite key value.
- **Why**:
Using `idParam()` with a `Column<EntityID<CompositeID>>` only invokes `registerArgument()` once for the entire composite id value, leading to only 1 placeholder '?' being appended to the statement.
- **What**:
`QueryParameter.toQueryBuilder()` now checks whether the value to parameterize is a `CompositeID` and, if so, calls `registerArgument()` for every component value.
Using `idParam()` with equality or null comparison operators is also now possible.
- **How**:
Internal property `compositeValue` has been added to the `QueryParameter` class, both as a flag (to differentiate between other `QueryParameter`) and to store the `CompositeID` instead of always …
=> fix: EXPOSED-547 idParam() registers composite id value with a single placeholder

documentation-website/Writerside/topics/Breaking-Changes.md, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SchemaUtils.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/DataTypeProvider.kt, exposed-json/api/exposed-json.api, exposed-json/src/main/kotlin/org/jetbrains/exposed/sql/json/JsonColumnType.kt, exposed-json/src/test/kotlin/org/jetbrains/exposed/sql/json/JsonColumnTests.kt
That bug I found when I was working on disabling sending all the default parameters explicitly in insert statements.
The main reason, before changes the DDL definition of the columns was looking like `JSON DEFAULT '{"name":"name","team":"team"}'`, and it was recognized string, so the new entry had `json string` instead of `json object`. After changes DDL looks like `DEFAULT JSON '{"name":"name","team":"team"}'`
---
---
[EXPOSED-546](https://youtrack.jetbrains.com/issue/EXPOSED-546) [H2] Column with Json default value can not be used as databaseGenerated
=> fix!: EXPOSED-546 [H2] Column with Json default value can not be used as databaseGenerated

documentation-website/Writerside/topics/Breaking-Changes.md, exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Queries.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/DeleteStatement.kt
`DeleteStatement.offset` is now deprecated, as well as both `deleteWhere()` and `deleteIgnoreWhere()` that accept an argument for `offset` parameter.
- **Why**:
The class `DeleteStatement` has a property `offset` that is not used anywhere in the library nor when generating SQL, as no supported databases allow the `OFFSET` syntax in this operation. This has now been confirmed by db documentation and by checking with plain sql.
The property was originally implemented wherever `DELETE + LIMIT` was allowed, but it was [later removed](https://github.com/JetBrains/Exposed/commit/5d1ab8ba688ea37cc5e3f9e22ffca712981347bb#diff-9b8efbe4b97d8d793cee88a308283ba3347b33095a680f84aada090cdf121516) since even databases that support `LIMIT` do not …
=> deprecate!: EXPOSED-550 DeleteStatement holds unused offset property

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/MariaDBDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/MysqlDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLServerDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/DeleteTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/UpdateTests.kt
`Join.update(limit = ?)` now uses correct syntax with SQL Server and fails early for MySQL. These were not caught because there was no test for this operation.
- **Why**:
Attempting to perform an update from a join, with a provided limit, throws a syntax exception for SQL Server:
```
com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near 'LIMIT'.
```
because generated SQL uses both `TOP` and `LIMIT` clauses, when only `TOP` syntax should be used.
An exception is also thrown for MySQL:
```
java.sql.SQLException: Incorrect usage of UPDATE and LIMIT
```
because `LIMIT` clause is being added even though the database does not support it [for multiple-table syntax](https://dev.mysql.com/doc/refman/8.4/en/update.html). …
=> fix: EXPOSED-551 [SQL Server] Update from join with limit throws syntax exception

exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityLifecycleInterceptor.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/ReturningTests.kt
`EntityLifecycleInterceptor.beforeExecution()` now includes a branch to handle entity cache flushes for `ReturnStatement.mainStatement`.
- **Why**:
We were noticing weird issues where DAOs returned using upsertReturning had stale values.
We pinned it down to the EntityLifecycleInterceptor not correctly handling ReturningStatement upsertStatement cache evictions.
The test I’ve added validates this and will fail without my changes.
---
---
[EXPOSED-558](https://youtrack.jetbrains.com/issue/EXPOSED-558/ReturnStatements-dont-trigger-entity-cache-flush-before-execution) ReturnStatements don't trigger entity cache flush before execution
=> fix: EXPOSED-558 Entity cache for upsertReturning statements results in stale return values

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/AbstractQuery.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ExplainQuery.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/InsertStatement.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/ReturningStatement.kt
**Summary of the change**: 
Close ResultSet before closing Statement. Motivation is to suppress "JDBC resource leaked" warning when used with agroal.
[Agroal](https://agroal.github.io/docs.html), a popular `javax.sql.DataSource` implementation as used by [Quarkus](https://quarkus.io/) and others, issues a ["leak report"](https://github.com/agroal/agroal/blob/3cde889cd9c90cfed00ba494ebde9689e4837fb9/agroal-pool/src/main/java/io/agroal/pool/ConnectionHandler.java#L112-L114) before automatically closing tracked ResultSets and Statements. If a Statement is closed before related ResultSets are closed it will trigger a leak report - [ref](https://github.com/agroal/agroal/blob/3cde889cd9c90cfed00ba494ebde9689e4837fb9/agroal-pool/src/main/java/io/agroal/pool/wrapper/State …
=> fix: EXPOSED-373 Close ResultSet before closing Statement to suppress Agroal leak warning

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Database.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/api/ExposedDatabaseMetadata.kt, exposed-jdbc/api/exposed-jdbc.api, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcDatabaseMetadataImpl.kt, exposed-migration/api/exposed-migration.api, exposed-migration/src/main/kotlin/MigrationUtils.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/DatabaseMigrationTests.kt
`MigrationUtils.statementsRequiredForDatabaseMigration` now includes DROP statements for unmapped columns (those that exist in the database but not in the Exposed Kotlin code).
- **Why**:
Necessary for migration.
- **How**:
A new function `dropUnmappedColumnsStatements` was added to `MigrationUtils`. This function returns the SQL statements that drop any columns that exist in the database but are not defined in the Exposed tables. This function is then invoked in `statementsRequiredForDatabaseMigration`.
---
---
=> feat: EXPOSED-552 Include DROP statements for unmapped columns for migration

CHANGELOG.md, documentation-website/Writerside/topics/Breaking-Changes.md, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/transactions/ThreadLocalTransactionManager.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/NestedTransactionsTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/RollbackTransactionTest.kt
Nested transaction that throws any exception will continue to trigger a rollback, but inner transaction that throws will only trigger a rollback if the exception is a database SQL exception. Otherwise the latter will be propagated up to the outer transaction, which will handle it in the way that exceptions have always been handled.
- **Why**:
Following PR #2186 , any inner transaction (`useNestedTransaction = false`) that failed, for whatever reason, would trigger a rollback of all commits from the inner to the outer transaction savepoint.
This caused a regression for users that have client-side operations that may throw from inside an inner transaction. These exceptions would usually be caught and handled by try-catch logic wrapping …
=> fix: EXPOSED-562 Any caught exception from inner transaction triggers full rollback

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/AliasesTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/CompositeIdTableEntityTest.kt
The aliased `id` column from a subquery now generates the correct aliased table identifier when used in an equality comparison with an unwrapped right-hand side value.
- **Why**:
- In PR #2189  , a fix was implemented for the use of aliased tables with comparison operators that rely on `mapIdComparison()` and `mapIdOperator()`. The added tests only covered cases when the right-hand side of the operators was a wrapped `EntityID` value. Unwrapped values use operators that first need to wrap them as an `EntityID` instance, for which reason the invoking expression's table is found as an `IdTable`. The latter was then incorrectly being used to call `mapIdComparison()`, meaning that the column identifier used in SQL generation was the …
=> fix: EXPOSED-565 Subquery alias with id fails to use correct alias with eq

documentation-website/Writerside/topics/Breaking-Changes.md, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Function.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLServerDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLiteDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/GroupByTests.kt
`groupConcat()` no longer generates wrong SQL syntax for SQLite and no longer ignores unsupported parameters for Oracle and SQL Server.
- **Why**:
It was observed by a user that SQLite uses the wrong syntax for a separator in its `GROUP_CONCAT` funtion. They were also attempting to use the ORDER BY clause, which Exposed prevents because the database used to not support it. ORDER BY with aggregate functions has been supported since [version 3.44.0](https://www.sqlite.org/changes.html).
While adjusting the tests to no longer exclude, it was confirmed that SQL Server doesn't actually support DISTINCT in the function. Exposed was ignoring this value if set to `true` and not including it in SQL, whereas the usual behavior is to fail early. …
=> fix!: EXPOSED-569 groupConcat uses wrong SQLite syntax & ignores DISTINCT in Oracle & SQL Server

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Column.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateTableTests.kt
- **What**:
DDL for column in Oracle has changed when it is part of a primary key constraint.
- **Why**:
When adding a new column to an existing table in Oracle, if that new column is used in a primary key, then a separate statement is needed for the primary key otherwise there will be a syntax error. Previously, adding the column and the constraint was being done in one statement.
- **How**:
In `createStatement()` in `Column`, a check was added for Oracle to include a separate statement when there is a primary constraint to be added.
---
---
=> fix: EXPOSED-278 Invalid Oracle statement when adding a new column that is used in a primary key

build.gradle.kts, buildScripts/docker/docker-compose-oracle.yml, gradle/libs.versions.toml
Bump Oracle JDBC driver, as well as docker image for testing.
**Note** [Oracle 19c LTS](https://www.oracle.com/database/technologies/appdev/jdbc-downloads.html) could ideally be used, but [available express edition images](https://hub.docker.com/r/gvenzl/oracle-xe) do not include 19c, so the image version was bumped to 21c.
- **Why**:
- Implementation of R2DBC support with Oracle requires some changes to test configuration: Oracle database and jdbc version 18+, as well as JDK11+. **Note** If R2DBC is tested using `exposed-tests`, the latter will require other module dependencies also bumping JDK version later.
---
--- …
=> build(deps): EXPOSED-587 Bump com.oracle.database.jdbc:ojdbc8 from 12.2.0.1 to 19.24.0.0

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Constraints.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/sqlite/ForeignKeyConstraintTests.kt
- **What**:
Modified the way a foreign key name is constructed.
- **Why**:
When creating a child table that has a dot in its name, the foreign key name created by Exposed would include that dot, which causes an error.
- **How**:
The fix is to replace the dot in the table name with an underscore when constructing the foreign key name.
---
---
=> fix: EXPOSED-588 Foreign key error when table has dot in its name

documentation-website/Writerside/topics/Breaking-Changes.md, documentation-website/Writerside/topics/Data-Types.topic, exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Op.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SchemaUtils.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ops/AllAnyOps.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/MultiArrayColumnTypeTests.kt
**Summary of the change**: Added support for multi-dimensional array types in Exposed for PostgreSQL database.
- **What**: This PR adds support for multi-dimensional arrays (Postgres). Corresponding literal and param functions are updated. It also works with `ArrayGet` and `ArraySlice` functions.
---
---
[EXPOSED-359](https://youtrack.jetbrains.com/issue/EXPOSED-359) Add support for multidimensional arrays
=> feat!: EXPOSED-359 Add support for multidimensional arrays

documentation-website/Writerside/snippets/exposed-dao/build.gradle.kts, documentation-website/Writerside/snippets/exposed-dao/src/main/kotlin/org/example/entities/BaseEntity.kt, documentation-website/Writerside/snippets/exposed-dao/src/main/kotlin/org/example/entities/BaseEntityClass.kt, documentation-website/Writerside/snippets/exposed-dao/src/main/kotlin/org/example/tables/BaseTable.kt, documentation-website/Writerside/snippets/gradle/libs.versions.toml, documentation-website/Writerside/topics/DAO-CRUD-Operations.topic
Replace external sample link in DAO subsection (how to auto-fill columns on entity change) with inline sample block.
- **What**:
- Refactor original sample to use updated api and to not allow auto-fill to trigger continuous self-updates
- Add dependency on kotlin-datetime module to snippets directory
- Add refactored abstract classes to snippets directory
- Edit DAO subsection to use refactored code & link to existing section on DSL interceptors
---
---
[EXPOSED-572]()
=> docs: EXPOSED-572 Add code sample for 'auto-fill columns on entity change﻿'

documentation-website/Writerside/topics/Breaking-Changes.md, exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/dao/id/CompositeID.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/dao/id/EntityID.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/dao/id/IdTable.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Alias.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Function.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Op.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Queries.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ResultRow.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/UpdateBuilder.kt, exposed-dao/api/exposed-dao.api, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/DaoEntityID.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/DaoEntityIDFactory.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/Entity.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityCache.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityClass.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityHook.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/InnerTableLink.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/References.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/ColumnWithTransformTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/CompositeIdTableEntityTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/OrderedReferenceTest.kt
All `Entity` related objects and functions are no longer restricted to type-parameter `Comparable`.
- **Why**:
Introduction of [Kotlin 2.0](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.uuid/-uuid/) brought `kotlin.uuid.Uuid`, which does not implement `Comparable` interface, and many requests to allow its usage with `IdTable`. Loosening these type restrictions will allow users to easily implement their own `UuidColumnType` and `IdTable<Uuid>`, at least until the new type is no longer `@ExperimentalUuidApi` and built-in Exposed api options are made available.
- **How**:
- Any entity related function type-parameter restriction `T : Comparable<T>` has been replaced with `T : Any`.
- `Min` and `Max` class operators are also no longer …
=> feat!: EXPOSED-577 Allow Entity and EntityID parameters to not be Comparable

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Queries.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Query.kt
Add `inline` modifier to query functions that are passed lambda parameters.
- **What**:
- Add `inline` modifier to query functions, where possible, with `crossinline` modifier on body/block parameters to prevent non-local returns.
- Instead of using `noinline` on nullable `where` lambda parameters, some functions have been duplicated as overloads instead.
---
---
[EXPOSED-494]()
=> feat: EXPOSED-494 Inline DSL statement and query functions

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/FunctionProvider.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/UpsertTests.kt
Allows valid MERGE syntax to be generated again when using `upsert()` with update columns that include the table name in their name.
- **Why**: PR #2172 changed the way update values that copy insert values are processed internally. Since then (version 0.54.0), any update-insert value is parsed like a regular expression. For dialects that use MERGE, this means the value is automatically aliased with virtual S alias and any potential presence of the table name in the update expression is also aliased with origin T. This leads to invalid identifier syntax if the expression holds a column name that itself includes the table name.
- **What**: String replacement now only happens if the table name is located in a prefix identifier position, …
=> fix: EXPOSED-602 Column name that includes table name is aliased with upserts

documentation-website/Writerside/topics/DSL-CRUD-operations.topic, exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Query.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/DistinctOnTests.kt
Added support for `DISTINCT ON` clauses in the `Query` class, enabling retrieval of distinct rows based on specified columns for SQL SELECT statements. 
- **What**: Introduced new methods `withDistinctOn(Column<*>, vararg Column<*>)` and `withDistinctOn(Pair<Column<*>, SortOrder>, vararg Pair<Column<*>, SortOrder>)` in the `Query` class to allow the use of `DISTINCT ON` clauses. These methods enable distinct rows selection based on the specified columns and optionally ordered by specified sort orders.
- **Why**: We had several requests for that feature from GitHub and Slack
- **How**: The changes were implemented by:
- Adding two new methods to the `Query` class to set the `distinctOn` property.
- Adjusting the `prepareSQL` method to include the `DISTINCT ON` …
=> feat: EXPOSED-560 Support DISTINCT ON from Postgres

exposed-java-time/src/test/kotlin/org/jetbrains/exposed/DefaultsTest.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/JavaTimeTests.kt, exposed-jodatime/src/test/kotlin/org/jetbrains/exposed/JodaTimeDefaultsTest.kt, exposed-jodatime/src/test/kotlin/org/jetbrains/exposed/JodaTimeTests.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/DefaultsTest.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinTimeTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/h2/H2Tests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ConnectionTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateMissingTablesAndColumnsTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/DatabaseMigrationTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/BooleanColumnTypeTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/CharColumnType.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/UnsignedColumnTypeTests.kt
**Summary of the change**: While refactoring `DatabaseMigrationTests`, I noticed that there were several other test files where `withTables` could be used to simplify the tests.
---
---
=> test: Use `withTables` instead of invoking `SchemaUtils.create` wherever possible

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Query.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/CountTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/DistinctOnTests.kt
Query method `count()` ignores `offset` parameter if the `limit` parameter is not specified.
Since the PR [#2226 Allow OFFSET without LIMIT](https://github.com/JetBrains/Exposed/pull/2226/files) we can create query without `limit` parameter.
If the `count()` is called on such query the following sql is generated:
```sql
SELECT COUNT(*) FROM <table>
```
but expected query is:
```sql
SELECT COUNT(*) FROM (SELECT <columns> FROM <table> OFFSET 10) subquery
```
PR contains a fix for `count()` function that already has a check `limit != null` to generate the variant with subquery. Now it also checks for `offset > 0`
---
---
[EXPOSED-623](https://youtrack.jetbrains.com/issue/EXPOSED-623) Offset not applied in COUNT query
=> fix: EXPOSED-623 Offset not applied in COUNT query

docs/data-types.html, documentation-website/Writerside/topics/Data-Types.topic
Fixes a bug in the example code for `nullTransform` provided in the documentation.
- **What**: 
Fix Docs Example code
- **Why**:
If you try to use the example code as is, you'll get a compiler error. 
- **How**:
Change `transform()` to `nullTransform()`.
---
---
=> docs: EXPOSED-626 fix nullTransform example code

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/SequencesTests.kt
- **Why**:
The issue was that the `hashCode()` function was using `sequence` which invokes `autoincSeq` if `_sequence` is null, which then invokes `currentDialect`, and if this is not within a transaction, it will throw an error. This was introduced [here](https://github.com/JetBrains/Exposed/pull/2197).
- **How**:
The fix is to use `_sequence` instead of `sequence` when generating a hashcode.
---
---
=> fix: EXPOSED-621 IllegalStateException on accessing autoincrement column after insert using Entity

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Alias.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/AliasesTests.kt
In the case when select query has joined subquery (by `QueryAlias`) and that subquery has selected aliases (by `ExpressionAlias`) the `selectAll()` for the whole query would ignore that internal aliases.
- **What**: PR adds to select fields with pattern `${subQueryAlias}.${ExpressionAlias}`, it allows to get all the results from the query.
- **Why**: It happens because in moment of join to evaluate `fields` parameter only the values from `columns` parameter from `joinPart` is taken, but not all the `fields.
- **How**: Even if we take all the `fields` from subquery, it would not solve the problem, because these `fields` will not have (in the case of alias) connection to the `QueryAlias`. And what's worser it's not possible to differentiate them from other …
=> fix: EXPOSED-583 alias from inner query missing from outer select

documentation-website/Writerside/cfg/buildprofiles.xml
Add Algolia configuration for the search feature in Exposed Docs, as defined in [WH-5391](https://youtrack.jetbrains.com/issue/WH-5391).
Docs Ref: [EXPOSED-414](https://youtrack.jetbrains.com/issue/EXPOSED-414)
=> EXPOSED-414 Docs Search: Add Algolia parameters to Writerside config

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt
Small change that makes requirements of `ArrayColumnType` to `delegate` weaker
---
[EXPOSED-633](https://youtrack.jetbrains.com/issue/EXPOSED-633) Weak ArrayColumnType.delegate from ColumnType to IColumnType
=> chore: EXPOSED-633 Weak ArrayColumnType.delegate from ColumnType to IColumnType

documentation-website/Writerside/topics/DSL-CRUD-operations.topic
Update DSL Delete section:
- Include import statements in code blocks when using `deleteWhere` and `deleteIgnoreWhere`.
- Include  note about resolving `SqlExpressionBuilder` extension functions with inclusion of these imports.
- Fix incorrect `deleteAll` code block.
- Use named parameter in `Join.delete` to make sentence before code block more clear.
- **Why**: Recent versions of IntelliJ IDEA with K2 mode enabled no longer suggest the required imports (as part of context actions) for `deleteWhere` lambda functions (see issues below for full details & git hx). In the interim, especially for new users, documentation at least should be a guide on the necessary imports to fix any potential unresolved code errors.
---
Please mark the …
=> docs: EXPOSED-639 Add note about required imports with deleteWhere()

documentation-website/Writerside/cfg/buildprofiles.xml
[EXPOSED-601](https://youtrack.jetbrains.com/issue/EXPOSED-601) Replace the default Writerside favicon with the Exposed logo
---
=> docs: EXPOSED-601 Add Exposed logo favicon to Writerside config

build.gradle.kts, buildSrc/src/main/kotlin/org/jetbrains/exposed/gradle/TestDbDsl.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/h2/H2Tests.kt
Here is a small fix of our gradle test tasks. Before it was not possible to run the tests for particular H2 dialect (or the one without dialect). It was not always convenient for local testing and especially debugging.
With these changes for every database that has multiple dialects (H2_v1, H2_v2 actually) would be created separated gradle task with the name `test_${db}_${dialect}`. The task that would run tests with all the dialects (as it was working before) would be named `test_all_${db}`.
The full list of test tasks will look like:
```
test
test_all_h2_v1
test_all_h2_v2
test_h2_v1
test_h2_v1_mysql
test_h2_v2
test_h2_v2_mariadb
test_h2_v2_mysql
test_h2_v2_oracle
test_h2_v2_psql
test_h2_v2_sqlserver
test_mariadb_v2
test_mariadb_v3
test_mysql_v5
test_mysql_v8
test_oracle
test_postgres …
```
=> fix: EXPOSED-653 Split H2 gradle test task by dialects

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/transactions/experimental/Suspended.kt, exposed-tests/build.gradle.kts, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/postgresql/ConnectionPoolTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ThreadLocalManagerTest.kt, gradle/libs.versions.toml
**Summary of the change**: Regular transaction management allow callers to configure if new transactions should be read-only. This change adds the same behavior to suspendable transactions.
- **What**: A `readOnly` parameter has been added for `newSuspendTransaction`.
- **Why**: Regular transactions allow `readOnly` to be configured by callers. As per JetBrains Exposed documentation, this behavior is supposed to be the same for regular and suspendable transactions, but the parameter was missing for suspendable transactions.
- **How**: The parameter was added as optional (nullable with the default value set to `null`) to avoid breaking changes as much as possible. It is passed ahead to internal functions in order to create the transaction either as read-only based …
=> feat: EXPOSED-555 Allow read-only suspendable transactions

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Query.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/DistinctOnTests.kt
Here is the fix for the `count()` function that does not take into account the `distinctOn` parameter of the query.
By default `count()` performs `select(*) from <table>` query, In several case like queries with `distinct`, `limit` or `offset` parameters the `count()` would perform `select count(*) from (<the-whole-query>) subquery`.
The solution - trigger second option for `distinctOn` also.
---
---
- [EXPOSED-646](https://youtrack.jetbrains.com/issue/EXPOSED-646) count() voids distinctOn call on query
=> fix: EXPOSED-646 count() voids distinctOn call on query

documentation-website/Writerside/snippets/exposed-dao/src/main/kotlin/org/example/entities/EntityWithBase64.kt
Add missing import statements to documentation `exposed-dao` project file so that it can build & run successfully.
- **Why**:  A dependency was bumped recently in PR #2322 , so projects in documentation `snippets` were run to ensure the new version would not cause any issue. It was found that the `exposed-dao` project could not compile even without the bump due to unresolved object errors.
- **What**: `EntityWithBase64.kt` was throwing compile errors due to unresolved `Base64` object.
---
---
=> chore: Fix docs/snippets exposed-dao project build fail

documentation-website/Writerside/topics/Getting-Started-with-Exposed.topic
The builds for docs are failing due to markup validity issues. This PR fixes those.
=> docs: Fix markup validity issues in the Get started tutorial

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/transactions/ThreadLocalTransactionManager.kt
**Summary of the change**: Try to close connection in `ThreadLocalTransactionManager#connectionLazy` if setup fails
- **What**: The connection setup in `ThreadLocalTransactionManager#connectionLazy` now catches exceptions and attempts to close the database connection in case of an exception.
- **Why**: After the connection is obtained from the `Database`, Exposed tries to perform some initial setup before using the connection in a `Transaction`. If this setup fails, the connection is not closed (neither immediately nor when closing the transaction, because the connection is not stored inside the transaction due to `lazy` semantics), which in turn leads to connection leak.
- **How**: The setup code is wrapped in a `try-catch` block, which catches all exceptions …
=> fix: EXPOSED-651 Try to close connection in ThreadLocalTransactionManager#connectionLazy if setup fails

documentation-website/Writerside/topics/Breaking-Changes.md, exposed-dao/api/exposed-dao.api, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityClass.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/References.kt
**Summary of the change**: Raise deprecation level of `OptionalReferrers` from WARNING to ERROR
---
---
=> chore!: Raise deprecation level of `OptionalReferrers`

documentation-website/Writerside/snippets/exposed-dsl/README.md, documentation-website/Writerside/snippets/exposed-dsl/build.gradle.kts, documentation-website/Writerside/snippets/exposed-dsl/src/main/kotlin/org/example/App.kt, documentation-website/Writerside/snippets/exposed-dsl/src/main/kotlin/org/example/examples/CreateExamples.kt, documentation-website/Writerside/snippets/exposed-dsl/src/main/kotlin/org/example/examples/CustomSelectExamples.kt, documentation-website/Writerside/snippets/exposed-dsl/src/main/kotlin/org/example/examples/DeleteExamples.kt, documentation-website/Writerside/topics/DAO-Entity-definition.topic, documentation-website/Writerside/topics/DSL-CRUD-operations.topic, documentation-website/Writerside/topics/DSL-Querying-data.topic
Added SQLite and MySQL database configurations to the `exposed-dsl` project, used to run the following queries:
SQLite:
- `insertIgnore`
- `insertIgnoreAndGetId`
MySQL:
- `deleteIgnoreWhere`
- join update
- join delete
- query with index hint
---
[EXPOSED-661](https://youtrack.jetbrains.com/issue/EXPOSED-661)
=> chore: docs: EXPOSED-661 Support non-H2 compatible queries in the `exposed-dsl` snippets project

documentation-website/Writerside/topics/DSL-CRUD-operations.topic, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/MariaDBDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/ReturningTests.kt
**Summary of the change**: Returning clause was implemented for MariaDB
- **What**: Returning clause was implemented for MariaDB.
- **Why**: Returning clause is widely used, but MariaDB support was not included when `RETURNING` clause was introduced in either #2060 or #2061. 
- **How**: FunctionProvider.returning(...) was overridden in MariaDBFunctionProvider. Some tests were fixed and MariaDB is excluded from tests for `updateReturning()` because `UPDATE ... RETURNING` is not yet supported by the database ([open issue MDEV-5092](https://jira.mariadb.org/browse/MDEV-5092)).
---
---
=> feat: [MariaDB] Support RETURNING clause

README.md, documentation-website/Writerside/topics/Contributing.md, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Alias.kt
**Summary of the change**: Update documentation about YouTrack issue tracker & pull request guidelines.
- **Why**: Issues used to not have public visibility and this was addressed in PR #1798  by adding a note to the README explaining why a 404 message would be met when using an Exposed YouTrack link. Instead, the default visibility of issues has been made public  so none of our links should result in a 404 error for users.
**Other changes:**
- README PR section
- Updated to include details similar to more extensive list in Contribution page on site
- Contributing page
- Add more relevant links
- Use `main` instead of `master`
- Add YT links for existing issues
- Add how to format PR title & descriptions
- Include missing mention about breaking changes
- Added …
=> docs: EXPOSED-670 Adjust YouTrack issue visibility and PR guidelines

exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/DatabaseMigrationTests.kt
**Summary of the change**:  Fixed file separator in the test `testMigrationScriptDirectoryAndContent` to be system independent
---
---
=> test: Fix failing migration test for Windows

buildScripts/docker/docker-compose-sqlserver.yml
**Summary of the change**: Bump [SQL Server docker image](https://hub.docker.com/r/microsoft/azure-sql-edge) version to latest to rule it out as a possible cause for recent bouts of flaky TC builds that fail on task `:sqlserverComposeUp`.
- **Why**: TC [builds](https://exposed.teamcity.com/buildConfiguration/Exposed_Build) have been failing sporadically for the past 2 months without a clear pattern as to why. Please see [EXPOSED-683](https://youtrack.jetbrains.com/issue/EXPOSED-683/Flaky-outcomes-for-task-sqlserverComposeUp-on-TC-build) for more details, build links, internal threads, etc.
- **How**: Bump SQL Server image version to [latest](https://mcr.microsoft.com/v2/azure-sql-edge/tags/list) 2.0.0.
---
Affected …
=> test: EXPOSED-683 Fix flaky task sqlserverComposeUp on TC build

.github/workflows/docs-workflow.yml, build.gradle.kts, gradle.properties
- **Why**: This removes the warning that Dokka Gradle plugin V1 is deprecated.
- **How**: By following the guide [here](https://kotlinlang.org/docs/dokka-migration.html#enable-the-new-dokka-gradle-plugin).
---
---
=> build: Enable the new Dokka Gradle plugin

documentation-website/Writerside/topics/DSL-CRUD-operations.topic
**Summary of the change**: Switch link to `.select()` API reference in [DSL Read topic](https://jetbrains.github.io/Exposed/dsl-crud-operations.html#read)
- **Why**: Previous link went to [this deprecated method](https://jetbrains.github.io/Exposed/api/exposed-core/org.jetbrains.exposed.sql/select.html), when it should go to its [replacement](https://jetbrains.github.io/Exposed/api/exposed-core/org.jetbrains.exposed.sql/-column-set/select.html).
---
---
[EXPOSED-682](https://youtrack.jetbrains.com/issue/EXPOSED-682/Documentation-for-DSL-CRUD-operations-describes-the-Deprecated-Select-method.)
=> docs: EXPOSED-682 Switch api link from deprecated select()

documentation-website/Writerside/topics/DAO-CRUD-Operations.topic
Added an introduction and links to the methods described in the 'Sort results' section of DAO's 'CRUD operations' topic. This clarifies that the methods described come from the Kotlin standard library.
---
---
[EXPOSED-675](https://youtrack.jetbrains.com/issue/EXPOSED-675)
=> EXPOSED-675 Clarify that sort methods are from the Kotlin std lib

exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityClass.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/WarmUpLinkedReferencesTests.kt
**Summary of the change**: Provide a concise summary of this PR. Describe the changes made in a single sentence or short paragraph.
- **What**: The method `EntityClass::warmUpLinkedReferences()` was filling the cache by values from `references` argument and returning after that all the values from cache. As a result on the second call with a new list of `references` the wrong result was returned (all the values from the cache were returned)
- **How**: The solution is to filter cache values by the values from `references` argument and return the filtered result.
---
[EXPOSED-689](https://youtrack.jetbrains.com/issue/EXPOSED-689) warmUpLinkedReferences() should not return all the values from cache
=> EXPOSED-689 warmUpLinkedReferences() should not return all the values from cache

documentation-website/Writerside/topics/Breaking-Changes.md, exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Sequence.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/api/ExposedDatabaseMetadata.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/DatabaseDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/VendorDialect.kt, exposed-jdbc/api/exposed-jdbc.api, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcDatabaseMetadataImpl.kt, exposed-migration/src/main/kotlin/MigrationUtils.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/DatabaseMigrationTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/SequencesTests.kt
**Summary of the change**: SQL generated by `MigrationUtils` methods no longer includes `DROP` statements for every sequence that exists in a PostgreSQL database but not in an Exposed table. These statements are only generated if the database stored a relational dependency between the sequence and table (namely through a `SERIAL` column).
- **Why**: If `MigrationUtils.statementsRequiredForDatabaseMigration()` is called for only a subset of Exposed tables, it will invoke `checkUnmappedSequences()`, which disregards the specified tables and performs a metadata query for every single sequence (related or unrelated to any table) that exists in the database. The result of this query is used to check against mapped sequences, leading to undesirable `DROP` commands …
=> fix!: EXPOSED-691 [PostgreSQL] Restrict dropping unmapped sequences to related tables only

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/SchemaTests.kt
Check constraints created without user-specified names now use full table name with any dot-prefixed schema name replaced with underscores.
- **Why**:
A schema-prefixed table name currently uses the full name (with dot character) when generating a name for unnamed check constraints. This results in syntax exceptions or schema-not-found exceptions because something like this `Table("my_schema.my_table")` will name the constraint `check_my_schema.my_table_index_1`.
- **How**:
- Move common unquoting and `.` character replacement logic to private `Table` properties
- Use above logic when generating constraint name instead of raw `tableName`
- These constraints will be named like `check_my_schema_my_table_index_1` to match pattern used when …
=> fix: EXPOSED-695 DDL for unnamed check constraints fails when table has schema name

documentation-website/Writerside/topics/Breaking-Changes.md, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/DefaultsTest.kt, exposed-jodatime/src/test/kotlin/org/jetbrains/exposed/JodaTimeDefaultsTest.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/DefaultsTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateTableTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/NumericColumnTypesTests.kt
- **What**:
The SQL type of H2 Oracle Long type was changed. A CHECK constraint was also added for Oracle.
- **Why**:
1. H2 enforces the range on its own when BIGINT is used.
2. It is a preparation step for making detecting column type change for migration easier
---
---
=> chore!: Change H2 Oracle longType and longAutoincType from NUMBER(19) to BIGINT and add CHECK constraint in Oracle

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnDiff.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/DatabaseMigrationTests.kt
Add `ALTER COLUMN ... DROP DEFAULT` string to modified columns that lose their auto-increment status.
- **Why**:
When a column is modified to no longer be auto-incrementing, `MigrationUtils.statementsRequiredForDatabaseMigration()` currently generates statements to `ALTER` the column type and `DROP` the associated sequence. If these statements are actually executed using PostgreSQL, they will fail with an exception like:
```bash
ERROR: cannot drop sequence test_table_id_seq because other objects depend on it
Detail: default value for column id of table test_table depends on sequence test_table_id_seq
Hint: Use DROP ... CASCADE to drop the dependent objects too.. Statement(s): DROP SEQUENCE IF EXISTS test_table_id_seq 
```
Before …
=> fix: EXPOSED-696 [PostgreSQL] Drop of auto-increment sequence fails after column modified without dropping default

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Op.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/SQLExpressionBuilder.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/SelectTests.kt
Add `lessSubQuery`, `lessEqSubQuery`, `greaterSubQuery`, and `greaterEqSubQuery` operators
---
---
=> feat: EXPOSED-697 Add `lessSubQuery`, `lessEqSubQuery`, `greaterSubQuery`, and `greaterEqSubQuery` operators

exposed-spring-boot-starter/src/main/kotlin/org/jetbrains/exposed/spring/DatabaseInitializer.kt, exposed-spring-boot-starter/src/test/kotlin/org/jetbrains/exposed/spring/DatabaseInitializerTest.kt, exposed-spring-boot-starter/src/test/kotlin/org/jetbrains/exposed/spring/tables/NonObjectTable.kt
If `spring.exposed.generate-ddl` option is enabled, `DatabaseInitializer` discover exposed tables using following function.
```kotlin
fun discoverExposedTables(applicationContext: ApplicationContext, excludedPackages: List<String>): List<Table> {
val provider = ClassPathScanningCandidateComponentProvider(false)
provider.addIncludeFilter(AssignableTypeFilter(Table::class.java))
excludedPackages.forEach { provider.addExcludeFilter(RegexPatternTypeFilter(Pattern.compile(it.replace(".", "\\.") + ".*"))) }
val packages = AutoConfigurationPackages.get(applicationContext)
val components = packages.map { provider.findCandidateComponents(it) }.flatten()
return components.map { Class.forName(it.beanClassName).kotlin.objectInstance as Table }
// …
```
=> fix: EXPOSED-714 [exposed-spring-boot-starter] Fix NPE from DatabaseInitializer when non-object Table is defined

exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityCache.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityCacheTests.kt
If there are multiple entities that have different set of columns inside `writeValues` the flush of these entities could fail. The reason is the batch insert that will have different column sets for different entities.
It happens if the `id` field of that entity has client side default value. Otherwise entity's `writeValues` will be extended with default values inside `EntityClass::new()`. Actually, the check for that extending looks suspicious and has the following form:
```kotlin
if (entityId._value == null) {
val readValues = prototype._readValues!!
val writeValues = prototype.writeValues
table.columns.filter { col ->
col.defaultValueFun != null && col !in writeValues && readValues.hasValue(col)
}.forEach { col ->
writeValues[col as Column<Any?>] = readValues[col]
}
}
```
As I can see …
=> fix: EXPOSED-694 Entities insertion could fail if batches have different column sets

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/api/ExposedDatabaseMetadata.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/DatabaseDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/H2.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-jdbc/api/exposed-jdbc.api, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcDatabaseMetadataImpl.kt
**Summary of the change**: `exposed-core` no longer uses JDBC `DatabaseMetaData` to resolve metadata query results into `ReferenceOption` constants.
- **Why**:
In preparation for R2DBC, all JDBC specific metadata processing must be extracted from the core module. `DatabaseDialect.resolveRefOptionFromJdbc()` currently relies on JDBC `DatabaseMetaData` to find a matching `ReferenceOption` when table constraints are being generated by metadata query results.
- **How**:
-  Add new `ExposedDatabaseMetadata.resolveReferenceOption()` (so that it can be implemented for JDBC now and R2DBC later)
- Deprecate old `DatabaseDialect.resolveRefOptionFromJdbc()` and have it call the above.
- Move dialect specific logic to `exposed-jdbc`
---
Please mark the relevant options with …
=> refactor: EXPOSED-708 Remove JDBC DatabaseMetaData from exposed-core module

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/api/ExposedDatabaseMetadata.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/api/IdentifierManagerApi.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/H2.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLServerDialect.kt, exposed-jdbc/api/exposed-jdbc.api, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcDatabaseMetadataImpl.kt
**Summary of the change**: `vendors` package no longer has any metadata retrieved via `Transaction.exec()`. PR #2380 is open in conjunction to this one, since the extraction required a bit more.
- **Why**:
In preparation for R2DBC, instances of JDBC transaction-specific execution need to be removed from `exposed-core` and this focuses on the metadata retrieval queries in `vendors`, namely:
- H2 mode retrieval
- Query for all sequences in db
- **How**:
- Add new `ExposedDatabaseMetadatat.databaseDialectMode` property that can be called by `H2Dialect.h2Mode` and extract its logic to `exposed-jdbc`. 
- Add `isDotPrefixedAndUnquoted()` for identifier manager to be used when processing sequence results. Both this method and the 1 above are introduced as they will both …
=> refactor: EXPOSED-709 Remove plain SQL execution from core DatabaseDialect

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/DatabaseDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/MariaDBDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/DatabaseMigrationTests.kt
- **What**: Handle MariaDB sequence max value for versions earlier than 11.5.
- **Why**: According to the documentation [here](https://mariadb.com/kb/en/create-sequence/#maxvalue), MariaDB versions less than 11.5 have a max value for sequences that is lower than the one Exposed currently allows and that causes errors. Exposed allows a max of **9223372036854775807**, while MariaDB allows a max of **9223372036854775806**.
- **How**: I added a new property, `sequenceMaxValue`, to `DatabaseDialect`, and that is overridden in `MariaDBDialect` and used to set the `maxValue` of `Sequence` wherever a sequence is created.
**How to test:**
1. Go to `docker-compose-mariadb.yml`
2. Modify it to use this image: `image: mariadb:10.3.0`
3. Run `SequencesTests` and …
=> fix: EXPOSED-706 Handle MariaDB sequence max value for versions earlier than 11.5

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Database.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/MariaDBDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/MysqlDialect.kt
- **What**:
1. Handle MariaDB fractional seconds support since version 5.3.
2. Fixed mistake in KDocs referring to JDBC connector version instead of database version.
3. Fixed `isVersionCovers` function to handle comparison of 8.0 with 5.6.
4. Made the `MariaDBDialect` class extendable to be consistent with other dialect classes.
- **Why**:
According to the documentation [here](https://mariadb.com/kb/en/changes-improvements-in-mariadb-5-3/#datatypes), MariaDB introduced fractional seconds support in temporal data types from version 5.3. For MySQL, it's from version 5.6. Previously, Exposed was assuming it was 5.6 for both MariaDB and MySQL.
- **How**:
Modified `isFractionDateTimeSupported` in `MysqlDialect` to be open and overrided it in `MariaDBDialect` to …
=> fix: EXPOSED-707 Handle MariaDB fractional seconds support since version 5.3

exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/javatime/JavaDateColumnType.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/JavaTimeTests.kt, exposed-kotlin-datetime/src/main/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinDateColumnType.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinTimeTests.kt
**Summary of the change**: Fixed timestamp column not storing values in UTC time zone
- **Why**:
Instant is in UTC time zone, and the expected behaviour is that the timestamp column should store values in UTC time zone since it is without a user-specified time zone. Using the session or system time zone leads to unexpected behaviour like [this](https://kotlinlang.slack.com/archives/C0CG7E0A1/p1732897615084149).
- **How**:
Created new formatters that use the UTC timezone and used these formatters for timestamp column type.
In `JavaInstantColumnType` and `KotlinInstantColumnType`, I modified the `notNullValueToDB` function to return the formatted String for MySQL (excluding MariaDB) because there was an issue with MySQL 5 where it implicitly converted the value to …
=> fix: EXPOSED-718  Fix timestamp column not storing values in UTC time zone

exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/References.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/h2/EntityReferenceCacheTest.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityTests.kt
Both `BackReference` and `OptionalBackReference` classes use `Referrers` as their delegate class when `getValue()` is invoked. This means that, when there is no transaction context, the delegate correctly attempts to get a child value from the cache, but incorrectly assumes that it will be a `SizedIterable` (expected type for `Referrers`). Causing the retrieval to fail with something like:
```bash
org.jetbrains.exposed.sql.tests.shared.entities.EntityTestsData$BEntity cannot be cast to org.jetbrains.exposed.sql.SizedIterable
```
This fix ensures that an attempt is made to store the child value as a `LazySizedCollection` if it is not found to be a collection itself already.
Contains a test that reproduces a crash with eager loading of `backReferencedOn` (and `optionalBackReferencedOn`) …
=> fix: EXPOSED-704 ClassCastException when referencing an eager-loaded backReferencedOn with keepLoadedReferencesOutOfTransaction = true

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/BatchReplaceStatement.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/ReplaceStatement.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/MariaDBDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/MysqlDialect.kt
**Summary of the change**: Moved some things around to make the MariaDB code neater.
- **What**:
1. Override some functions in `MariaDBDialect` and `MariaDBFunctionProvider` to be able to remove the MariaDB checks done in `MysqlDialect` and `MysqlFunctionProvider` respectively.
2. Create new object `MariaDBDataTypeProvider` and move MariaDB-specific checks to it from `MysqlDataTypeProvider`.
- **Why**:
To reduce MariaDB checks in the MySQL code and separate their concerns where possible.
---
---
=> refactor: EXPOSED-722 Refactor MariaDB code to reduce checks in MySQL code and make it neater

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/FunctionProvider.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/InsertTests.kt
**Summary of the change**: Oracle insert statement now uses valid syntax for inserting only default values.
- **Why**:
Oracle currently generates a statement like `INSERT ... DEFAULT VALUES` if an insert operation is performed with no provided column set, like `Table.insert { }`.
This was not caught because there is actually no test for insertion of only truly database-side defaults; all tests either insert at minimum 1 column, an expression, or implicit auto-inc value for example.
The above syntax causes `java.sql.SQLSyntaxErrorException: ORA-00926: missing VALUES keyword` because it is not supported. [More details here](https://forums.oracle.com/ords/apexds/post/add-support-for-insert-default-values-7537)
- **How**: Oracle no longer relies solely on the default …
=> fix: EXPOSED-701 [Oracle] Insert into table using only database default values fails

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/MysqlDialect.kt, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcDatabaseMetadataImpl.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ConnectionTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/sqlite/ForeignKeyConstraintTests.kt
**Summary of the change**: Plain SQL in `MysqlDialect.fillConstraintCacheForTables()` is now in `exposed-jdbc` under `tableConstraints()`.
- **Why**: 
In preparation for R2DBC, JDBC-specific execution of plain SQL needs to be extracted from `exposed-core`. `MysqlDialect.fillConstraintCacheForTables()` currently executes a custom SQL query to retrieve foreign key constraints associated with the provided table. This is an override for a protected method that is only called in 1 place: `DatabaseDialect.columnConstraints()`. The latter is responsible for all `SchemaUtils` methods that check foreign key consistency.
- **How**:
- Query is now located in JDBC  `tableConstraints()`, because this is the metadata query called by the default implementation of …
=> refactor: EXPOSED-710 Move plain SQL for retrieving foreign keys from MysqlDialect

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/DatabaseDialect.kt, exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityClass.kt
**Summary of the change**: Edit KDocs of all `optionalBackReferencedOn()` overloads to clarify that it is possible to use even in non-nullable parent to non-nullable child relationships.
- **Why**: User mentioned that current KDocs makes it seem like using `optionalBackReferencedOn()` will not be possible if the child entity's table does not have a nullable reference. Existing tests for the function actually use a relationship example where the child table has a non-nullable reference. In this case, if no record in the child table references the parent entity and an attempt is made to retrieve a child value, `optionalBackReferencedOn()` simply returns `null`.
- **What**: Update all 3 variants of `optionalBackReferencedOn()` to mention that child reference can be …
=> docs: EXPOSED-705 Clarify optionalBackReferencedOn() usage in KDocs

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/DataTypeProvider.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/MariaDBDialect.kt, exposed-java-time/src/main/kotlin/org/jetbrains/exposed/sql/javatime/JavaDateColumnType.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/DefaultsTest.kt, exposed-kotlin-datetime/src/main/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/KotlinDateColumnType.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/DefaultsTest.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/sql/kotlin/datetime/MiscTableTest.kt
**Summary of the change**: Change timestamp column type for MariaDB from "DATETIME" to "TIMESTAMP"
- **Why**: Oracle, PostgreSQL are the only ones that use type "TIMESTAMP" for the timestamp column. MariaDB also has that type but "DATETIME" was being used instead for some reason.
- **How**: Added `timestampType()` in `DataTypeProvider` and overrided it in `MariaDBDataTypeProvider`.
Note: Using "TIMESTAMP" instead of "DATETIME" for MySQL 5 fails for `testUpdate02`.  The reason is that when updating another TIMESTAMP column, the first TIMESTAMP column's value is changing when retrieving it from the database because the database silently adds ON UPDATE CURRENTTIMESTAMP, so it's best to leave it as "DATETIME" for MySQL. I could also change it just for MySQL 8 in a …
=> chore!: EXPOSED-693 Change timestamp column type for MariaDB from "DATETIME" to "TIMESTAMP"

CHANGELOG.md, README.md
**Summary of the change**: Change urls in CHANGELOG & README from using 'https://jetbrains.github.io/Exposed' to using 'https://www.jetbrains.com/help/exposed'
- **Why**: Version releases usually come with a link to a changelog with breaking changes links that should be updated.
- **How**: All found instances have been switched to a url that is synced.
---
=> docs: Change urls for site pages in Changelog and ReadMe

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/UpsertTests.kt
- **What**: Upsert command fails for H2 if it contains array column.
- **Why**: The problem is that H2 has problems with type inference and fails with `Data conversion error converting` for such columns
- **How**: The only way I found is cast explicitly parameter markers for array values on H2 database. The list of particular types was added, and the test checks that everything works for these types, but in general such a cast could not work for other types (for example it was not working for BigDecimal)
---
---
[EXPOSED-719](https://youtrack.jetbrains.com/issue/EXPOSED-719) H2 upsert operation converts arrays to string
=> fix: EXPOSED-719 H2 upsert operation converts arrays to string

.github/workflows/commit-message-validation.yml, .github/workflows/pull-request-title-validation.yml
- **What**:
Ensure that all commit messages in a pull request, including the pull request's title, adhere to the Conventional Commits specification.
- **Why**:
The commit message rule is being forgotten sometimes, so it's better to automate this check. Ensuring we adhere to the Conventional Commits specification makes it easier to categorize the commits when preparing the ChangeLog for the release.
- **How**:
1. Added `commit-message-validation.yml` that runs a bash script to check the commit messages using a regular expression. The `validate-commits` job will run when the pull request is first opened and on every push.
2. Added `pull-request-title-validation.yml` that runs a bash script to check the pull request's title using a regular expression. The …
=> ci: EXPOSED-725 Enforce commit message rules

.github/workflows/commit-message-validation.yml, .github/workflows/pull-request-title-validation.yml, documentation-website/Writerside/topics/Breaking-Changes.md, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/H2.kt
**Summary of the change**: Change timestamp column type for H2 from "DATETIME(9)" to "TIMESTAMP(9)"
- **Why**:
1. Oracle, PostgreSQL, and MariaDB are the only ones that use type "TIMESTAMP" for the timestamp column. H2 also has that type but "DATETIME" was being used instead for some reason.
2. This is a preparation step that makes detecting column type change for migration easier.
- **How**:
Overrided `timestampType()` in `H2DataTypeProvider`
⚠️ Note: Some issues were discovered and fixed in the Pull Request Title Validation and Commit Message Validation scripts.
---
---
=> chore!: EXPOSED-727 Change timestamp column type for H2 from "DATETIME(9)" to "TIMESTAMP(9)"

exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/OracleDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/DeleteTests.kt
**Summary of the change**: Using `Table.delete(limit = #)` with Oracle no longer throws unsupported exception.
- **Why**:
Oracle does not support the `LIMIT` syntax, but it is still possibly to limit the number of rows on which an update or delete operation takes place. This can be done using the `ROWNUM` [pseudocolumn](https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/ROWNUM-Pseudocolumn.html), which is the current implementation for `Table.update(limit = #)`. For some reason, this syntax was never extended to `DELETE`.
- **How**:
- Extract common string building logic to private function
- Use the above in `delete()` instead of throwing
---
--- …
=> feat: EXPOSED-729 [Oracle] Allow setting limit with DELETE

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Queries.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/api/ExposedDatabaseMetadata.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/DatabaseDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/PostgreSQL.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/SQLiteDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/VendorDialect.kt, exposed-jdbc/api/exposed-jdbc.api, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcDatabaseMetadataImpl.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/DeleteTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/UpdateTests.kt
**Summary of the change**: Deprecate `SQLiteDialect.ENABLE_UPDATE_DELETE_LIMIT` and replace with metadata functions that perform the same query, but which can be extracted into separate modules when R2DBC is introduced.
- **Why**:
`SQLiteDialect` has a companion property that sends a low-level JDBC connection query to check if `LIMIT` clause is allowed in either update or delete statements. The latter is only possible if SQLite is built from the source with the compile-time flag `ENABLE_UPDATE_DELETE_LIMIT` enabled ([source docs](https://www.sqlite.org/lang_update.html#optional_limit_and_order_by_clauses)).
In preparation for R2DBC, this query needs to be removed from `exposed-core` so that it can be implemented in both a blocking and non-blocking way. …
=> refactor: EXPOSED-728 [SQLite] Remove ENABLE_UPDATE_DELETE_LIMIT metadata check from core function provider

documentation-website/Writerside/topics/Breaking-Changes.md, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/NumericColumnTypesTests.kt
- **What**: Fix inconsistent CHECK constraint names for UShort and UInt columns
- **Why**:
UByte -> `chk_tester_unsigned_byte_column_name` ✅
UShort -> `chk_tester_unsigned_column_name` ❌ should be `chk_tester_unsigned_short_column_name`
UInt -> `chk_tester_unsigned_column_name` ❌ should be `chk_tester_unsigned_integer_column_name`
---
---
=> chore!: EXPOSED-741 Fix inconsistent CHECK constraint names for UShort and UInt columns

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/NumericColumnTypesTests.kt
- **Why**: Because the length limit of identifiers is being reached sometimes with the CHECK constraint name that Exposed generates, so it is useful for users sometimes to be in control of the name.
- **How**: Added a nullable String parameter `checkConstraintName` to `long()` column.
---
---
=> feat: EXPOSED-742 Allow customizing the CHECK constraint name of `long()` column

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/ForUpdateOption.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/mysql/MysqlTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/postgresql/PostgresqlTests.kt
**Summary of the change**: Adds the `SKIP LOCKED` and `NO WAIT` modes when using `SELECT ... FOR UPDATE`. Also adds tests to make sure that the queries are generated as expected.  Breaking change: Moved ForUpdateBase outside Postgres.
- **What**: 
- Added the `MODE` option for MySQL, that can be used to define modes for ForUpdate and ForShare.
- Refactored the ForUpdateOption class so that some of the methods are available across DBs
- The ForUpdateBase class has been moved out of Postgres, which is a breaking change.
- Mostly repackages the tests for Postgres.
- **Why**: 
- Since MySQL 8.0.1, there has been support for ForUpdate and ForShare modes. 
- https://dev.mysql.com/doc/refman/8.0/en/innodb-locking-reads.html
- However, the implementation only supported …
=> feat!: EXPOSED-740  Add support for modes (SKIP LOCKED or NOWAIT) with ForUpdate and ForShare Option for MySQL

documentation-website/Writerside/topics/Frequently-Asked-Questions.md
**Summary of the change**: Fix text that says Exposed is not an official JetBrains library
---
---
=> docs: Fix text that says Exposed is not an official JetBrains library

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/dml/ColumnWithTransformTest.kt
`ColumnWithTranform` currently doesn't forward `readObject` to the delegate. This can cause exceptions to be thrown after (not) reading special objects from the database driver.
[EXPOSED-761](https://youtrack.jetbrains.com/issue/EXPOSED-761/Column-transform-doesnt-forward-readObject-to-the-delegate) explains this issue with more details and gives an example.
---
(possibly other ones as well, untested)
---
[EXPOSED-761](https://youtrack.jetbrains.com/issue/EXPOSED-761/Column-transform-doesnt-forward-readObject-to-the-delegate)
=> fix: EXPOSED-761 Forward ColumnWithTransform.readObject to delegate

exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityClass.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/DefaultsTest.kt
**Summary of the change**: Changed the new function for Entities under EntityClass to explicitly insert default values (when provided for columns that have default values) even when an ID is provided. This should not have any impact other than the generated SQL explicitly including columns with default values if they are specified.
- **What**: Entity insertion via new will generate SQL that will explicitly insert columns whose values match their default value.
- **Why**: To align the DAO SQL generation with the DSL, which will explicitly insert columns whose values match their default value.
- **How**: Removed an _if_ statement that prevented explicit insertion if an ID was provided to the new() function
--- …
=> fix: EXPOSED-713 Allow entity batchInsert() to generate SQL for column values that match the default

buildScripts/docker/docker-compose-mariadb.yml, exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/ColumnType.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/types/UUIDColumnTypeTests.kt
When working with MariaDB 10.7+ which provides a native UUID data type, Exposed SQL currently handles it incorrectly. When retrieving data from a MariaDB UUID field, it incorrectly processes it as a byte array, when it should be handled as a string representation of the UUID.
---
---
[EXPOSED-762](https://youtrack.jetbrains.com/issue/EXPOSED-762) Mariadb improper UUID type for dialect
=> fix: EXPOSED-762 [MariaDB] Fix UUIDColumType to make it working with own UUID type

exposed-r2dbc/api/exposed-r2dbc.api, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/R2dbcDatabase.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/R2dbcDatabaseConfig.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/mappers/ArrayTypeMapper.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/mappers/BinaryTypeMapper.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/mappers/DateTimeTypeMapper.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/mappers/DefaultTypeMapper.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/mappers/ExposedColumnTypeMapper.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/mappers/PostgresSpecificTypeMapper.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/mappers/PrimitiveTypeMapper.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/mappers/R2dbcTypeMapping.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/mappers/TypeMapper.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/mappers/ValueContainer.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/mappers/ValueTypeMapper.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/statements/InsertSuspendExecutable.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/statements/R2dbcConnectionImpl.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/statements/R2dbcPreparedStatementImpl.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/statements/api/R2dbcResult.kt
`TypeMapperRegistry` class was  abstracted with 2 interfaces `R2dbcTypeMapping` and `R2dbcRegistryTypeMapping`.
The first one `R2dbcTypeMapping` is the base class for any implementation for r2dbc type mapping that we expect from the user. It contains 2 methods `setValue` and `getValue`.
The second one `R2dbcRegistryTypeMapping` is a more specific type mapping that is aware of `TypeMapper` and extends `TypeMapperRegistry`. It has method `register` to add new type mappers. 
The old class `TypeMapperRegistry` become `R2dbcRegistryTypeMappingImpl` and implements `R2dbcRegistryTypeMapping`. 
So that confiuguration allows to write own type mappers, and use our `R2dbcRegistryTypeMappingImpl`, or create complete own type mapping based on anything else.
I'm not sure about naming, I personally …
=> fix: Ordering of type mappers, interface for type mappers registry

exposed-r2dbc-tests/src/test/kotlin/org/jetbrains/exposed/v1/r2dbc/sql/tests/shared/ddl/EnumerationTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/v1/tests/shared/ddl/EnumerationTests.kt
**Summary of the change**: Enable `TestDB.POSTGRESQL` in all existing R2DBC `customEnumeration()` tests
- **Why**: Tests with `customEnumeration()` were not running on PostgreSQL because they would fail with `Cannot decode parameter of type...` errors. This is because PostgreSQL Enum types require special [enum codec registration on r2dbc connection](https://github.com/pgjdbc/r2dbc-postgresql?tab=readme-ov-file#postgres-enum-types).
- **What**:
- Create `R2dbcDatabase.connect()` instance that uses PG-specific connection factory with `.codecRegistrar()` configuration.
- Use this instance for any connections that require binding a Kotlin Enum constant to a statement parameter 
---
=> test: Enable PostgreSQL tests for R2DBC customEnumeration()

exposed-core/src/main/kotlin/org/jetbrains/exposed/v1/core/SchemaUtilityApi.kt, exposed-tests/build.gradle.kts, exposed-tests/src/test/kotlin/org/jetbrains/exposed/v1/tests/shared/ddl/DatabaseMigrationTests.kt
The issue occurs when MigrationUtils attempts to generate a migration for a column that has a default value in the database but lacks a default value in the table object (though it's marked as `databaseGenerated`).
The `databaseGenerated` flag indicates that the column's value will be generated by the database (through a default value, trigger, or other mechanism), but we cannot define this value in the table object itself.
The solution is to skip default value validation for `databaseGenerated` columns. Otherwise, the migration utilities will attempt to remove the existing default value.
---
---
[EXPOSED-806](https://youtrack.jetbrains.com/issue/EXPOSED-806) Inconsistent migration of JSON generated columns on Postgres
=> fix: EXPOSED-806 Inconsistent migration of JSON generated columns on Postgres

exposed-r2dbc/api/exposed-r2dbc.api, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/mappers/DateTimeMySqlTypeMapper.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/mappers/DateTimeNullTypeMapper.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/mappers/DateTimeOracleTypeMapper.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/mappers/DateTimeTypeMapper.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/mappers/DefaultTypeMapper.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/mappers/TypeMapper.kt, exposed-r2dbc/src/main/resources/META-INF/services/org.jetbrains.exposed.v1.r2dbc.mappers.TypeMapper
Update for r2dbc type mappers, that splits `DateTimeTypeMapper` into several smaller type mappers, that ordered by `priority`.
---
=> fix: Split date/time type mapper

exposed-spring-boot-starter/src/main/kotlin/org/jetbrains/exposed/v1/spring/boot/ExposedAotContribution.kt
Updated resource paths in ExposedAotContribution to match the current package structure, ensuring proper GraalVM native image support for Spring Boot applications using Exposed.
- **What**: Updated the resource paths in the `registerResourceHints()` method of `ExposedAotContribution` class to match the current package structure:
1. Changed `org.jetbrains.exposed.v1.dao.id.EntityIDFactory` to `org.jetbrains.exposed.v1.core.dao.id.EntityIDFactory`
2. Changed `org.jetbrains.exposed.v1.sql.DatabaseConnectionAutoRegistration` to `org.jetbrains.exposed.v1.jdbc.DatabaseConnectionAutoRegistration`
- **Why**: The package structure of the Exposed framework has been reorganized, with `EntityIDFactory` moving from `dao.id` to `core.dao.id` and …
=> fix: Update resource paths in ExposedAotContribution to match current package structure

documentation-website/Writerside/topics/Breaking-Changes.md, exposed-r2dbc/api/exposed-r2dbc.api, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/transactions/R2dbcTransactionUtils.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/transactions/TransactionManager.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/transactions/mtc/MappedThreadContext.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/transactions/mtc/MappedTransactionContext.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/transactions/mtc/ThreadLocalMap.kt
**Summary of the change**: Make `ThreadLocalMap` internal & move it and associated classes under `transactions` package
- **Why**: `ThreadLocalMap` (a public class) is only used by `MappedThreadContext` (an internal object), which is only used by `MappedTransactionContext` (an internal object). These 3 objects are the only ones in the `r2dbc.mtc` package and only the latter is actually used by a single public object, `TransactionManager`.
- **What**:
- `ThreadLocalMap` made internal
- Now all internal objects moved to directly where they are used, as a utility subpackage: `r2dbc.transactions.mtc`
---
=> refactor!: Make ThreadLocalMap internal & move mtc package into transactions

documentation-website/Writerside/topics/Breaking-Changes.md, exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/v1/core/Transaction.kt, exposed-jdbc/api/exposed-jdbc.api, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/v1/jdbc/JdbcTransaction.kt, exposed-r2dbc-tests/src/test/kotlin/org/jetbrains/exposed/v1/r2dbc/sql/tests/shared/ParameterizationTests.kt, exposed-r2dbc/api/exposed-r2dbc.api, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/R2dbcTransaction.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/v1/tests/demo/dao/SamplesDao.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/v1/tests/shared/ParameterizationTests.kt, spring-transaction/src/main/kotlin/org/jetbrains/exposed/v1/spring/transaction/SpringTransactionManager.kt
**Summary of the change**: `JdbcTransaction.addLogger()` and `R2dbcTransaction.addLogger()` replaced with class methods.
- **Why**:
Prior to 1.0.0, `Transaction.addLogger()` existed as an extension function ins `SQLLog.kt`. Its logic called `registerInterceptor()`, which was a public `Transaction` method that relied on [an internal ArrayList](https://github.com/JetBrains/Exposed/blob/main/exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/v1/jdbc/JdbcTransaction.kt#L64). This was fine because everything was together in `exposed-core`.
After 1.0.0, the original was removed and replaced with 2 extension functions, one in the jdbc and r2dbc module. This was done because the internal array list was maintained, so `registerInterceptor()` had to be removed from …
=> refactor!: Move addLogger() to exposed-core Transaction class

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/v1/core/vendors/PostgreSQL.kt
Override `supportsSelectForUpdate` parameter for `PostgreSQLDialect`
---
---
[EXPOSED-827](https://youtrack.jetbrains.com/issue/EXPOSED-827) forUpdate() query method doesn't add actual `FOR UDPATE` modifier
=> fix: EXPOSED-827 forUpdate() query method doesn't add actual `FOR UDPATE` modifier

exposed-core/src/main/kotlin/org/jetbrains/exposed/v1/core/vendors/SQLServerDialect.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/v1/tests/h2/H2Tests.kt
See https://youtrack.jetbrains.com/issue/EXPOSED-768. Exposed does not currently support the inserts of UUIDs into columns of type BINARY(16) in H2.
This PR attempts to use the UUID type instead of String when inserting java.util.UUIDs into the database.
---
---
https://youtrack.jetbrains.com/issue/EXPOSED-768
https://youtrack.jetbrains.com/issue/EXPOSED-116
=> fix: EXPOSED-768 UUID inserts into BINARY(16) column types in H2

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/v1/core/statements/IStatementBuilder.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/v1/core/statements/UpsertStatement.kt, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/v1/jdbc/Queries.kt, exposed-r2dbc-tests/src/test/kotlin/org/jetbrains/exposed/v1/r2dbc/sql/tests/shared/dml/UpsertTests.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/Queries.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/v1/tests/shared/dml/UpsertTests.kt
Update `where` parameter in upsert statement to allow use `insertValue(column)` also in the `where` condition.
---
---
[EXPOSED-811](https://youtrack.jetbrains.com/issue/EXPOSED-811) argument "where" in "batchUpsert" have no way to use it
=> fix: EXPOSED-811 argument "where" in "batchUpsert" have no way to use it

documentation-website/Writerside/topics/Migrations.md, exposed-migration/api/exposed-migration.api, exposed-migration/src/main/kotlin/org/jetbrains/exposed/v1/migration/MigrationUtilityApi.kt, exposed-migration/src/main/kotlin/org/jetbrains/exposed/v1/migration/MigrationUtils.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/v1/tests/shared/ddl/DatabaseMigrationTests.kt
Migration utils already had a method `dropUnmappedColumnsStatements` to get the statements to drop columns that exist in database but not defined in the code. 
With these PR two new methods `dropUnmappedIndices` and `dropUnmappedSequences` would be added. These methods allow to get statements to drop unmapped indices and sequences respectively
---
---
[EXPOSED-826](https://youtrack.jetbrains.com/issue/EXPOSED-826) Extend MigrationUtils with dropUnmappedIndices and dropUnmappedSequence
=> feat: EXPOSED-826 Extend MigrationUtils with dropUnmappedIndices and dropUnmappedSequence

documentation-website/Writerside/topics/Migration-Guide-1-0-0.md, exposed-core/src/main/kotlin/org/jetbrains/exposed/v1/core/ColumnType.kt, exposed-jdbc/api/exposed-jdbc.api, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/v1/jdbc/statements/jdbc/JdbcResult.kt
**Summary of the change**: Add `RowApi.origin` to `exposed-jdbc` to avoid need to cast when overriding `IColumnType.readObject()`.
- **Why**:
Parameter type change of `readObject()` is unavoidable at this point and already documented: [Migration Guide](https://www.jetbrains.com/help/exposed/migration-guide-1-0-0.html#read-object)
If a custom column type is implemented that requires this method override, the best way to ensure common JDBC/R2DBC compatibility is to use common `RowApi.getObject()`.
**BUT,** if there is no intention to share code, or the user wants to continue to use the original JDBC `ResultSet` code, the only way to accomplish this would be to cast and access the underlying result:
```kotlin
// PRE-V1
override fun readObject(rs: ResultSet, index: …
```
=> fix: readObject() parameter change requires casting to keep using

documentation-website/Writerside/topics/Breaking-Changes.md, exposed-kotlin-datetime/api/exposed-kotlin-datetime.api, exposed-kotlin-datetime/build.gradle.kts, exposed-kotlin-datetime/src/main/kotlin/org/jetbrains/exposed/v1/datetime/KotlinDateColumnType.kt, exposed-kotlin-datetime/src/main/kotlin/org/jetbrains/exposed/v1/datetime/KotlinDateFunctions.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/v1/datetime/DateTimeLiteralTest.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/v1/datetime/DefaultsTest.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/v1/datetime/KotlinTimeTests.kt, exposed-kotlin-datetime/src/test/kotlin/org/jetbrains/exposed/v1/datetime/MiscTableTest.kt, exposed-r2dbc-tests/build.gradle.kts, exposed-r2dbc-tests/src/test/kotlin/org/jetbrains/exposed/v1/r2dbc/sql/tests/kotlindatetime/DateTimeLiteralTest.kt, exposed-r2dbc-tests/src/test/kotlin/org/jetbrains/exposed/v1/r2dbc/sql/tests/kotlindatetime/DefaultsTest.kt, exposed-r2dbc-tests/src/test/kotlin/org/jetbrains/exposed/v1/r2dbc/sql/tests/kotlindatetime/KotlinTimeTests.kt, exposed-r2dbc-tests/src/test/kotlin/org/jetbrains/exposed/v1/r2dbc/sql/tests/kotlindatetime/MiscTableTest.kt, exposed-r2dbc-tests/src/test/kotlin/org/jetbrains/exposed/v1/r2dbc/sql/tests/shared/dml/InsertTests.kt, exposed-tests/build.gradle.kts, exposed-tests/src/test/kotlin/org/jetbrains/exposed/v1/tests/shared/ddl/DatabaseMigrationTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/v1/tests/shared/dml/InsertTests.kt, gradle/libs.versions.toml
Migration of `kotlinx.datetime` from version 6 to version 7
---
---
[EXPOSED-813](https://youtrack.jetbrains.com/issue/EXPOSED-813) When is the plan to migrate kotlinx.datetime.Instant to kotlin.time.Instant?
=> chore!: EXPOSED-813 When is the plan to migrate kotlinx.datetime.Instant to kotlin.time.Instant?

exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/statements/InsertSuspendExecutable.kt
The fix for one of r2dbc todos that complained that it's necessary to remove result of the last segment from batch insert.
---
---
=> fix: Fix the duplicated segments on SQLServer dialect

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/v1/core/vendors/H2.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/v1/core/vendors/MysqlDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/v1/core/vendors/OracleDialect.kt
Enable "SELECT FOR UPDATE" for the several applicable dialects  
It turned out that it's impossible to apply select for update for non-postgesql dialects, even though they are declared in `ForUpdateOption`
---
---
=> fix: Enable "SELECT FOR UPDATE" for the several applicable dialects

documentation-website/Writerside/topics/Breaking-Changes.md, exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/v1/core/statements/DeleteStatement.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/v1/core/statements/StatementBuilder.kt, exposed-jdbc/api/exposed-jdbc.api, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/v1/jdbc/ExplainBlockingExecutable.kt, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/v1/jdbc/statements/BlockingExecutable.kt, exposed-r2dbc-tests/src/test/kotlin/org/jetbrains/exposed/v1/r2dbc/sql/tests/shared/TransactionExecTests.kt, exposed-r2dbc-tests/src/test/kotlin/org/jetbrains/exposed/v1/r2dbc/sql/tests/shared/dml/ExplainTests.kt, exposed-r2dbc/api/exposed-r2dbc.api, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/ExplainSuspendExecutable.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/Queries.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/statements/SuspendExecutable.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/v1/tests/shared/TransactionExecTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/v1/tests/shared/dml/ExplainTests.kt
**Summary of the change**: Rename `IStatementBuilder` to `StatementBuilder` and replace usage and add way to get built-in executable instance from statement instance.
- **What**:
- Rename `IStatementBuilder` to `StatementBuilder` + deprecate original
- Change  related usages in `buildStatement()` and `explain()`
- Update KDocs
- Add `Statement.toExecutable()` in both modules to avoid user needing to know what executable classes are
- Add unit tests
Documentation update -> PR #2563 
---
=> refactor!: Rename IStatementBuilder interface and add executable converter

README.md
**Summary of the change**: Update content of project README to match V1 changes to modules, packages, and associated links.
- **Why**: It was brought up that many of the new-ish packages are not listed, nor are new site links, and some current content is broken/incorrect.
- **What**:
- Add links to Exposed website
- Edit intro to mention R2DBC support
- Replace majority of dependency section with link to identical details in docs
- Add full module list with dependencies that were missing
- Move tutorial link to samples section
- Replace links section with documentation, remove duplicates, and fix broken url
- Replace community section with reporting and support and move details about issue tracker there
- Fix incorrect import paths in example code
- Minor …
=> docs: Update root README with new links and modules

exposed-r2dbc-tests/src/test/kotlin/org/jetbrains/exposed/v1/r2dbc/sql/tests/h2/MultiDatabaseTest.kt, exposed-r2dbc-tests/src/test/kotlin/org/jetbrains/exposed/v1/r2dbc/sql/tests/shared/ConnectionTests.kt, exposed-r2dbc-tests/src/test/kotlin/org/jetbrains/exposed/v1/r2dbc/sql/tests/shared/SchemaTests.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/R2dbcDatabase.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/statements/R2dbcConnectionImpl.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/vendors/metadata/OracleMetadata.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/v1/tests/shared/ConnectionTests.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/v1/tests/shared/SchemaTests.kt
**Summary of the change**: Fix `R2dbcDatabase.name` logic to no longer return database name + all connection url property key-value pairs.
- **Why**:
In H2 JDBC, calling `Database.name` returns the full prefix of the connection url, like `jdbc:h2:mem:regular`. It is assumed that this is the original return value because of the potential variety of H2 connection url string prefixes.
With R2DBC, calling `R2dbcDatabase.name` returns the database name, but with every single property following attached, like `regular;MODE-...;DB_CLOSE_DELAY=...`. The full prefix is not returned because h2-r2dbc urls always have a `///` delimiter, regardless of connection type.
The same parsing logic used for JDBC does not work for R2DCB because the url being used is the user-defined …
=> fix: [H2] R2dbcDatabase.name parsing error returns all url properties

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/v1/core/statements/api/ResultApi.kt, exposed-jdbc/api/exposed-jdbc.api, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/v1/jdbc/statements/jdbc/JdbcResult.kt, exposed-json/api/exposed-json.api, exposed-json/build.gradle.kts, exposed-json/src/main/kotlin/org/jetbrains/exposed/v1/json/JsonColumnType.kt, exposed-json/src/main/kotlin/org/jetbrains/exposed/v1/json/JsonConditions.kt, exposed-json/src/test/kotlin/org/jetbrains/exposed/v1/json/JsonBColumnTests.kt, exposed-json/src/test/kotlin/org/jetbrains/exposed/v1/json/JsonColumnTests.kt, exposed-r2dbc-tests/build.gradle.kts, exposed-r2dbc/api/exposed-r2dbc.api, exposed-r2dbc/build.gradle.kts, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/mappers/PostgresSpecificTypeMapper.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/statements/api/R2dbcResult.kt
**Summary of the change**: Remove all dependencies on PG-JDBC from both `exposed-json` and R2DBC modules.
- **Why**: If a project is started with Exposed + PostgreSQL R2DBC + JSON, a runtime dependency on PostgreSQL JDBC is required; otherwise at some point most likely a `NoClassDefFoundError` for `PGobject` will be experienced. This occurs because `JsonColumnType` logic relies on JDBC `PGobject` to send and retrieve JSON values.
- **How**:
-  All uses of `PGobject` removed from both `exposed-json` and `exposed-r2dbc`
- `JsonColumnType` now treats JSON values directly as a String by casting `::json` when sending to the database and retrieving directly as a string when reading results.
- Surprisingly, `ResultSet.getString(index)` is not equivalent to …
=> fix: EXPOSED-801 NoClassDefFoundError when using exposed-json with pg-r2dbc dependency only

exposed-java-time/src/main/kotlin/org/jetbrains/exposed/v1/javatime/JavaDateColumnType.kt, exposed-r2dbc-tests/src/test/kotlin/org/jetbrains/exposed/v1/r2dbc/sql/tests/javatime/JavaTimeTests.kt, exposed-r2dbc-tests/src/test/kotlin/org/jetbrains/exposed/v1/r2dbc/sql/tests/kotlindatetime/KotlinTimeTests.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/mappers/DateTimeOracleTypeMapper.kt
Here is the solving of yet another r2dbc todo item.
The method `JavaLocalTimeColumnType::notNullValueToDB()` is slightly cleaned by extracting the logic to type mappers layer.
---
=> chore: Move logic from JavaLocalTimeColumnType to type mappers

exposed-migration/build.gradle.kts
**Summary of the change**: Expose the jdbc module with dependencies on `exposed-migration`.
- **Why**: After many core classes were extracted to `exposed-jdbc`, a `compileOnly()` dependency was included in `exposed-migration`.
---
---
[EXPOSED-841](https://youtrack.jetbrains.com/issue/EXPOSED-841/Enable-exposed-migration-that-does-not-rely-on-JDBC)
=> build: Include api(exposed-jdbc) dependency with exposed-migration

exposed-spring-boot-starter/build.gradle.kts, spring-transaction/build.gradle.kts
**Summary of the change**: Expose the jdbc module with dependencies on `spring-transaction`.
- **Why**: After many core classes were extracted to `exposed-jdbc`, a `compileOnly()` dependency was included in both  `spring-transaction` and `exposed-spring-boot-starter` to allow them to work. More than likely, a dependency on these modules will still require the user to add a dependency on `exposed-jdbc` to get other aspects of previously core code to work. So the dependency has been switched to `api()` in `spring-transaction`, on which `exposed-spring-boot-starter` already has a full dependency.
---
---
[EXPOSED-818](https://youtrack.jetbrains.com/issue/EXPOSED-818/Add-SpringTransactionManager-and-autoconfiguration-compa …
=> build: Include api(exposed-jdbc) dependency with spring-transaction

exposed-core/src/main/kotlin/org/jetbrains/exposed/v1/core/DatabaseConfig.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/v1/core/statements/InsertStatement.kt, exposed-java-time/src/test/kotlin/org/jetbrains/exposed/v1/javatime/DateTimeLiteralTest.kt, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/v1/jdbc/transactions/experimental/Suspended.kt, exposed-r2dbc-tests/src/test/kotlin/org/jetbrains/exposed/v1/r2dbc/sql/tests/shared/dml/FetchBatchedResultsTests.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/Queries.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/Query.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/statements/InsertSuspendExecutable.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/statements/R2dbcConnectionImpl.kt
**Summary of the change**: Remove some of the existing TODOs based on planning discussion
- **Why**: These TODOs fall into 1 of 3 categories:
- Agreed to be obsolete or no longer worth pursuing
- Little to be done on our end, so known limitations have been documented
- Further steps or refactorings may be addressed post-V1 & YT tickets have been created
---
=> chore: Remove obsolete or reprioritized Todos

documentation-website/Writerside/cfg/buildprofiles.xml
This configures a feedback widget that will be displayed on the bottom of each documentation page. Users will be able to leave feedback or report issues. By doing so a new ticket will be created  in the EXPOSED project on YouTrack.
[EXPOSED-850](https://youtrack.jetbrains.com/issue/EXPOSED-850) Add feedback widget to Exposed docs
=> docs: build: EXPOSED-850 Add configuration for feedback widget

exposed-core/api/exposed-core.api, exposed-core/src/main/kotlin/org/jetbrains/exposed/v1/core/statements/api/ExposedDatabaseMetadata.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/v1/core/vendors/OracleDialect.kt, exposed-jdbc/api/exposed-jdbc.api, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/v1/jdbc/Database.kt, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/v1/jdbc/statements/jdbc/JdbcDatabaseMetadataImpl.kt, exposed-r2dbc/api/exposed-r2dbc.api, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/statements/api/R2dbcDatabaseMetadataImpl.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/transactions/R2dbcTransactionInterface.kt
**Summary of the change**: Remove some of the existing TODOs based on most recent planning discussion
- **Why**: These TODOs fall into 1 of 2 categories:
- Agreed to be obsolete or no longer worth pursuing
- Further steps or refactorings may be addressed post-V1 & YT tickets have been created
---
=> chore: Remove more obsolete TODOs

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/commit-message-validation.yml, README.md
**Summary of the change**: Changed source ref and link for GH README 'Maven Central' badge to show latest release.
- **Why**: Previous version was relying on [search.maven.org](https://search.maven.org/artifact/org.jetbrains.exposed/exposed-core/1.0.0-beta-4/jar?eh=), which only has up to version 1.0.0-beta-4 following recent changes to publishing process. Switched to rely on [central.sonatype.com](https://central.sonatype.com/namespace/org.jetbrains.exposed) instead.
---
=> chore: Fix broken maven central badge

documentation-website/Writerside/topics/Breaking-Changes.md, exposed-core/src/main/kotlin/org/jetbrains/exposed/v1/core/statements/api/ExposedDatabaseMetadata.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/v1/core/vendors/DatabaseDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/v1/core/vendors/H2.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/v1/core/vendors/MysqlDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/v1/core/vendors/OracleDialect.kt, exposed-core/src/main/kotlin/org/jetbrains/exposed/v1/core/vendors/PostgreSQL.kt, exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/v1/jdbc/Query.kt, exposed-r2dbc-tests/src/test/kotlin/org/jetbrains/exposed/v1/r2dbc/sql/tests/shared/dml/SelectTests.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/Query.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/v1/tests/shared/dml/SelectTests.kt
Parameter `supportsSelectForUpdate` from `DatabaseDialect` was deprecated and should not be used. The parameter was moved to `JdbcExposedDatabaseMetadata`/`R2dbcExposedDatabaseMetadata` classes. 
It could be used with call `TransactionManager.current().connection.metadata { supportsSelectForUpdate }` now.
---
- [] SQLite
---
[EXPOSED-844](https://youtrack.jetbrains.com/issue/EXPOSED-844) supportsSelectForUpdate parameter from DatabaseDialect should be deprecated
=> chore!: EXPOSED-844 supportsSelectForUpdate parameter from DatabaseDialect should be deprecated

documentation-website/Writerside/topics/Breaking-Changes.md, exposed-r2dbc/api/exposed-r2dbc.api, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/statements/InsertSuspendExecutable.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/statements/api/R2dbcDatabaseMetadataImpl.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/statements/api/R2dbcResult.kt
**Summary of the change**: Rename new `R2DBCRow` to `R2dbcRow` to match convention of all other R2DBC-specific API and all existing JDBC-specific API.
- **Why**: To keep naming convention (related to acronyms/abbreviations) as consistent as possible, especially with all newly implemented API.
- **What**:
- `R2DBCRow` -> `R2dbcRow`
- Updated breaking changes even though class has only been available since 1.0.0-beta-1
---
=> chore!: Rename R2DBCRow to R2dbcRow

exposed-r2dbc-tests/src/test/kotlin/org/jetbrains/exposed/v1/r2dbc/sql/tests/h2/MultiDatabaseTest.kt, exposed-r2dbc/api/exposed-r2dbc.api, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/transactions/TransactionManager.kt
**Summary of the change**: Replace thread local variable usage in R2DBC `TransactionManager` with `CoroutineContext.Key` + `Element`.
**Description:**
- **How:**
- Introduce internal data holder `TransactionContextHolder` that can be used to pass around transaction & its coroutine context key reference.
- Replace all usages of `ThreadLocal` in `TransactionManager`.
- Pass context holder to `withContext()` in `suspendTransaction()`.
---
There are 2 other uses of `ThreadLocal` in the library:
1. `exposed-core/CoreTransactionManager` - private variable for transaction manager storage
2. `exposed-core/DatabaseDialect` - private variable for explicit dialect storage
I'm not sure if either is worth refactoring currently, but I have wondered if # 1 is potentially related to these issues.
--- …
=> chore: Replace use of thread local in R2DBC transaction manager

exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/mappers/ArrayTypeMapper.kt
**Summary of the change**: Add support for inserting UUID arrays in R2DBC
- **What**: 
- Added UUIDColumnType columnType detector to mapPgArray
- **Why**: It is a logic that supports the implementation of JDBC that is not yet supported in R2DBC.
- **How**: 
---
---
https://youtrack.jetbrains.com/issue/EXPOSED-856/UUID-not-supported-in-Array-R2DBC
=> fix: EXPOSED-856 Add support for inserting UUID arrays in R2DBC

samples/exposed-ktor-r2dbc/build.gradle.kts, samples/exposed-ktor-r2dbc/gradle/libs.versions.toml, samples/exposed-ktor-r2dbc/src/main/kotlin/domain/BaseRepository.kt, samples/exposed-ktor-r2dbc/src/main/kotlin/domain/comment/CommentRepository.kt, samples/exposed-ktor-r2dbc/src/main/kotlin/domain/project/ProjectsTable.kt, samples/exposed-ktor-r2dbc/src/main/kotlin/domain/user/UserRepository.kt, samples/exposed-ktor/src/main/kotlin/Application.kt, samples/exposed-ktor/src/main/kotlin/plugins/Serialization.kt, samples/exposed-migration/README.md
**Summary of the change**: Fix any sample projects that no longer compiled following version bump to 1.0.0-rc-1, or that were missing some details.
**How**:
- **exposed-ktor-r2dbc**
- Remove dependency on PostgreSQL-JDBC (no longer needed following fix in  PR #2579 )
- Replace deprecated `suspendTransaction(context)`
- Add missing imports (following PR #2600 )
- **exposed-ktor**
-  Install content negotiation plugin for JSON (de)-/serialization; otherwise if user attempts to have paths respond at, for example, http://127.0.0.1:8000/users/# it sends back `Error code: 406 Not Acceptable`
- **exposed-migration**
-   Change to dependency code block was missed from docs changes in PR #2604 
---
=> chore: Update sample projects to work with version 1.0.0-rc-1

documentation-website/Writerside/topics/Breaking-Changes.md, documentation-website/Writerside/topics/Statement-Interceptors.md, exposed-r2dbc-tests/src/test/kotlin/org/jetbrains/exposed/v1/r2dbc/sql/tests/shared/StatementInterceptorTests.kt, exposed-r2dbc/api/exposed-r2dbc.api, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/R2dbcTransaction.kt, exposed-r2dbc/src/main/kotlin/org/jetbrains/exposed/v1/r2dbc/statements/SuspendStatementInterceptor.kt, exposed-tests/src/test/kotlin/org/jetbrains/exposed/v1/tests/shared/StatementInterceptorTests.kt
**Summary of the change**: Add statement interceptor to `exposed-r2dbc` that uses suspend methods, so that suspend db operations can potentially be called by them.
- **Why**: `StatementInterceptor` + `GlobalStatementInterceptor` were left in `exposed-core` after V1 refactoring. In the event suspend db operations need to be run in custom interceptor overrides, this would not be possible without the methods themselves suspending.
An example of this is in our own `EntityLifecycleInterceptor` -> If DAO was made to be compatible with R2DBC, `beforeExecution()` would need to suspend.
- **What**:
- No changes have been made to `StatementInterceptor` or JDBC usage
- R2DBC user could continue to rely solely on core's `StatementInterceptor`, if it suites their needs
- If …
=> feat!: EXPOSED-882 Add StatementInterceptor that allows suspend operations
